import {pagePreference} from './grid-preferences.js';
import {lucide} from './tree-icons.js';
import {DataGridView,GridQueryController,GridQueryCancelled} from './data-grid.js';
import {runOwnedGrid,releaseGrid} from './grid-operations.js';
import {id,copy,column,output,emptyModel,active,same,leaves,joins,sharedJoin,connect,disconnect,removeSource,label,dependencies,aggregate} from './visual-model.js';
import {el,button,input,select,field,picker,dialog,editExpression,expressionEditor,parameterDefinitions,parameterValues,queryParameter} from './visual-expressions.js';
export const SOURCE_MIME='application/x-codegraph-query-source';
const COLUMN_MIME='application/x-codegraph-query-column',OUTPUT_MIME='application/x-codegraph-query-output',MAX_SQL=16384;

/** Canvas and grid edit one structured draft. Compilation never executes its data query. */
export class VisualQueryBuilder {
 constructor({api,initialDirty=false,connectionId,connectionName,database='',selection=null,sql='',draft=null,viewEditor=null,changed=()=>{},openScript=()=>{},openBuilder=()=>{},account=()=>{}}){
  Object.assign(this,{api,initialDirty,connectionId,connectionName,database,selection,viewEditor,changed,openScript,openBuilder,account});this.sql=sql;this.originalSql=sql;this.mode='visual';this.model=draft?.version===2?copy(draft):emptyModel();this.restored=!!draft;this.restoredViewBaseline=copy(draft?.viewBaseline??null);delete this.model.viewBaseline;this.positions=copy(draft?.layout?.positions??{});this.zoom=draft?.layout?.zoom??1;this.ratio=draft?.layout?.ratio??.57;this.selectedTab=draft?.layout?.tab==='plan'?'plan':'data';this.quote=draft?.dialect?.quote??'"';this.engine=draft?.dialect?.engine??'jdbc';delete this.model.layout;delete this.model.dialect;this.history=[];this.future=[];this.revision=0;this.compiledRevision=-1;this.values={};this.valueTypes={};this.parameterRevision=0;this.jobIds=new Set();this.result={kind:'rows',columns:[],rows:[],rowCount:0};this.plan=null;this.messages={data:'Run to load rows.',plan:'Explain to request an estimated plan.'};this.saved=initialDirty?null:JSON.stringify(this.model);
  this.controller=new GridQueryController({api,run:(change,execution)=>this.execute(change,execution),canRun:automatic=>!this.disposed&&!this.loading&&!this.viewEditor?.loading&&!this.viewEditor?.unreconciled&&!this.viewEditor?.committed&&!(automatic&&(document.hidden||this.result.grid?.refreshRequired))});this.unsubscribe=this.controller.subscribe(()=>this.executionState());
 }
 get dirty(){if(this.viewEditor&&this.savedViewState&&this.mode==='preserved')return this.mode!==this.savedViewState.mode||this.originalSql!==this.savedViewState.originalSql;return this.mode==='preserved'?this.initialDirty:JSON.stringify(this.model)!==this.saved;}
 get draft(){return this.mode==='preserved'||this.readOnly?undefined:{...copy(this.model),...(this.viewEditor&&this.savedViewBaseline?{viewBaseline:copy(this.savedViewBaseline)}:{}),layout:{positions:copy(this.positions),zoom:this.zoom,ratio:this.ratio,tab:this.selectedTab},dialect:{quote:this.quote,engine:this.engine}};}
 remember(stack,value){stack.push(value);while(stack.length>30||stack.reduce((n,s)=>n+s.length*2,0)>1048576)stack.shift();}
 edit(action){if(this.readOnly||this.mode==='preserved')return;const old=JSON.stringify(this.model);try{action();if(JSON.stringify(this.model).length>1048576)throw Error('The visual draft exceeds its 2 MiB allowance. Remove unused sources or expressions.');if(this.model.detail.outputs.length>256||this.model.summary.outputs.length>256)throw Error('Maximum 256 output columns. Uncheck columns before adding more sources.');}catch(e){this.model=JSON.parse(old);throw e;}this.viewEditor?.diagramChanged();this.remember(this.history,old);this.future=[];this.revision++;this.controller.stopRefresh();this.changed(this);this.refreshCanvas();this.scheduleCompile();this.updateStatus();}
 undo(redo=false){if(this.readOnly)return;const from=redo?this.future:this.history,to=redo?this.history:this.future;if(!from.length)return;this.remember(to,JSON.stringify(this.model));this.model=JSON.parse(from.pop());this.revision++;this.controller.stopRefresh();this.refreshCanvas();this.scheduleCompile();this.changed(this);}
 scheduleCompile(){clearTimeout(this.compileTimer);this.compiledRevision=-1;this.sql='';this.updateStatus();this.compileTimer=setTimeout(()=>void this.compile(),80);}
 async compile(){clearTimeout(this.compileTimer);if(this.mode==='preserved'||this.readOnly)return;const revision=this.revision;if(this.compilation?.revision===revision)return this.compilation.promise;const promise=(async()=>{try{const result=await this.api('/query-builder/compile','POST',{connectionId:this.connectionId,model:copy(this.model),quote:this.quote,engine:this.engine,uniqueOutputNames:!!this.viewEditor});if(this.disposed||revision!==this.revision)return;this.compiled=result;this.compiledRevision=revision;this.sql=result.sql??'';if(result.valid&&this.viewEditor?.querySource==='diagram')this.viewEditor.acceptDiagramQuery(this.sql);this.changed(this);this.updateStatus();return result;}catch(e){if(revision===this.revision){this.compiled={valid:false,diagnostics:[{message:e.message}]};this.compiledRevision=revision;this.sql='';this.updateStatus();}throw e;}})();this.compilation={revision,promise};promise.catch(()=>{});return promise;}
 updateOutputAliases(){const aliases=new Map((this.compiledRevision===this.revision?this.compiled?.outputs??[]:[]).map(o=>[o.id,o.automaticAlias]));for(const row of this.board?.querySelectorAll('.qb-output-row')??[]){const field=row.querySelector('input'),alias=aliases.get(row.dataset.output)??'';if(field){field.placeholder=alias;field.title=alias?'Automatic view column name: '+alias+'. Enter an alias to override.':'';}}}
 async currentQuery(){while(this.compiledRevision!==this.revision){await this.compile();if(this.disposed)throw Error('Builder closed');}if(!this.compiled?.valid)throw Error(this.compiled?.diagnostics?.map(d=>d.message).join(' ')||'Complete the query first.');return copy(this.compiled);}
 async job(path,payload){const job=await this.api(path,'POST',payload);this.jobIds.add(job.id);try{let current=job;while(!['complete','failed','cancelled'].includes(current.state)){if(this.disposed)await this.api('/jobs/'+job.id+'/cancel','POST',{});await new Promise(r=>setTimeout(r,200));current=await this.api('/jobs/'+job.id);}if(this.disposed)throw Error('Builder closed');if(current.state!=='complete')throw Error(current.error||'Metadata operation failed');return current.result;}finally{this.jobIds.delete(job.id);await this.api('/jobs/'+job.id,'DELETE').catch(()=>{});}}
 metadata(source){this.database=source.database??this.database;this.quote=source.quote??this.quote;this.engine=source.engine??this.engine;this.explainCapability=source.explainCapability;}
 insertSource(source){let number=1;while(this.model.sources.some(s=>s.alias==='t'+number))number++;const s={id:id(),name:source.name,reference:source.reference,alias:'t'+number,columns:source.columns??[],kind:source.kind,notice:source.notice};this.model.sources.push(s);this.model.roots.push({kind:'source',source:s.id});for(const c of s.columns) this.model.detail.outputs.push(output(column(s.id,c.name)));if(this.model.mode==='summary')for(const c of s.columns){const e=column(s.id,c.name);this.model.summary.groups.push({id:id(),expression:e});this.model.summary.outputs.push(output(copy(e)));}return s;}
 async initialize(){if(this.initialized)return;this.initialized=true;this.loading=true;this.notice('Reading query sources...');try{if(this.viewEditor){await this.initializeView();}else if(this.restored){await this.compile();}else if(this.selection){const source=await this.job('/query-builder/source',{connectionId:this.connectionId,...this.selection});this.metadata(source);this.source=source;if(source.kind==='tables'){this.readOnly=true;this.insertSource(source);this.sql=source.sql;this.notice('Relationship diagram. Open a new query from this source to compose a SELECT.');}else if(source.definition)await this.importSql(source.definition,false);else{this.insertSource(source);this.notice(source.definitionNotice??'Query selects from this view.');await this.compile();}}else if(this.sql)await this.importSql(this.sql,false);else await this.compile();if(!this.initialDirty&&!this.viewEditor)this.saved=JSON.stringify(this.model);this.changed(this);}catch(e){this.notice(e.message);}finally{this.loading=false;if(this.message==='Reading query sources...')this.notice('Canvas changes update the preview. Run fetches rows.');this.render();}}
 viewState(){return {model:copy(this.model),positions:copy(this.positions),zoom:this.zoom,ratio:this.ratio,mode:this.mode,originalSql:this.originalSql};}
 markViewSaved(){if(this.viewEditor?.snapshot&&this.compiled?.valid)this.savedViewBaseline={fingerprint:this.viewEditor.snapshot.fingerprint,sql:this.sql};this.saved=JSON.stringify(this.model);this.initialDirty=false;this.savedViewState=this.viewState();this.changed(this);this.syncViewActions();}
 async initializeView(){
  const restored=this.restored?this.viewState():null;if(!this.viewEditor.snapshot)await this.viewEditor.load();
  if(!this.viewEditor.snapshot)throw Error(this.viewEditor.message||'Cannot load the view definition.');
  const snapshot=this.viewEditor.snapshot;this.metadata({database:snapshot.database,engine:snapshot.engine,quote:snapshot.quote});
  const query=snapshot.fields.query??'';
  if(query.trim())await this.importSql(query,false);
  else{if(!snapshot.creation)throw Error('The database did not expose this view definition. Open Properties to inspect its DDL.');this.mode='visual';this.model=emptyModel();this.originalSql='';this.revision++;this.compiledRevision=-1;await this.compile();}
  this.render();this.markViewSaved();const savedSql=this.sql;let keepDefinition=false;
  if(restored){this.viewEditor.querySource='definition';Object.assign(this,restored);this.revision++;this.compiledRevision=-1;await this.compile();const clean=this.compiled?.valid&&(this.sql===savedSql||this.restoredViewBaseline?.fingerprint===this.viewEditor.snapshot.fingerprint&&this.sql===this.restoredViewBaseline.sql);if(clean)this.markViewSaved();else if(this.compiled?.valid){this.viewEditor.querySource='diagram';this.viewEditor.acceptDiagramQuery(this.sql);}}
  else if(this.viewEditor.draft.fields.query!==query){await this.importSql(this.viewEditor.draft.fields.query,true);keepDefinition=this.mode==='preserved';if(keepDefinition)this.viewEditor.querySource='definition';}
  if(!keepDefinition)this.viewEditor.querySource='diagram';
 }
 async syncViewDefinition(){
  if(!this.viewEditor||!this.initialized||this.loading||!this.viewEditor.snapshot||this.viewEditor.querySource!=='definition')return;
  const query=this.viewEditor.draft?.fields?.query??'',current=this.mode==='preserved'?this.originalSql:this.sql;
  if(query===current){this.viewEditor.querySource='diagram';return;}
  this.loading=true;this.updateStatus();
  try{
   if(query.trim()){await this.importSql(query,true);if(this.mode==='preserved')this.viewEditor.querySource='definition';}
   else{this.viewEditor.diagramChanged();this.mode='visual';this.originalSql='';this.edit(()=>this.model=emptyModel());await this.compile();this.render();}
  }finally{this.loading=false;this.updateStatus();}
 }
 async restoreView(){
  if(!this.savedViewState)return;await this.settle();clearTimeout(this.compileTimer);Object.assign(this,copy(this.savedViewState));this.revision++;this.compiledRevision=-1;this.history=[];this.future=[];this.values={};this.valueTypes={};this.parameterRevision++;
  if(this.mode==='visual')await this.compile();else this.sql=this.originalSql;this.saved=JSON.stringify(this.model);this.initialDirty=false;this.render();this.changed(this);this.updateStatus();
 }
 async reloadView(query){await this.settle();await this.importSql(query,false);this.history=[];this.future=[];this.render();this.markViewSaved();}
 syncViewActions(){
  if(!this.viewEditor)return;this.grid?.updateDraftActions();const busy=!!(this.viewEditor.loading||this.viewEditor.unreconciled||this.viewEditor.committed);
  const save=this.root?.querySelector('[aria-label="Save view"]');if(save)save.disabled=busy||!this.viewEditor.dirty||this.loading||this.controller.busy||this.viewEditor.querySource==='diagram'&&(this.compiledRevision!==this.revision||this.compiled?.diagnostics?.some(d=>d.code==='join_type_resolution'));
  if(this.runButton)this.runButton.disabled=busy||this.controller.busy||this.loading||this.readOnly||this.mode==='preserved'||this.compiledRevision!==this.revision||!this.compiled?.valid;
  if(this.explainButton)this.explainButton.disabled=this.runButton.disabled;
  for(const area of [this.upper,this.root?.querySelector('.qb-toolbar')])if(area)area.inert=busy;if(this.grid?.interactive)this.grid.interactive.inert=busy||this.controller.busy&&!this.controller.scrolling;
 }

 async importSql(sql,dirty=true){if(!sql.trim()||sql.length>MAX_SQL)throw Error('Import one SELECT of at most 16 KiB.');const revision=this.importRevision=(this.importRevision??0)+1;const result=await this.job('/query-builder/import',{connectionId:this.connectionId,database:this.database,sql});if(this.disposed||revision!==this.importRevision)return;this.metadata(result);if(dirty){this.remember(this.history,JSON.stringify(this.model));this.viewEditor?.diagramChanged();}this.mode=result.editable&&result.visualModel?'visual':'preserved';this.originalSql=sql;this.model=result.visualModel??emptyModel();this.sql=sql;this.revision++;this.compiledRevision=-1;this.notice(result.notice??'Imported query.');if(this.mode==='visual')await this.compile();if(!dirty)this.saved=JSON.stringify(this.model);this.controller.stopRefresh();this.changed(this);this.render();}
 async addSource(payload,position=null){if(this.readOnly)throw Error('This relationship diagram is read-only. Open a new query from source.');if(payload.connectionId!==this.connectionId)throw Error('Use sources from the same connection.');if(this.mode!=='visual')throw Error('Start a new visual query before adding sources to preserved SQL.');if(this.database&&payload.parent.database&&this.database!==payload.parent.database)throw Error('Use sources from the same database.');if(this.loading)throw Error('Wait for source discovery.');this.loading=true;this.updateStatus();try{const source=await this.job('/query-builder/source',{...payload,connectionId:this.connectionId,sourceConnectionId:payload.connectionId,database:this.database||payload.parent.database});this.metadata(source);this.edit(()=>{const s=this.insertSource(source);if(position)this.positions[s.id]=position;});this.notice('Connect column handles to define joins. Sources are never joined automatically.');}finally{this.loading=false;this.updateStatus();}}
 mount(host){this.unmount();this.host=host;this.render();void this.initialize();}
 unmount(){this.captureCanvasState();this.grid?.destroy();this.grid=null;this.resizeObserver?.disconnect();this.resizeObserver=null;this.host=null;this.root=null;this.board=null;this.svg=null;this.resultHost=null;this.planHost=null;}
 async settle(){this.controller.stopRefresh();this.valueDialog?.close();await this.controller.cancel();await this.controller.completion?.catch(e=>{if(this.controller.uncertain)throw e;});}
 get rowsDirty(){return DataGridView.dirty(this.result);}
 async guardRows(){return DataGridView.guard(this.result,()=>this.controller.execute({action:'save_rows'}));}
 async ownedGrid(change,execution){
   return runOwnedGrid(this.result,change,execution,{api:this.api,replace:async(next,options={})=>{
     this.account(this.retainedBytes(next,this.plan));const outputIds=new Map((this.result.columns??[]).map(c=>[c.id,c.outputId]));if(next.columns)next.columns=next.columns.map(c=>({...c,outputId:outputIds.get(c.id)}));DataGridView.replacePage(this.result,next,options.window);
     this.resultSql=next.sourceSql??this.resultSql;this.grid?.updateData(this.resultSql);
   }});
 }
 async dispose(){this.disposed=true;clearTimeout(this.compileTimer);this.valueDialog?.close();this.importModal?.close();this.unmount();this.unsubscribe?.();for(const job of this.jobIds)void this.api('/jobs/'+job+'/cancel','POST',{}).catch(()=>{});await this.controller.dispose();await releaseGrid(this.api,this.result);this.account(0);}
 action(title,icon,callback,disabled=false){const b=button('',()=>{Promise.resolve().then(callback).catch(e=>this.notice(e.message));},'qb-icon');b.title=title;b.setAttribute('aria-label',title);b.append(lucide(icon));b.disabled=disabled;return b;}
 notice(message){this.message=message;if(this.status)this.status.textContent=message;}
 render(){if(!this.host||this.disposed)return;this.captureCanvasState();const scroll=this.viewport?{left:this.viewport.scrollLeft,top:this.viewport.scrollTop}:null;this.grid?.destroy();this.grid=null;this.resizeObserver?.disconnect();const root=el('section','query-builder');root.setAttribute('aria-label','Visual Query Builder');this.host.replaceChildren(root);this.root=root;
  const toolbar=el('div','qb-toolbar');toolbar.setAttribute('role','toolbar');toolbar.setAttribute('aria-label','Visual query actions');toolbar.append(this.action('New query','file-plus',()=>{this.mode='visual';this.readOnly=false;this.edit(()=>this.model=emptyModel());this.render();}),this.action('Open query file','folder-open',()=>this.openFile()),this.action(this.viewEditor?'Save view':'Save query','save',()=>this.viewEditor?this.viewEditor.save():this.saveFile()),this.action('Save query as','copy',()=>this.saveFile(true)),this.action('Copy SQL','copy',async()=>navigator.clipboard.writeText((await this.currentQuery()).sql)),this.action('Undo','undo-2',()=>this.undo()),this.action('Redo','redo-2',()=>this.undo(true)),this.action('Paste or import SQL','file-code',()=>this.importDialog()),this.action('Add source','plus',()=>this.sourcePicker()),this.action('Connect columns','link',()=>this.connectionDialog()),this.action('Parameters','list',()=>parameterDefinitions(this)));
  if(this.readOnly)for(const control of toolbar.querySelectorAll('button'))control.disabled=true;const target=el('span','qb-target',this.connectionName+(this.database?' / '+this.database:''));toolbar.append(target);if(this.readOnly)toolbar.append(this.action('New query from source','workflow',()=>this.openBuilder(this.source.sql,this.database)));this.explainButton=this.action('Explain query','workflow',()=>this.run('plan'));this.explainButton.classList.add('qb-explain-button');this.explainButton.append(el('span','','Explain'));this.runButton=this.action('Run query (Ctrl+Enter)','play',()=>this.run('data'));toolbar.append(this.explainButton,this.runButton);root.append(toolbar);this.status=el('div','qb-status',this.message??'');this.status.setAttribute('role','status');root.append(this.status);
  this.upper=el('div','qb-upper');this.upper.style.flex='0 0 '+this.ratio*100+'%';root.append(this.upper);this.renderCanvas();if(scroll){this.viewport.scrollLeft=scroll.left;this.viewport.scrollTop=scroll.top;}
  const divider=el('div','qb-divider');divider.tabIndex=0;divider.setAttribute('role','separator');divider.setAttribute('aria-label','Resize query builder and results');divider.setAttribute('aria-orientation','horizontal');const resize=value=>{this.ratio=Math.max(.25,Math.min(.8,value));this.upper.style.flex='0 0 '+this.ratio*100+'%';divider.setAttribute('aria-valuenow',Math.round(this.ratio*100));this.changed(this);};divider.setAttribute('aria-valuenow',Math.round(this.ratio*100));divider.onpointerdown=e=>{if(e.button===0)divider.setPointerCapture(e.pointerId);};divider.onpointermove=e=>{if(divider.hasPointerCapture(e.pointerId)){const r=root.getBoundingClientRect();resize((e.clientY-r.top)/r.height);}};divider.onkeydown=e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();resize(this.ratio+(e.key==='ArrowDown'?.05:-.05));}};
  if(!this.readOnly){root.append(divider);const results=el('div','qb-results');const nav=el('div','qb-output-tabs');nav.setAttribute('role','tablist');nav.setAttribute('aria-label','Query output');this.tabButtons={};for(const [key,title]of [['data','Data Grid'],['plan','Explain Plan']]){const b=button(title,()=>this.selectTab(key));b.setAttribute('role','tab');b.id='qb-tab-'+key+'-'+this.connectionId;b.setAttribute('aria-controls',b.id+'-panel');b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();this.selectTab(key==='data'?'plan':'data');this.tabButtons[this.selectedTab].focus();}};this.tabButtons[key]=b;nav.append(b);}this.resultPanel=el('div','qb-output-panel');this.planPanel=el('div','qb-output-panel');for(const [key,panel]of [['data',this.resultPanel],['plan',this.planPanel]]){panel.id=this.tabButtons[key].id+'-panel';panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',this.tabButtons[key].id);}this.dataStatus=el('div','qb-operation-status');this.dataStatus.setAttribute('role','status');this.staleData=el('div','qb-stale');this.resultHost=el('div','qb-grid');this.resultPanel.append(this.resultHost);this.planStatus=el('div','qb-operation-status');this.planStatus.setAttribute('role','status');this.stalePlan=el('div','qb-stale');this.planHost=el('div','qb-plan-content');this.planPanel.append(this.planStatus,this.stalePlan,this.planHost);results.append(nav,this.resultPanel,this.planPanel);root.append(results);this.mountGrid();this.renderPlan();this.selectTab(this.selectedTab,false);}else this.upper.style.flex='1';
  root.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();e.stopPropagation();void this.run('data');}};this.updateStatus();this.executionState();
 }
 selectTab(tab,persist=true){this.selectedTab=tab;for(const [key,b]of Object.entries(this.tabButtons??{})){b.setAttribute('aria-selected',String(key===tab));b.tabIndex=key===tab?0:-1;}if(this.resultPanel)this.resultPanel.hidden=tab!=='data';if(this.planPanel)this.planPanel.hidden=tab!=='plan';if(persist)this.changed(this);}
 refreshCanvas(){if(!this.upper)return;const p={left:this.viewport?.scrollLeft??0,top:this.viewport?.scrollTop??0};this.renderCanvas();this.viewport.scrollLeft=p.left;this.viewport.scrollTop=p.top;}
 captureCanvasState(){if(!this.board?.isConnected)return;const focused=document.activeElement,row=focused?.closest('.qb-column'),card=row?.closest('.qb-source');this.canvasState={left:this.viewport.scrollLeft,top:this.viewport.scrollTop,sources:new Map([...this.board.querySelectorAll('.qb-source')].map(card=>{const fields=card.querySelector('.qb-source-columns');return [card.dataset.source,{left:fields.scrollLeft,top:fields.scrollTop}];})),focus:card&&this.board.contains(card)?{source:card.dataset.source,column:row.dataset.column,selector:focused.matches('input[type="checkbox"]')?'input[type="checkbox"]':'.qb-column-handle'}:null};}
 restoreCanvasState(){const state=this.canvasState;if(!state)return;const retained=new Map();for(const card of this.board.querySelectorAll('.qb-source')){const position=state.sources.get(card.dataset.source),fields=card.querySelector('.qb-source-columns');if(position){fields.scrollLeft=position.left;fields.scrollTop=position.top;retained.set(card.dataset.source,position);}if(state.focus?.source===card.dataset.source){const row=[...fields.children].find(row=>row.dataset.column===state.focus.column);row?.querySelector(state.focus.selector)?.focus({preventScroll:true});}}state.sources=retained;this.viewport.scrollLeft=state.left;this.viewport.scrollTop=state.top;}
 renderCanvas(){this.captureCanvasState();this.upper.replaceChildren();if(this.mode==='preserved'){const panel=el('div','qb-preserved');panel.append(el('h3','','SQL preserved for inspection'),el('p','',this.message),button('Open in Script',()=>this.openScript(this.originalSql,this.database)));const text=el('textarea');text.readOnly=true;text.value=this.originalSql;text.setAttribute('aria-label','Preserved SQL');panel.append(text);this.upper.append(panel);this.board=null;return;}
  const viewport=el('div','qb-canvas');viewport.tabIndex=0;viewport.setAttribute('aria-label','Query diagram canvas');this.viewport=viewport;const board=el('div','qb-board');board.style.zoom=this.zoom;this.board=board;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('qb-connections');board.append(svg);this.svg=svg;viewport.append(board);this.upper.append(viewport);
  viewport.ondragover=e=>{if([...e.dataTransfer.types].includes(SOURCE_MIME)){e.preventDefault();e.dataTransfer.dropEffect='copy';}};viewport.ondrop=e=>{if(!e.dataTransfer.types.includes(SOURCE_MIME))return;e.preventDefault();const text=e.dataTransfer.getData(SOURCE_MIME);if(text.length>8192)return;const r=board.getBoundingClientRect();try{void this.addSource(JSON.parse(text),{x:Math.max(8,(e.clientX-r.left)/this.zoom),y:Math.max(8,(e.clientY-r.top)/this.zoom)}).catch(error=>this.notice(error.message));}catch{this.notice('Invalid source.');}};
  const tools=el('div','qb-canvas-tools');tools.append(this.action('Zoom out','zoom-out',()=>{this.zoom=Math.max(.5,this.zoom-.1);this.refreshCanvas();this.changed(this);}),el('span','',Math.round(this.zoom*100)+'%'),this.action('Zoom in','zoom-in',()=>{this.zoom=Math.min(1.5,this.zoom+.1);this.refreshCanvas();this.changed(this);}),this.action('Arrange sources','workflow',()=>{this.positions={};this.refreshCanvas();this.changed(this);}));viewport.append(tools);
  let sources=this.model.sources;if(this.readOnly){const related=new Map();for(const rel of this.source?.relationships??[]){const prefix=rel.direction==='incoming'?'FK':'PK',reference=[rel[prefix+'TABLE_SCHEM'],rel[prefix+'TABLE_NAME']].filter(Boolean).join('.');if(!related.has(reference))related.set(reference,{id:'r'+related.size,name:reference,reference,columns:[],relationships:[]});const s=related.get(reference);if(!s.columns.some(c=>c.name===rel[prefix+'COLUMN_NAME']))s.columns.push({name:rel[prefix+'COLUMN_NAME'],type:'Key'});s.relationships.push(rel);}sources=[...sources,...related.values()];}this.canvasSources=sources;sources.forEach((s,i)=>this.card(s,i));
  if(!sources.length)board.append(el('p','qb-empty','Drag tables and views here, or use Add source. Connect column handles to create joins.'));if(!this.readOnly)this.outputCard();this.expandCanvas();this.restoreCanvasState();requestAnimationFrame(()=>this.drawLines());this.resizeObserver?.disconnect();this.resizeObserver=new ResizeObserver(()=>this.drawLines());this.resizeObserver.observe(board);
 }
 place(card,key,index){const p=this.positions[key]??={x:24+(index%3)*340,y:48+Math.floor(index/3)*350};card.style.left=p.x+'px';card.style.top=p.y+'px';const head=card.querySelector('.qb-source-head');head.tabIndex=0;head.setAttribute('aria-label','Move '+(key==='output'?'Query Output':this.canvasSources.find(s=>s.id===key)?.name)+' with arrow keys');let start;const move=(x,y)=>{p.manual=true;p.x=Math.max(8,x);p.y=Math.max(8,y);card.style.left=p.x+'px';card.style.top=p.y+'px';this.expandCanvas();this.drawLines();};head.onpointerdown=e=>{if(e.button||e.target.closest('button,input,select'))return;head.setPointerCapture(e.pointerId);start={x:e.clientX,y:e.clientY,px:p.x,py:p.y};};head.onpointermove=e=>{if(head.hasPointerCapture(e.pointerId)&&start)move(start.px+(e.clientX-start.x)/this.zoom,start.py+(e.clientY-start.y)/this.zoom);};head.onpointerup=()=>this.changed(this);head.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||e.target!==head)return;e.preventDefault();move(p.x+(e.key==='ArrowLeft'?-16:e.key==='ArrowRight'?16:0),p.y+(e.key==='ArrowUp'?-16:e.key==='ArrowDown'?16:0));this.changed(this);};}
 // Keep SVG units in canvas pixels; a viewBox would rescale/recenter lines when CSS minimum dimensions exceed the content size.
 expandCanvas(){if(!this.board)return;let width=1000,height=500;for(const card of this.board.querySelectorAll('.qb-source,.qb-output-card')){width=Math.max(width,card.offsetLeft+card.offsetWidth+100);height=Math.max(height,card.offsetTop+card.offsetHeight+100);}this.board.style.width=width+'px';this.board.style.height=height+'px';}
 card(source,index){const card=el('article','qb-source');card.dataset.source=source.id;const head=el('div','qb-source-head');head.append(lucide('database'),el('strong','',source.name));if(!this.readOnly)head.append(this.action('Remove source '+source.alias,'x',()=>this.edit(()=>removeSource(this.model,source.id))));card.append(head);if(!this.readOnly)card.append(field('Alias',input('Alias for '+source.alias,source.alias,value=>{try{this.edit(()=>source.alias=value);}catch(e){this.notice(e.message);}})));else card.append(el('div','qb-reference',source.reference));const fields=el('div','qb-source-columns');fields.onscroll=()=>this.drawLines();for(const c of source.columns??[]){const e=column(source.id,c.name),row=el('div','qb-column');row.dataset.column=c.name;row.title=c.name+' / '+c.type;if(!this.readOnly){const checked=active(this.model).outputs.some(o=>same(o.expression,e));const check=input('Select '+source.alias+'.'+c.name,checked,value=>{try{this.edit(()=>{if(value){active(this.model).outputs.push(output(e));if(this.model.mode==='summary'&&!this.model.summary.groups.some(g=>same(g.expression,e)))this.model.summary.groups.push({id:id(),expression:copy(e)});}else active(this.model).outputs=active(this.model).outputs.filter(o=>!same(o.expression,e));});}catch(err){check.checked=!value;this.notice(err.message);}},'checkbox');row.append(check);}
   const handle=button(c.name,()=>{if(!this.readOnly)this.connectionDialog(e,handle);},'qb-column-handle');handle.dataset.column=c.name;handle.title='Connect '+(source.alias??source.name)+'.'+c.name;handle.setAttribute('aria-label',handle.title);if(!this.readOnly){handle.draggable=true;handle.ondragstart=event=>{this.columnDrag=e;event.dataTransfer.setData(COLUMN_MIME,JSON.stringify(e));};handle.ondragend=()=>this.columnDrag=null;handle.ondragover=event=>{if(event.dataTransfer.types.includes(COLUMN_MIME)){event.preventDefault();handle.classList.add('qb-column-over');}};handle.ondragleave=()=>handle.classList.remove('qb-column-over');handle.ondrop=event=>{event.preventDefault();event.stopPropagation();handle.classList.remove('qb-column-over');if(this.columnDrag)this.joinDrop(this.columnDrag,e,handle);this.columnDrag=null;};}row.append(handle,el('small','',c.type));fields.append(row);}card.append(fields);if(!this.readOnly)card.append(button('Cross join...',()=>this.crossDialog(source)));this.board.append(card);this.place(card,source.id,index);}

 outputCard(){const card=el('article','qb-output-card');const head=el('div','qb-source-head');head.append(lucide('list'),el('strong','','Query Output'),this.action(this.positions.output?.collapsed?'Expand Query Output':'Collapse Query Output',this.positions.output?.collapsed?'chevron-down':'chevron-up',()=>{this.positions.output.collapsed=!this.positions.output.collapsed;this.refreshCanvas();this.changed(this);}));card.append(head);if(!this.positions.output?.manual)this.positions.output={...this.positions.output,x:Math.max(364,...this.model.sources.map(s=>(this.positions[s.id]?.x??24)+340)),y:this.positions.output?.y??48};const content=el('div','qb-output-content');content.hidden=!!this.positions.output.collapsed;card.append(content);content.append(field('Mode',select('Output mode',[['detail','Detail'],['summary','Summary']],this.model.mode,v=>this.edit(()=>this.model.mode=v))),field('DISTINCT',input('Distinct rows',this.model.distinct,v=>this.edit(()=>this.model.distinct=v),'checkbox')));
  const area=el('div','qb-output-list');area.setAttribute('aria-label','Ordered query outputs');active(this.model).outputs.forEach((o,i)=>{const row=el('div','qb-output-row');row.dataset.output=o.id;row.draggable=true;row.ondragstart=e=>{e.dataTransfer.setData(OUTPUT_MIME,o.id);};row.ondragover=e=>{if(e.dataTransfer.types.includes(OUTPUT_MIME))e.preventDefault();};row.ondrop=e=>{if(!e.dataTransfer.types.includes(OUTPUT_MIME))return;e.preventDefault();const source=e.dataTransfer.getData(OUTPUT_MIME);this.edit(()=>{const outputs=active(this.model).outputs,index=outputs.findIndex(a=>a.id===source);if(index<0)return;const [item]=outputs.splice(index,1);outputs.splice(outputs.indexOf(o),0,item);});};const errors=dependencies(o.expression,this.model);row.classList.toggle('qb-invalid',errors.length>0);const expression=button(label(o.expression,this.model),()=>editExpression(this,'Edit output',o.expression,e=>this.edit(()=>o.expression=e),{allowOutputs:false,allowAggregate:this.model.mode==='summary'}),'qb-output-expression');expression.title=errors.join('\n')||expression.textContent;row.append(el('span','qb-order-number',String(i+1)),expression,input('Alias for output '+(i+1),o.alias,v=>this.edit(()=>o.alias=v)),this.action('Move output '+(i+1)+' up','chevron-up',()=>this.edit(()=>{const a=active(this.model).outputs;[a[i-1],a[i]]=[a[i],a[i-1]];}),i===0),this.action('Move output '+(i+1)+' down','chevron-down',()=>this.edit(()=>{const a=active(this.model).outputs;[a[i],a[i+1]]=[a[i+1],a[i]];}),i===active(this.model).outputs.length-1),this.action('Remove output '+(i+1),'x',()=>this.edit(()=>active(this.model).outputs=active(this.model).outputs.filter(a=>a.id!==o.id))));area.append(row);});content.append(area,button('Calculated column',()=>editExpression(this,'Calculated column',null,e=>this.edit(()=>active(this.model).outputs.push(output(e))),{allowOutputs:false,allowAggregate:this.model.mode==='summary'})));
  const drop=(title,callback)=>{const zone=el('div','qb-drop-zone',title);zone.tabIndex=0;zone.setAttribute('role','button');zone.onclick=()=>editExpression(this,title,null,callback,{allowOutputs:false,allowAggregate:false});zone.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();zone.click();}};zone.ondragover=e=>{if(e.dataTransfer.types.includes(COLUMN_MIME))e.preventDefault();};zone.ondrop=e=>{if(!this.columnDrag)return;e.preventDefault();e.stopPropagation();callback(copy(this.columnDrag));this.columnDrag=null;};content.append(zone);return zone;};
  if(this.model.mode==='summary'){drop('Group by - drop a column or choose an expression',e=>this.edit(()=>{if(!this.model.summary.groups.some(g=>same(g.expression,e))){this.model.summary.groups.push({id:id(),expression:e});if(!active(this.model).outputs.some(o=>same(o.expression,e)))active(this.model).outputs.push(output(copy(e)));}}));for(const group of this.model.summary.groups){const row=el('div','qb-group-expression');row.append(button(label(group.expression,this.model),()=>editExpression(this,'Group by',group.expression,e=>this.edit(()=>group.expression=e),{allowOutputs:false,allowAggregate:false})),this.action('Remove group','x',()=>this.edit(()=>this.model.summary.groups=this.model.summary.groups.filter(g=>g.id!==group.id))));content.append(row);}drop('Aggregates - drop a column or choose an expression',e=>this.aggregateDialog(e));}else drop('Outputs - drop a column',e=>this.edit(()=>active(this.model).outputs.push(output(e))));this.board.append(card);this.place(card,'output',0);this.updateOutputAliases();
 }
 aggregateDialog(expression){const body=el('div');let name='COUNT',distinct=false;body.append(el('p','',label(expression,this.model)),field('Function',select('Aggregate function',['COUNT','SUM','AVG','MIN','MAX'],name,v=>name=v)),field('DISTINCT',input('Distinct aggregate',false,v=>distinct=v,'checkbox')),button('Database aggregate functions',()=>{editExpression(this,'Aggregate expression',{kind:'function',name:'COUNT',args:[expression]},e=>this.edit(()=>active(this.model).outputs.push(output(e))),{allowOutputs:false,allowAggregate:true});d.close();}));const d=dialog('Aggregate column',body,{saveLabel:'Add aggregate',save:()=>this.edit(()=>active(this.model).outputs.push(output({kind:'function',name,distinct,args:[expression]})))});}
 anchor(source,name){if(!this.board)return null;const card=[...this.board.querySelectorAll('.qb-source')].find(c=>c.dataset.source===source);if(!card)return null;const row=[...card.querySelectorAll('.qb-column-handle')].find(c=>c.dataset.column===name),rect=(row??card.querySelector('.qb-source-head')).getBoundingClientRect(),base=this.board.getBoundingClientRect(),edge=card.getBoundingClientRect(),scroller=card.querySelector('.qb-source-columns').getBoundingClientRect();return {x:(edge.left-base.left)/this.zoom,y:(Math.max(scroller.top+5,Math.min(scroller.bottom-5,rect.top+rect.height/2))-base.top)/this.zoom,right:(edge.right-base.left)/this.zoom};}
 drawLines(){if(!this.svg||!this.board?.isConnected)return;const focused=this.svg.contains(document.activeElement)?document.activeElement.getAttribute('aria-label'):null;this.svg.replaceChildren();const line=(a,b,title,join)=>{if(!a||!b)return;const forward=a.x<=b.x,x=forward?a.right:a.x,end=forward?b.x:b.right,dx=Math.abs(end-x)*.45;const group=document.createElementNS(this.svg.namespaceURI,'g');const path=document.createElementNS(this.svg.namespaceURI,'path');path.setAttribute('d',`M ${x} ${a.y} C ${x+(forward?dx:-dx)} ${a.y}, ${end+(forward?-dx:dx)} ${b.y}, ${end} ${b.y}`);const text=document.createElementNS(this.svg.namespaceURI,'text');text.setAttribute('x',(x+end)/2);text.setAttribute('y',(a.y+b.y)/2-6);text.setAttribute('text-anchor','middle');text.textContent=title;group.append(path,text);if(join){group.setAttribute('role','button');group.setAttribute('tabindex','0');group.setAttribute('aria-label','Edit '+title+' join '+join.id);group.onclick=()=>this.joinEditor(join,group);group.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();this.joinEditor(join,group);}};}this.svg.append(group);};
  if(this.readOnly){for(const s of this.canvasSources.slice(1))for(const rel of s.relationships){const incoming=rel.direction==='incoming';line(this.anchor(this.model.sources[0].id,rel[(incoming?'PK':'FK')+'COLUMN_NAME']),this.anchor(s.id,rel[(incoming?'FK':'PK')+'COLUMN_NAME']),rel.FK_NAME||'Foreign key',null);}return;}
  for(const join of joins(this.model)){if(join.type==='CROSS')line(this.anchor(leaves(join.left)[0],''),this.anchor(leaves(join.right)[0],''),'CROSS',join);else for(const [i,pair]of join.pairs.entries())line(this.anchor(pair.left.source,pair.left.name),this.anchor(pair.right.source,pair.right.name),(i?'AND ':'')+join.type+' '+pair.op,join);}
  if(focused)[...this.svg.children].find(group=>group.getAttribute('aria-label')===focused)?.focus({preventScroll:true});
 }
 joinDrop(left,right,anchor){if(left.source===right.source){this.notice('Add the table again to create a self-join between separate instances.');return;}const existing=sharedJoin(this.model,left.source,right.source);this.joinEditor(existing,anchor,{left:copy(left),right:copy(right)});}
 joinEditor(join,anchor,pair=null){
  const baseRevision=this.revision,draft=join?copy(join):{id:id(),type:'INNER',pairs:[],left:copy(this.model.roots.find(n=>leaves(n).includes(pair.left.source))),right:copy(this.model.roots.find(n=>leaves(n).includes(pair.right.source)))};
  if(pair)draft.pairs.push({id:id(),op:'=',...pair});let sequence=0,assessments=[],pending=true,error='',d;
  const body=el('div'),names=node=>leaves(node).map(id=>this.model.sources.find(s=>s.id===id)?.alias??'[missing source]').join(', ');
  const candidate=()=>{const model=copy(this.model);let target=joins(model).find(n=>n.id===draft.id);if(!target){const p=draft.pairs[0];if(!p)throw Error('Add a column predicate, or disconnect and choose Cross join explicitly.');target=connect(model,p.left,p.right,draft.type==='CROSS'?'INNER':draft.type,p.op);}Object.assign(target,copy(draft),{type:draft.type==='CROSS'?'INNER':draft.type});return model;};
  const analyze=async()=>{const ticket=++sequence;pending=true;error='';render();try{const result=await this.api('/query-builder/compile','POST',{connectionId:this.connectionId,model:candidate(),quote:this.quote,engine:this.engine,uniqueOutputNames:!!this.viewEditor});if(!d.open||ticket!==sequence||this.disposed)return;if(this.revision!==baseRevision)throw Error('The canvas changed. Close and reopen this join to review its current columns.');assessments=(result.joinTypes??[]).filter(a=>a.joinId===draft.id);if(assessments.length!==draft.pairs.length)throw Error(result.diagnostics?.map(a=>a.message).join(' ')||'Column type information is unavailable. Retry or close this editor.');}catch(e){if(!d.open||ticket!==sequence)return;error=e.message;assessments=[];}finally{if(d.open&&ticket===sequence){pending=false;render();}}};
  const render=()=>{
   const focused=body.contains(document.activeElement)?document.activeElement.getAttribute('aria-label'):null;body.replaceChildren();
   body.append(el('p','',join?'Join node '+join.id+' - all predicates below share this type.':'Create join between these components.'),field('Join type',select('Join type',[['INNER','INNER'],['LEFT','LEFT OUTER'],['RIGHT','RIGHT OUTER'],['FULL','FULL OUTER']],draft.type==='CROSS'?'INNER':draft.type,v=>{draft.type=v;void analyze();})),el('p','qb-join-sides','Left: '+names(draft.left)+' | Right: '+names(draft.right)),el('p','','Preserves '+(draft.type==='LEFT'?'all rows from the left operand':draft.type==='RIGHT'?'all rows from the right operand':draft.type==='FULL'?'all rows from both operands':'matching rows only')),button('Swap sides',()=>{[draft.left,draft.right]=[draft.right,draft.left];for(const p of draft.pairs){[p.left,p.right]=[p.right,p.left];[p.leftCast,p.rightCast]=[p.rightCast,p.leftCast];if(!p.leftCast)delete p.leftCast;if(!p.rightCast)delete p.rightCast;p.op={'<':'>','>':'<','<=':'>=','>=':'<='}[p.op]??p.op;}void analyze();}));
   draft.pairs.forEach((p,i)=>{
    const assessment=assessments.find(a=>a.index===i),row=el('div','qb-join-pair'),group=el('fieldset','qb-join-types');group.append(el('legend','','Predicate '+(i+1)));
    const type=e=>this.model.sources.find(s=>s.id===e.source)?.columns.find(c=>c.name===e.name)?.type??'Unknown type';
    row.append(el('span','',label(p.left,this.model)+' ('+(assessment?.leftType??type(p.left))+')'),select('Comparison '+(i+1),['=','<>','<','<=','>','>='],p.op,v=>{p.op=v;delete p.typeAcknowledgment;void analyze();}),el('span','',label(p.right,this.model)+' ('+(assessment?.rightType??type(p.right))+')'),button('Remove predicate',()=>{draft.pairs.splice(i,1);void analyze();}));group.append(row);
    if(assessment){
     const message=el('p',assessment.resolved?'':'qb-invalid',assessment.message);message.setAttribute('role','status');group.append(message);
     const choices=assessment.conversions.filter(c=>c.available),hasCast=!!(p.leftCast||p.rightCast);let selected=p.typeAcknowledgment===assessment.signature?'unchanged':'';
     const options=[['',assessment.status==='compatible'?'No conversion needed':'Choose type handling'],...choices.map(c=>[c.side,c.label]),['unchanged','Keep comparison unchanged (accept warning)']];
     if(hasCast){const matching=choices.find(c=>p[c.side+'Cast']===c.castType&&!p[(c.side==='left'?'right':'left')+'Cast']);selected=matching?.side??'current';if(selected==='current')options.push(['current','Keep current conversion']);group.append(el('p','qb-join-conversion',[p.leftCast?'Left: CAST('+label(p.left,this.model)+' AS '+p.leftCast+')':'',p.rightCast?'Right: CAST('+label(p.right,this.model)+' AS '+p.rightCast+')':''].filter(Boolean).join(' | ')));}
     const control=select('Type handling '+(i+1),options,selected,value=>{if(value==='current')return;delete p.leftCast;delete p.rightCast;delete p.typeAcknowledgment;if(value==='unchanged')p.typeAcknowledgment=assessment.signature;else{const choice=choices.find(c=>c.side===value);if(choice)p[value+'Cast']=choice.castType;}void analyze();});control.disabled=pending;group.append(field('Type handling',control));
     for(const choice of assessment.conversions.filter(c=>!c.available))group.append(el('small','qb-join-unavailable','Convert '+choice.side+': '+choice.reason));
    }
    body.append(group);
   });
   if(pending)body.append(el('p','','Checking column types...'));if(error){const problem=el('p','qb-invalid',error);problem.setAttribute('role','alert');body.append(problem,button('Retry type check',()=>void analyze()));}
   if(join)body.append(button('Disconnect this join',()=>{this.edit(()=>disconnect(this.model,join));d.close();}));
   if(d){d.querySelector('footer button.primary').disabled=pending||!!error||!draft.pairs.length||assessments.length!==draft.pairs.length||assessments.some(a=>!a.resolved);if(focused)[...body.querySelectorAll('[aria-label]')].find(n=>n.getAttribute('aria-label')===focused)?.focus({preventScroll:true});}
  };
  d=dialog('Edit join',body,{anchor,save:async()=>{if(pending||error||assessments.some(a=>!a.resolved))throw Error(error||'Resolve each column type mismatch before applying the join.');if(this.revision!==baseRevision)throw Error('The canvas changed. Close and reopen this join.');const model=candidate();this.edit(()=>{this.model.roots=model.roots;});}});d.addEventListener('close',()=>sequence++);void analyze();
 }
 connectionDialog(from=null,anchor=null){if(!this.model.sources.length)return;const cols=this.model.sources.flatMap(s=>s.columns.map(c=>({value:s.id+'\u0000'+c.name,expr:column(s.id,c.name),text:s.alias+'.'+c.name+' / '+(c.type??'Unknown type')})));let left=from??cols[0]?.expr,right=cols.find(c=>c.expr.source!==left?.source)?.expr;const body=el('div');const choices=[['','Choose column'],...cols.map(c=>[c.value,c.text])];body.append(field('Left column',picker('Left column',choices,left?left.source+'\u0000'+left.name:'',v=>left=cols.find(c=>c.value===v)?.expr)),field('Right column',picker('Right column',choices,right?right.source+'\u0000'+right.name:'',v=>right=cols.find(c=>c.value===v)?.expr)));return dialog('Connect columns',body,{anchor,saveLabel:'Choose join',save:()=>{if(!left||!right||left.source===right.source)throw Error('Choose columns from different source instances.');setTimeout(()=>this.joinDrop(left,right,null),0);}});}
 crossDialog(source){let target=this.model.sources.find(s=>s.id!==source.id)?.id;const body=el('div');body.append(el('p','','CROSS JOIN combines every row from each operand.'),field('Join source',select('Cross join source',this.model.sources.filter(s=>s.id!==source.id).map(s=>[s.id,s.alias+' / '+s.name]),target,v=>target=v)));dialog('Cross join',body,{save:()=>{if(!target)throw Error('Add a second source.');if(sharedJoin(this.model,source.id,target))throw Error('These sources are already connected. Edit their existing join.');this.edit(()=>connect(this.model,{source:source.id},{source:target},'CROSS'));}});}
 async sourcePicker(){const body=el('div'),message=el('p'),objects=el('div'),schemaSelect=select('Schema',[],null,()=>{}),kindSelect=select('Object type',[['tables','Tables'],['views','Views'],['materialized_views','Materialized views']], 'tables',()=>{}),search=input('Search objects','',()=>{});let revision=0,offset=0;const load=async(more=false)=>{const current=++revision;if(!more){offset=0;objects.replaceChildren();}message.textContent='Reading objects...';try{const parent={kind:kindSelect.value,database:this.database,schema:schemaSelect.value};const page=await this.job('/metadata/tree',{connectionId:this.connectionId,...parent,offset});if(!d.open||current!==revision)return;message.textContent='';for(const descriptor of page.nodes){const item=button(descriptor.name,async()=>{try{await this.addSource({connectionId:this.connectionId,parent:{...parent,offset:page.offset??0},key:descriptor.key});d.close();}catch(e){message.textContent=e.message;}});item.dataset.search=descriptor.name.toLowerCase();objects.append(item);}if(page.nextOffset!==undefined){offset=page.nextOffset;objects.append(button('Load more objects',e=>{e.currentTarget.remove();void load(true);}));}filter();}catch(e){message.textContent=e.message;}};const filter=()=>{for(const item of objects.children)if(item.dataset.search)item.hidden=!item.dataset.search.includes(search.value.toLowerCase());};schemaSelect.onchange=kindSelect.onchange=()=>void load();search.oninput=filter;body.append(field('Search schemas',input('Search schemas','',value=>{for(const option of schemaSelect.options)option.hidden=!option.textContent.toLowerCase().includes(value.toLowerCase());})),field('Schema',schemaSelect),field('Object type',kindSelect),field('Search loaded objects',search),message,objects);const d=dialog('Add source',body,{cancel:'Close'});const loadSchemas=async(offset=0)=>{const page=await this.job('/metadata/tree',{connectionId:this.connectionId,kind:'schemas',database:this.database,offset});if(!d.open)return;for(const s of page.nodes){const o=el('option','',s.name);o.value=s.schema||s.name;schemaSelect.append(o);}if(page.nextOffset!==undefined){const more=button('Load more schemas',async()=>{more.disabled=true;try{await loadSchemas(page.nextOffset);more.remove();}catch(e){message.textContent=e.message;more.disabled=false;}});body.prepend(more);}};try{await loadSchemas();if(!schemaSelect.options.length){const o=el('option','','Default schema');o.value='';schemaSelect.append(o);}if([...schemaSelect.options].some(o=>o.value==='PUBLIC'))schemaSelect.value='PUBLIC';await load();}catch(e){message.textContent=e.message;}}

 mountGrid(){DataGridView.bindPreferences(this.result,this.connectionId);if(!this.resultHost)return;this.grid?.destroy();this.grid=new DataGridView(this.resultHost,this.result,{sourceSql:this.resultSql||this.sql,controller:this.controller,rowActions:!this.viewEditor,draftActions:this.viewEditor?{save:()=>this.viewEditor.save(),revert:()=>this.viewEditor.revert(),state:()=>({dirty:this.viewEditor.dirty,canSave:this.viewEditor.querySource!=='diagram'||this.compiledRevision===this.revision&&!this.compiled?.diagnostics?.some(d=>d.code==='join_type_resolution'),busy:this.loading||this.controller.busy||this.viewEditor.loading||this.viewEditor.unreconciled||this.viewEditor.committed})}:null,notice:message=>this.notice(message),transform:change=>this.gridAction(change),refresh:this.controller.refresh,structured:{render:host=>this.filterControls(host),settings:()=>this.sortDialog(),customFilter:(column,operator)=>this.customGridFilter(column,operator)}});this.resultHost.classList.add('qb-grid');
  // Keep status outside the inert grid so query cancellation remains available.
  const actions=this.grid.interactive.querySelector('.data-grid-footer');actions.className='qb-grid-actions';actions.removeAttribute('role');actions.removeAttribute('aria-label');this.gridActions=actions;
  const footer=el('div','data-grid-footer qb-grid-footer');footer.setAttribute('role','toolbar');footer.setAttribute('aria-label','Query results');const info=el('div','qb-grid-info');info.append(this.dataStatus,this.staleData);footer.append(actions,info);this.grid.view.append(footer);
 }
 filterControls(host){host.classList.add('qb-grid-filters');for(const [key,title]of [['where','Rows'],['having','Groups']]){const expression=key==='where'?this.model.where:this.model.summary.having;const group=el('div','qb-filter-control');const edit=button(title+(expression?': '+label(expression,this.model):': no filters'),()=>this.filterEditor(key));edit.disabled=key==='having'&&this.model.mode!=='summary';edit.title=expression?dependencies(expression,this.model).join('\n')||label(expression,this.model):'Edit '+title.toLowerCase()+' filters';edit.classList.toggle('qb-invalid',expression&&dependencies(expression,this.model).length>0);group.append(edit);if(expression){group.append(button('Remove '+title.toLowerCase()+' filters',()=>{this.edit(()=>{if(key==='where')this.model.where=null;else this.model.summary.having=null;DataGridView.setValueFilters(this.result);this.valuePredicates=new Map();});void this.run('data',false);}));}host.append(group);}host.append(button('Sorting ('+active(this.model).order.length+')',()=>this.sortDialog()));}
 filterEditor(key,initial=null){const value=initial??(key==='where'?this.model.where:this.model.summary.having)??{kind:'logical',op:'AND',args:[{kind:'binary',op:'=',left:{kind:'column',source:'',name:''},right:{kind:'literal',type:'text',value:''}}]};editExpression(this,key==='where'?'Rows filters':'Groups filters',value,async expression=>{this.edit(()=>{if(key==='where')this.model.where=expression;else this.model.summary.having=expression;});await this.run('data',false);},{allowAggregate:key==='having'});}
 sortDialog(){let rules=copy(active(this.model).order);const host=el('div');const render=()=>{host.replaceChildren();rules.forEach((r,index)=>{const row=el('div','qb-sort-rule');row.append(el('span','',String(index+1)),button(label(r.expression,this.model),()=>editExpression(this,'Sort expression',r.expression,e=>{r.expression=e;render();},{allowAggregate:this.model.mode==='summary'})),select('Sort direction '+(index+1),['ASC','DESC'],r.direction,v=>r.direction=v),button('Move up',()=>{if(index){[rules[index-1],rules[index]]=[rules[index],rules[index-1]];render();}}),button('Remove sorting',()=>{rules.splice(index,1);render();}));const errors=dependencies(r.expression,this.model);if(errors.length)row.append(el('span','qb-invalid',errors.join('; ')));host.append(row);});host.append(button('Add sorting rule',()=>editExpression(this,'Sort expression',{kind:'output',output:active(this.model).outputs[0]?.id??''},e=>{rules.push({expression:e,direction:'ASC'});render();},{allowAggregate:this.model.mode==='summary'})));};render();dialog('Ordered sorting rules',host,{saveLabel:'Apply and run',save:async()=>{this.edit(()=>active(this.model).order=rules);await this.run('data',false);}});}
 gridOutput(index){const o=this.result.columns?.[index];if(!o?.outputId)throw Error('Run this query to establish output references for these columns.');return {kind:'output',output:o.outputId};}
 customGridFilter(col,operator){const expression=this.gridOutput(col.source),out=active(this.model).outputs.find(o=>o.id===expression.output),key=out&&aggregate(out.expression)?'having':'where';this.filterEditor(key,{kind:'binary',op:operator,left:expression,right:{kind:'literal',type:'text',value:''}});}
 async gridAction(change){if(this.controller.busy)return;if(change.action==='filter_values')return this.applyGridValues(change);if(['save_rows','review_rows','page','export','reconcile','count'].includes(change.action))return this.controller.execute(change);if(!await this.guardRows())return;this.edit(()=>{const a=active(this.model);if(['clear_all','clear_filters'].includes(change.action)){this.model.where=null;this.model.summary.having=null;DataGridView.setValueFilters(this.result);this.valuePredicates=new Map();}if(['clear_all','clear_order'].includes(change.action))a.order=[];if(change.action==='order'){const expression=this.gridOutput(change.columnIndex);const existing=a.order.find(s=>same(s.expression,expression));if(existing)existing.direction=change.direction;else a.order.push({expression,direction:change.direction});}if(change.action==='filter'){const expression=this.gridOutput(change.columnIndex),out=a.outputs.find(o=>o.id===expression.output);let predicate;if(change.operator.includes('NULL'))predicate={kind:'null',arg:expression,not:change.operator.includes('NOT')};else{const numeric=[-6,5,4,-5,2,3,6,7,8].includes(change.jdbcType),bool=[-7,16].includes(change.jdbcType),value=change.value===null?null:numeric?String(change.value):bool?change.value===true||change.value==='true':change.value;predicate={kind:'binary',op:change.operator,left:expression,right:{kind:'literal',type:numeric?'number':bool?'boolean':'text',value}};}const key=out&&aggregate(out.expression)?'having':'where',target=key==='having'?this.model.summary:this.model,previous=target[key];target[key]=previous?{kind:'logical',op:'AND',args:[previous,predicate]}:predicate;}});await this.run('data',false);}
 async applyGridValues(change){
  if(!await this.guardRows())return false;
  if(!Array.isArray(change.values)||change.values.length>128)throw Error('Select at most 128 values.');
  const expression=this.gridOutput(change.columnIndex),output=active(this.model).outputs.find(o=>o.id===expression.output),key=output&&aggregate(output.expression)?'having':'where';
  const previousWhere=this.model.where,previousHaving=this.model.summary.having,previousModel=copy(this.model),previousHistory=[...this.history],previousFuture=[...this.future],previousPredicates=new Map(this.valuePredicates??[]),target=key==='having'?this.model.summary:this.model;
  const remove=(node,predicate)=>{if(!node)return null;if(node===predicate)return null;if(node.kind==='logical'&&node.op==='AND'){const args=node.args.map(child=>remove(child,predicate)).filter(Boolean);return args.length>1?{...node,args}:args[0]??null;}return node;};
  const previous=previousPredicates.get(expression.output);let where=target[key];
  if(!change.values.length&&!previous)throw Error('There is no value filter to clear for this column.');
  if(previous&&previous.key===key)where=remove(where,previous.predicate);
  const type=[-6,5,4,-5].includes(change.jdbcType)?'integer':[2,3,6,7,8].includes(change.jdbcType)?'number':[-7,16].includes(change.jdbcType)?'boolean':({91:'date',92:'time',93:'timestamp'}[change.jdbcType]??'text');
  const args=change.values.filter(value=>value!==null).map(value=>({kind:'literal',type,value:type==='boolean'?['true','1'].includes(String(value).toLowerCase()):String(value)}));
  let predicate=args.length?{kind:'in',arg:expression,args,not:false}:null;
  if(change.values.includes(null)){const nil={kind:'null',arg:expression,not:false};predicate=predicate?{kind:'logical',op:'OR',args:[predicate,nil]}:nil;}
  try{
   this.edit(()=>{target[key]=predicate?(where?{kind:'logical',op:'AND',args:[where,predicate]}:predicate):where;});
   this.operation='data';this.selectTab('data');await this.controller.execute({action:'builder',prompt:false});
   if(this.resultRevision!==this.revision)throw Error('The filter was not applied. Previous results are retained.');
   this.valuePredicates=new Map(previousPredicates);if(predicate)this.valuePredicates.set(expression.output,{key,predicate});else this.valuePredicates.delete(expression.output);return true;
  }catch(error){
   this.model=previousModel;this.model.where=previousWhere;this.model.summary.having=previousHaving;this.history=previousHistory;this.future=previousFuture;this.valuePredicates=previousPredicates;this.revision++;this.refreshCanvas();this.scheduleCompile();this.changed(this);throw error;
  }
 }
 async run(tab='data',prompt=true){this.selectTab(tab);if(this.controller.busy||this.readOnly||this.viewEditor?.loading||this.viewEditor?.unreconciled||this.viewEditor?.committed)return;this.operation=tab;this.messages[tab]='Preparing query...';try{await this.controller.execute({action:tab==='plan'?'explain':'builder',prompt});}catch(e){this.messages[tab]=e.message;this.executionState();} }
 async execute(change,execution){if(!['save_rows','review_rows','reconcile','count'].includes(change.action)&&!await DataGridView.guard(this.result,()=>this.ownedGrid({action:'save_rows'},execution)))return;if(['save_rows','review_rows','page','export','reconcile','count'].includes(change.action))return this.ownedGrid(change,execution);const op=change.action==='explain'?'plan':'data';if(change.action==='refresh'){this.operation='data';if(!change.automatic)this.selectTab('data');}this.messages[op]='Compiling current query...';this.executionState();try{const query=await this.currentQuery();execution.check();const revision=this.revision;this.messages[op]=query.bindings?.length?'Collecting parameter values...':'Submitting query...';this.executionState();const values=await parameterValues(this,query.bindings??[],change.prompt===true);execution.check();if(this.revision!==revision)throw Error('The query changed during preparation. Run the current query again.');if(JSON.stringify(values)!==JSON.stringify(this.values)){this.values=copy(values);this.parameterRevision++;}this.valueTypes=Object.fromEntries((query.bindings??[]).map(p=>[p.id,p.type]));const parameterRevision=this.parameterRevision;const parameters=(query.bindings??[]).map(p=>queryParameter(this,p,values[p.id]));this.messages[op]=op==='plan'?'Collecting estimated plan...':'Fetching rows...';this.executionState();const body={connectionId:this.connectionId,database:this.database,sql:query.sql,parameters,...(op==='data'?{rowLimit:pagePreference(this.result,this.connectionId)}:{})};const response=await execution.submit(body,op==='plan'?'/query/explain':'/query/execute');execution.check();if(this.disposed||revision!==this.revision||parameterRevision!==this.parameterRevision){this.messages[op]='Query changed while the operation was in progress. Previous successful results are retained.';return;}
   if(op==='plan'){const bytes=this.retainedBytes(this.result,response);this.account(bytes);this.plan=response;this.planRevision=revision;this.planParameterRevision=parameterRevision;this.messages.plan='Estimated plan ready.';this.renderPlan();}
   else{const rows=response.results?.filter(r=>r.kind==='rows');if(rows?.length!==1)throw Error('The builder requires one SELECT result set.');const next=rows[0];next.columns=next.columns.map((c,i)=>({...c,outputId:query.outputs?.[i]?.id}));this.account(this.retainedBytes(next,this.plan));await releaseGrid(this.api,this.result);DataGridView.replacePage(this.result,next);DataGridView.clearSelection(this.result);this.resultSql=next.sourceSql??query.sql;this.resultRevision=revision;this.resultParameterRevision=parameterRevision;this.messages.data=(next.rowCount??next.rows.length)+' rows'+(next.truncated?' (truncated at the row or byte limit)':'');this.grid?.updateData(this.sql);}
  }catch(e){this.messages[op]=e instanceof GridQueryCancelled?'Cancelled. Previous successful results are retained.':e.message;throw e;}finally{this.updateStatus();this.executionState();}}
 retainedBytes(data,plan){return new TextEncoder().encode(JSON.stringify({data,plan})).length*3;}
 cancel(){this.valueDialog?.close();void this.controller.cancel();}
 executionState(){if(!this.root)return;const busy=this.controller.busy;for(const [key,host]of [['data',this.dataStatus],['plan',this.planStatus]])if(host){host.replaceChildren(el('span','',this.messages[key]??''));if(busy&&this.operation===key){const progress=el('progress');progress.removeAttribute('value');progress.setAttribute('aria-label',key==='plan'?'Explain in progress':'Query in progress');const cancel=button(this.controller.state==='cancelling'?'Cancelling...':'Cancel',()=>this.cancel());cancel.disabled=this.controller.state==='cancelling';host.append(progress,el('span','',this.controller.elapsed+'s'),cancel);}}if(this.grid?.interactive)this.grid.interactive.inert=busy&&!this.controller.scrolling;if(this.gridActions)this.gridActions.inert=busy;if(this.runButton)this.runButton.disabled=busy||this.loading||this.viewEditor?.loading||this.viewEditor?.unreconciled||this.viewEditor?.committed||this.readOnly||this.mode==='preserved'||this.compiledRevision!==this.revision||!this.compiled?.valid;if(this.explainButton)this.explainButton.disabled=this.runButton.disabled;this.syncViewActions();}
 updateStatus(){this.updateOutputAliases();if(!this.root)return;const current=this.compiledRevision===this.revision;const diagnostics=current?this.compiled?.diagnostics?.map(d=>d.message).join(' '):'Updating SQL preview...';if(this.status)this.status.textContent=this.readOnly?this.message:this.mode==='preserved'?this.message:diagnostics||this.message||'Query ready. Canvas changes update the SQL preview; Run fetches rows.';if(this.grid){this.grid.updateData(this.sql||'-- '+(diagnostics||'Complete the query on the canvas.'));this.grid.structured?.host?.replaceChildren();if(this.grid.structured?.host)this.filterControls(this.grid.structured.host);}for(const [text,disabled]of [['Undo',!this.history.length],['Redo',!this.future.length]]){const b=this.root.querySelector('[aria-label="'+text+'"]');if(b)b.disabled=disabled||this.readOnly;}
  for(const name of ['Save query','Save query as','Copy SQL']){const control=this.root.querySelector('[aria-label="'+name+'"]');if(control)control.disabled=this.readOnly||this.mode==='visual'&&(!current||!this.compiled?.valid);}
  if(this.staleData){this.staleData.replaceChildren();if(this.resultSql){const stale=this.resultRevision!==this.revision||this.resultParameterRevision!==this.parameterRevision;this.staleData.append(el('span','',stale?'Rows belong to the previous execution.':'Rows match the current query.'),button('Executed SQL',()=>{const pre=el('pre','',this.resultSql);dialog('SQL for displayed rows',pre,{cancel:'Close'});}));}}
  if(this.stalePlan){this.stalePlan.textContent=this.plan&&(this.planRevision!==this.revision||this.planParameterRevision!==this.parameterRevision)?'This plan is outdated. Explain again to update it.':'';}this.executionState();
 }
 renderPlan(){if(!this.planHost)return;this.planHost.replaceChildren();if(!this.plan){this.planHost.append(el('p','muted','Estimated plan results will appear here.'));return;}const plan=this.plan;this.planHost.append(el('h3','',plan.engine+' - estimated plan'),el('p','',plan.costLabel));const tree=(nodes,host)=>{for(const node of nodes){const details=el('details','qb-plan-node');details.open=true;details.append(el('summary','',node.operator));const table=el('table');for(const [name,value]of Object.entries(node.properties??{})){const row=el('tr');row.append(el('th','',name),el('td','',typeof value==='object'?JSON.stringify(value):String(value)));table.append(row);}details.append(table);tree(node.children??[],details);host.append(details);}};tree(plan.nodes??[],this.planHost);if(!plan.nodes?.length&&plan.raw?.columns?.length>1){const table=el('table','qb-plan-table'),header=el('tr');plan.raw.columns.forEach(c=>header.append(el('th','',c)));table.append(header);for(const values of plan.raw.rows??[]){const row=el('tr');values.forEach(v=>row.append(el('td','',v??'NULL')));table.append(row);}this.planHost.append(table);}for(const note of plan.observations??[])this.planHost.append(el('p','',note));const raw=el('details','qb-plan-raw');raw.open=!plan.nodes?.length;raw.append(el('summary','','Raw output'),el('pre','',plan.rawText??JSON.stringify(plan.raw,null,2)));this.planHost.append(raw);}
 importDialog(){const body=el('div'),text=el('textarea');text.setAttribute('aria-label','SQL to import');text.maxLength=MAX_SQL;text.wrap='off';body.append(el('p','','Import one SELECT. Queries outside the visual model remain exact for inspection and Open in Script.'),text);this.importModal=dialog('Import SQL',body,{saveLabel:'Import query',save:()=>this.importSql(text.value)});}
  async openFile(){if(this.dirty&&!confirm('Discard unsaved query changes and open a file?'))return;const load=async(file,handle)=>{if(file.size>MAX_SQL)throw Error('Query files are limited to 16 KiB');await this.importSql(await file.text());this.fileHandle=handle;this.fileName=file.name;if(!this.viewEditor)this.saved=JSON.stringify(this.model);this.changed(this);};if(window.showOpenFilePicker){try{const [handle]=await window.showOpenFilePicker({types:[{description:'SQL query',accept:{'text/plain':['.sql','.txt']}}]});await load(await handle.getFile(),handle);}catch(e){if(e.name!=='AbortError')throw e;}}else{const input=el('input');input.type='file';input.accept='.sql,.txt';input.onchange=()=>{if(input.files[0])void load(input.files[0],null).catch(e=>this.notice(e.message));};input.click();}}
  async saveFile(asNew=false){const contents=this.mode==='preserved'?this.originalSql:(await this.currentQuery()).sql;let handle=asNew?null:this.fileHandle;try{if(!handle&&window.showSaveFilePicker)handle=await window.showSaveFilePicker({suggestedName:this.fileName||'query.sql',types:[{description:'SQL query',accept:{'text/plain':['.sql']}}]});if(handle){const writable=await handle.createWritable();await writable.write(contents);await writable.close();this.fileHandle=handle;this.fileName=handle.name;}else{const url=URL.createObjectURL(new Blob([contents],{type:'application/sql'}));const link=el('a');link.href=url;link.download=this.fileName||'query.sql';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(!this.viewEditor)this.saved=JSON.stringify(this.model);this.changed(this);this.notice('SQL query saved. No database object was changed.');}catch(error){if(error.name!=='AbortError')throw error;}}
}
