import {lucide} from './tree-icons.js';
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const button=(label,run)=>{const n=el('button',label);n.type='button';n.onclick=run;return n;};
const field=(label,input)=>{const n=el('label');n.append(el('span',label),input);return n;};
const stamp=value=>value?new Date(value).toLocaleString():'';
export function installRelationalAdministration({api,profiles,notify}){
  const launch=button('PostgreSQL / MySQL Administration',open);launch.id='relational-administration';launch.setAttribute('role','menuitem');launch.prepend(lucide('database'));document.getElementById('workspace-settings-menu').append(launch);
  const dialog=el('dialog',undefined,'oracle-admin');dialog.id='relational-admin-dialog';dialog.setAttribute('aria-labelledby','relational-admin-title');const title=el('h2','PostgreSQL / MySQL Administration');title.id='relational-admin-title';
  const connection=el('select');connection.setAttribute('aria-label','Administration connection');const database=el('input');database.setAttribute('aria-label','Administration database');database.placeholder='Connection default';database.maxLength=128;
  const connectButton=button('Connect',()=>act(connect)),close=button('Close',requestClose),cancel=button('Cancel operation',cancelJob);const header=el('header');header.append(title,field('Connection',connection),field('Database',database),connectButton,close);
  const target=el('p','Choose a connection.','oracle-admin-target'),status=el('p','','oracle-admin-status'),error=el('p','','oracle-admin-error');status.setAttribute('role','status');error.setAttribute('role','alert');const nav=el('nav');nav.setAttribute('aria-label','Administration categories');
  const heading=el('h3','Catalog'),refresh=button('Refresh',()=>act(()=>read(0))),previous=button('Previous page',()=>act(()=>read(Math.max(0,offset-pageSize)))),next=button('Next page',()=>act(()=>read(offset+pageSize)));const tools=el('div',undefined,'oracle-admin-tools');tools.append(heading,refresh,previous,next);
  const catalog=el('div',undefined,'oracle-admin-catalog');catalog.tabIndex=0;catalog.setAttribute('role','region');catalog.setAttribute('aria-label','Database administration catalog');const actions=el('select');actions.setAttribute('aria-label','Administration action');const form=el('form',undefined,'oracle-admin-fields'),reviewButton=button('Review operation',()=>act(prepare));const operation=el('section',undefined,'oracle-admin-operation');operation.append(el('h3','Reviewed operation'),field('Action',actions),form,reviewButton);
  const review=el('section',undefined,'oracle-admin-review'),sql=el('textarea');sql.readOnly=true;sql.wrap='off';sql.setAttribute('aria-label','Reviewed administration SQL');const notice=el('p'),ack=el('input');ack.type='checkbox';const password=el('input');password.type='password';password.autocomplete='new-password';password.setAttribute('aria-label','New account password');const passwordField=field('Password (sent only on Apply)',password),apply=button('Apply reviewed operation',()=>act(applyPlan));review.append(el('h3','Review SQL and target'),notice,sql,passwordField,field('I reviewed the target and operation.',ack),apply);
  const backup=el('section',undefined,'oracle-admin-rman'),backupForm=el('form',undefined,'oracle-admin-fields'),backupScript=el('textarea');backupScript.readOnly=true;backupScript.wrap='off';backupScript.setAttribute('aria-label','Manual backup restore script');
  for(const [name,label,value]of [['mode','Mode (backup or restore)','backup'],['tool','Absolute native tool path','/usr/bin/pg_dump'],['file','Absolute backup file path','/srv/backups/database.dump'],['toolMajor','Confirmed native client major version',''],['tls','TLS (verify, require, disable)','verify'],['ca','CA certificate path (optional)','']]){const input=el('input');input.name=name;input.value=value;input.maxLength=1024;input.setAttribute('aria-label',label);backupForm.append(field(label,input));}
  let backupArtifact=null;const generateBackup=button('Generate manual script',()=>act(async()=>{const input={...selected};for(const control of backupForm.elements)input[control.name]=control.name==='toolMajor'?Number(control.value):control.value;backupArtifact=await job('/relational/backup/script',input);backupScript.value=backupArtifact.script;backupNotice.textContent=backupArtifact.notice;})),copyBackup=button('Copy complete script',()=>act(async()=>{if(!backupArtifact)throw Error('Generate a script first.');await navigator.clipboard.writeText(backupArtifact.script);notify('Complete script copied.');})),saveBackup=button('Save script',()=>{if(!backupArtifact)return;const url=URL.createObjectURL(new Blob([backupArtifact.script],{type:'text/plain;charset=utf-8'}));const link=el('a');link.href=url;link.download=backupArtifact.fileName;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}),backupNotice=el('p','Manual logical backup/restore commands. Nothing is executed by this workspace.');backup.append(el('h3','Native backup / restore scripts'),backupNotice,backupForm,generateBackup,backupScript,copyBackup,saveBackup);backup.hidden=true;
  const last=el('details',undefined,'oracle-admin-last'),lastTitle=el('summary','Last operation'),lastText=el('pre');last.append(lastTitle,lastText);const main=el('main');main.append(tools,catalog,operation,review,backup,last);const layout=el('div',undefined,'oracle-admin-layout');layout.append(nav,main);const footer=el('footer');footer.append(status,cancel);dialog.append(header,target,error,layout,footer);document.body.append(dialog);
  let selected=null,capabilities=null,category='',offset=0,pageSize=100,hasMore=false,busy=false,closing=false,currentJob=null,reviewJob=null,plan=null,selectedRow=null;
  function update(){dialog.setAttribute('aria-busy',String(busy));for(const n of dialog.querySelectorAll('input,select,button'))n.disabled=busy;close.disabled=false;cancel.disabled=!busy||!currentJob;connectButton.disabled=busy||!connection.value;refresh.disabled=busy||!capabilities;previous.disabled=busy||!capabilities||offset===0;next.disabled=busy||!capabilities||!hasMore;reviewButton.disabled=busy||!capabilities||!actions.value;review.hidden=!plan;apply.disabled=busy||!plan||!ack.checked||(plan.requiresPassword&&!password.value);operation.hidden=category==='backup'||!actions.options.length;generateBackup.disabled=busy||!capabilities;copyBackup.disabled=saveBackup.disabled=busy||!backupArtifact;}
  async function releaseReview(){const id=reviewJob;reviewJob=null;plan=null;ack.checked=false;password.value='';update();if(id)await api('/jobs/'+id,'DELETE').catch(()=>{});}
  async function cancelJob(){if(currentJob){status.textContent='Cancellation requested; waiting for the database.';await api('/jobs/'+currentJob+'/cancel','POST',{}).catch(e=>{error.textContent=e.message;});}}
  async function requestClose(){closing=true;backupArtifact=null;backupScript.value='';if(busy){await cancelJob();return;}await releaseReview();dialog.close();}
  async function act(run){if(busy)return;busy=true;error.textContent='';update();try{await run();}catch(e){if(!closing)error.textContent=e.message;}finally{busy=false;update();if(closing)await requestClose();}}
  async function job(path,body,{retain=false,mutation=false}={}){const submitted=await api(path,'POST',body);currentJob=submitted.id;update();let retained=false;try{for(;;){if(closing)await cancelJob();const state=await api('/jobs/'+submitted.id);status.textContent=(state.progress||state.state)+(state.started?' | Started '+stamp(state.started)+' | '+Math.floor(((state.finished||Date.now())-state.started)/1000)+'s elapsed':'');if(state.finished){if(mutation){last.hidden=false;last.open=true;lastTitle.textContent='Last operation: '+(state.result?.status||state.state);lastText.textContent=['Status: '+(state.result?.status||state.state),'Outcome: '+(state.result?.outcome||state.outcome||state.state),'Started: '+stamp(state.started),'Finished: '+stamp(state.finished),state.result?.message||state.error||'',JSON.stringify(state.result?.results??[],null,2)].join('\n');}if(state.state!=='complete')throw Error(state.error||state.state);if(retain){reviewJob=submitted.id;retained=true;}return state.result;}await new Promise(resolve=>setTimeout(resolve,300));}}finally{currentJob=null;if(!retained){await api('/jobs/'+submitted.id+'/cancel','POST',{}).catch(()=>{});await api('/jobs/'+submitted.id,'DELETE').catch(()=>{});}update();}}
  async function open(){if(busy)return;closing=false;backupArtifact=null;backupScript.value='';backup.hidden=true;tools.hidden=catalog.hidden=false;last.hidden=true;lastText.textContent='';await releaseReview();connection.replaceChildren();for(const profile of profiles().filter(p=>['postgresql','mysql','mariadb'].includes(p.templateId))){const option=el('option',profile.name);option.value=profile.id;connection.append(option);}selected=null;capabilities=null;category='';nav.replaceChildren();catalog.replaceChildren();form.replaceChildren();actions.replaceChildren();error.textContent='';status.textContent='';target.textContent=connection.options.length?'Connect to inspect the resolved target.':'Add a PostgreSQL, MySQL or MariaDB connection to use Administration.';update();dialog.showModal();}
  async function connect(){await releaseReview();selected={connectionId:connection.value,database:database.value};capabilities=await job('/relational/admin/read',{...selected,category:'overview'});selected.database=capabilities.target.database;database.value=selected.database;target.textContent=[capabilities.target.engine,capabilities.target.version,'Database '+selected.database,'User '+capabilities.target.identity.principal,capabilities.scopeNotice].join(' | ');nav.replaceChildren();for(const item of capabilities.categories){const b=button(item.label,()=>act(async()=>{await releaseReview();category=item.id;backup.hidden=true;tools.hidden=catalog.hidden=false;selectedRow=null;renderActions();await read(0);}));b.dataset.category=item.id;nav.append(b);}const backupTab=button('Backup / restore scripts',()=>act(async()=>{await releaseReview();category='backup';tools.hidden=catalog.hidden=operation.hidden=true;backup.hidden=false;for(const n of nav.querySelectorAll('button'))n.setAttribute('aria-current',String(n===backupTab));}));nav.append(backupTab);backupForm.elements.toolMajor.value=capabilities.target.major;backupForm.elements.mode.value='backup';backupForm.elements.tool.value='/usr/bin/'+(capabilities.target.engine==='postgresql'?'pg_dump':capabilities.target.engine==='mysql'?'mysqldump':'mariadb-dump');backup.hidden=true;tools.hidden=catalog.hidden=false;category=capabilities.categories[0].id;renderActions();await read(0);}
  async function read(start){await releaseReview();const result=await job('/relational/admin/read',{...selected,category,offset:start});offset=result.offset;pageSize=result.pageSize;hasMore=result.hasMore;selectedRow=null;heading.textContent=result.label;catalog.replaceChildren();for(const b of nav.querySelectorAll('button'))b.setAttribute('aria-current',String(b.dataset.category===category));if(!result.available){catalog.append(el('p',result.message,'oracle-admin-error'));return;}if(!result.rows.length){catalog.append(el('p','No visible rows.'));renderFields();return;}const keys=Object.keys(result.rows[0]),table=el('table'),head=el('thead'),labels=el('tr');for(const key of keys)labels.append(el('th',key.replaceAll('_',' ')));head.append(labels);const body=el('tbody');for(const row of result.rows){const tr=el('tr');tr.tabIndex=0;for(const key of keys)tr.append(el('td',row[key]??''));const select=()=>{selectedRow=row;for(const r of body.children)r.setAttribute('aria-selected',String(r===tr));releaseReview();renderFields();};tr.onclick=select;tr.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}};body.append(tr);}table.append(head,body);catalog.append(table);renderFields();}
  function renderActions(){actions.replaceChildren();for(const action of capabilities.actions.filter(a=>a.category===category)){const option=el('option',action.label);option.value=action.id;actions.append(option);}renderFields();}
  function renderFields(){form.replaceChildren();const action=capabilities?.actions.find(a=>a.id===actions.value);if(!action){update();return;}const row=selectedRow??{},values={name:row.rolname??row.user??row.extname,host:row.host,role:row.role,roleHost:row.role_host,schema:row.schemaname??row.table_schema??row.nspname??row.schema_name??row.event_schema,object:row.relname??row.table_name??row.event_name,pid:row.pid};for(const spec of action.fields){const input=el('input');input.name=spec.key;input.value=values[spec.key]??spec.value??'';input.maxLength=128;input.autocomplete='off';input.setAttribute('aria-label',spec.label);form.append(field(spec.label,input));}update();}
  async function prepare(){await releaseReview();const input={...selected,action:actions.value};for(const control of form.elements)input[control.name]=control.value;plan=await job('/relational/admin/prepare',input,{retain:true});sql.value=plan.sql;notice.textContent=plan.label+' | '+plan.target.database+' | '+plan.warning;passwordField.hidden=!plan.requiresPassword;ack.checked=false;update();review.scrollIntoView({block:'nearest'});}
  async function applyPlan(){const result=await job('/relational/admin/apply',{planId:reviewJob,confirmed:ack.checked,...(plan.requiresPassword?{password:password.value}:{})},{mutation:true});await releaseReview();if(result.status!=='success')throw Error(result.message);notify(result.message);await read(offset);}
  function invalidate(){backupArtifact=null;backupScript.value='';backup.hidden=true;selected=null;capabilities=null;nav.replaceChildren();catalog.replaceChildren();actions.replaceChildren();form.replaceChildren();target.textContent='Connect to inspect the selected target.';releaseReview();}
  backupForm.oninput=e=>{backupArtifact=null;backupScript.value='';if(e.target.name==='mode'&&capabilities){const pg=capabilities.target.engine==='postgresql',maria=capabilities.target.engine==='mariadb',restore=e.target.value==='restore';backupForm.elements.tool.value='/usr/bin/'+(pg?(restore?'pg_restore':'pg_dump'):maria?(restore?'mariadb':'mariadb-dump'):(restore?'mysql':'mysqldump'));}update();};backupForm.onsubmit=e=>{e.preventDefault();generateBackup.click();};connection.onchange=invalidate;database.oninput=invalidate;actions.onchange=()=>{releaseReview();renderFields();};form.oninput=()=>releaseReview();form.onsubmit=e=>{e.preventDefault();act(prepare);};ack.onchange=update;password.oninput=update;dialog.addEventListener('cancel',e=>{e.preventDefault();requestClose();});dialog.addEventListener('close',()=>document.getElementById('workspace-settings').focus());update();
}
