import {lucide} from './tree-icons.js';
const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
const button=(label,icon,action)=>{const n=el('button');n.type='button';n.className='designer-button';n.setAttribute('aria-label',label);n.append(lucide(icon),document.createTextNode(label));n.onclick=action;return n;};
const field=(host,label,input)=>{const row=el('label',label);input.setAttribute('aria-label',label);row.append(input);host.append(row);return input;};
export const quoteIdentifier=(name,quote='"')=>quote+name.replaceAll(quote,quote+quote)+quote;

/** Ordered selections retain exact identifiers; position determines composite-key order. */
export function columnSelection(host,{columns,foreign=false,changed=()=>{},initial=[]}){
  const root=el('section');root.className='schema-columns';host.append(root);
  let choices=columns,remote=[],rows=initial.map(name=>({name,reference:''}));
  const list=el('div'),add=button(foreign?'Add column pair':'Add key column','plus',()=>{rows.push({name:'',reference:''});render((foreign?'Local column ':'Key column ')+rows.length);changed();});
  root.append(el('p',foreign?'Pair each local column with a referenced column. Pair order defines the composite foreign key.':'Select columns in key order. Use Move up / Move down to change the order.'),list,add);
  const select=(label,values,value,used,change)=>{const s=el('select');s.setAttribute('aria-label',label);s.append(new Option('Choose a column',''));for(const c of values){const o=new Option(c.name+(c.type?' ('+c.type+')':''),c.name);o.disabled=used.has(c.name)&&c.name!==value;s.append(o);}s.value=value;s.onchange=()=>{change(s.value);render(label);changed();};return s;};
  function render(focusLabel){list.replaceChildren();rows.forEach((row,i)=>{const line=el('div');line.className='schema-column-pair';line.append(el('span',String(i+1)),select((foreign?'Local column ':'Key column ')+(i+1),choices,row.name,new Set(rows.map(r=>r.name)),v=>row.name=v));if(foreign)line.append(el('span','references'),select('Referenced column '+(i+1),remote,row.reference,new Set(rows.map(r=>r.reference)),v=>row.reference=v));
    const up=button('Move column '+(i+1)+' up','chevron-up',()=>{[rows[i-1],rows[i]]=[rows[i],rows[i-1]];render((foreign?'Local column ':'Key column ')+i);changed();}),down=button('Move column '+(i+1)+' down','chevron-down',()=>{[rows[i+1],rows[i]]=[rows[i],rows[i+1]];render((foreign?'Local column ':'Key column ')+(i+2));changed();});up.disabled=i===0;down.disabled=i===rows.length-1;line.append(up,down,button('Remove column '+(i+1),'trash-2',()=>{rows.splice(i,1);render((foreign?'Local column ':'Key column ')+Math.min(i+1,rows.length));changed();}));list.append(line);});add.disabled=rows.length>=Math.min(32,choices.length);if(focusLabel)([...list.querySelectorAll('select')].find(n=>n.getAttribute('aria-label')===focusLabel)??add).focus();}
  render();return{root,get value(){return rows.map(r=>r.name);},get references(){return rows.map(r=>r.reference);},setColumns(value){choices=value;rows=[];render();changed();},setReferences(value){remote=value;rows.forEach(r=>r.reference='');render();changed();},validate(allowEmpty=false){if(!rows.length&&!allowEmpty)throw Error('Select at least one column.');if(rows.some(r=>!choices.some(c=>c.name===r.name)||foreign&&!remote.some(c=>c.name===r.reference)))throw Error(foreign?'Select both columns in every pair.':'Select a column in every row.');}};
}

/** Metadata jobs belong to this dialog, including requests which return after Close. */
export function metadataScope(api){const ids=new Set();let closed=false;return{get closed(){return closed;},close(){closed=true;for(const id of ids)api('/jobs/'+id+'/cancel','POST',{}).catch(()=>{});},async job(path,body){if(closed)throw Error('Picker closed');const start=await api(path,'POST',body);ids.add(start.id);try{for(;;){if(closed){await api('/jobs/'+start.id+'/cancel','POST',{}).catch(()=>{});throw Error('Picker closed');}const state=await api('/jobs/'+start.id);if(state.finished){if(state.state!=='complete')throw Error(state.error||state.state);return state.result;}await new Promise(r=>setTimeout(r,200));}}finally{ids.delete(start.id);await api('/jobs/'+start.id,'DELETE').catch(()=>{});}}};}

/** Paged metadata choices stay bound to the editor's connection and database. */
export function relationSelection(host,{scope,connectionId,database,schema,engine,materialized=false,changed}){
  const root=el('section');root.className='schema-relations';host.append(root);let revision=0,source=null;
  const status=el('p');status.setAttribute('role','status');
  function catalog(label,onchange){const wrap=el('div'),search=field(wrap,'Filter loaded '+label.toLowerCase(),el('input')),select=field(wrap,label,el('select'));search.type='search';let items=[],next;
    const more=button('Load more '+label.toLowerCase(),'plus',()=>void load(true));more.hidden=true;
    const retry=button('Retry '+label.toLowerCase(),'refresh-cw',()=>void load(false));retry.hidden=true;wrap.append(more,retry);root.append(wrap);
    function draw(){const selected=select.value;select.replaceChildren(new Option('Choose '+label.toLowerCase(),''));for(const n of items)if(n.name.toLowerCase().includes(search.value.toLowerCase())||n.key===selected)select.append(new Option(n.name,n.key));select.value=selected;}
    search.oninput=draw;select.onchange=()=>onchange(items.find(n=>n.key===select.value));
    let request=null,version=0;
    async function load(append){if(!request)return;const own=++version,req={...request,offset:append?next:0};more.disabled=true;retry.hidden=true;select.disabled=true;status.textContent='Loading '+label.toLowerCase()+'...';try{const page=await scope.job('/metadata/tree',{connectionId,database,...req});if(scope.closed||own!==version)return;const nodes=page.nodes.map(n=>({...n,pageOffset:page.offset??req.offset}));items=append?[...items,...nodes]:nodes;next=page.nextOffset;draw();more.hidden=next===undefined;status.textContent=items.length?'Choose from the loaded '+label.toLowerCase()+'.':'No '+label.toLowerCase()+' are visible with this connection.';}catch(e){if(!scope.closed&&own===version){status.textContent=e.message;retry.hidden=false;}}finally{if(!scope.closed&&own===version){select.disabled=false;more.disabled=false;}}}
    return{select,fixed(name){items=[{name,schema:name,key:name}];draw();select.value=name;select.disabled=true;search.disabled=true;onchange(items[0]);},async reset(req){version++;request=req;items=[];next=undefined;search.value='';select.replaceChildren(new Option('Choose '+label.toLowerCase(),''));more.hidden=retry.hidden=true;if(req)await load(false);},choose(name){const n=items.find(n=>n.name===name);if(n){select.value=n.key;onchange(n);}}};}
  const reset=()=>{revision++;source=null;changed(null);};
  const catalogOnly=['mysql','mariadb'].includes(engine);
  const schemas=catalog(catalogOnly?'Database':'Schemas',node=>{reset();void tables.reset(node?{kind:kind.value,schema:node.schema||node.name}:null);});
  const kind=field(root,'Object type',el('select'));kind.append(new Option('Tables','tables'));if(materialized)kind.append(new Option('Materialized views','materialized_views'));kind.onchange=()=>{reset();const selected=schemas.select.selectedOptions[0];void tables.reset(selected?.value?{kind:kind.value,schema:selected.textContent}:null);};
  const tables=catalog('Tables / objects',async node=>{reset();if(!node)return;const own=revision;status.textContent='Loading columns for '+node.name+'...';try{const parent={kind:kind.value,database,schema:node.schema||schemas.select.selectedOptions[0].textContent,offset:node.pageOffset};const result=await scope.job('/query-builder/source',{connectionId,parent,key:node.key});if(scope.closed||own!==revision)return;source=result;changed(result);status.textContent='Columns loaded for '+result.name+'.';}catch(e){if(!scope.closed&&own===revision)status.textContent=e.message+' Select the object again to retry.';}});
  root.append(status);if(catalogOnly)schemas.fixed(database||schema);else void schemas.reset({kind:'schemas'}).then(()=>{if(!scope.closed)schemas.choose(schema);});return{root,get source(){return source;}};
}

export function keyDialog({api,connectionId,database,schema,columns=null,category='Indexes',engine='',initial=[],accept}){
  const dialog=el('dialog');dialog.className='designer-dialog schema-picker-dialog';dialog.setAttribute('aria-label',category==='Primary key'?'Choose primary key':'Choose '+category.toLowerCase());
  const header=el('header',category==='Foreign Keys'?'Configure foreign key':'Choose '+category.toLowerCase()),body=el('div'),footer=el('footer');body.className='designer-dialog-body';dialog.append(header,body,footer);document.body.append(dialog);
  const scope=metadataScope(api);let relation=null;
  const foreign=category==='Foreign Keys',standalone=columns===null,primary=category==='Primary key';
  const name=!standalone&&!primary?field(body,'Object name',el('input')):null;
  const kind=category==='Constraints'?field(body,'Constraint kind',el('select')):null;if(kind)kind.append(new Option('CHECK','CHECK'),new Option('UNIQUE','UNIQUE'));
  const check=el('section');if(kind)body.append(check);const expression=kind?field(check,'Check expression',el('textarea')):null;
  const unique=category==='Indexes'&&!standalone?field(body,'Unique',el('input')):null;if(unique)unique.type='checkbox';
  if(foreign)body.append(el('p','Referenced columns must form a primary or unique key. The database validates key eligibility and compatible types when you apply the reviewed SQL.'));if(primary)body.append(el('p','Remove all selected columns to remove the primary key. Changes require SQL review.'));
  const selection=columnSelection(body,{columns:columns??[],foreign,initial});
  if(foreign||standalone)relation=relationSelection(body,{scope,connectionId,database,schema,engine,materialized:standalone&&engine==='postgresql',changed(value){if(foreign)selection.setReferences(value?.columns??[]);else selection.setColumns(value?.columns??[]);}});
  if(kind){const sync=()=>{selection.root.hidden=kind.value==='CHECK';check.hidden=kind.value!=='CHECK';};kind.onchange=sync;sync();const insert=field(check,'Insert column into check expression',el('select'));insert.append(new Option('Choose a column',''));for(const c of columns)insert.append(new Option(c.name,c.name));insert.onchange=()=>{if(!insert.value)return;const q=quoteIdentifier(insert.value,['mysql','mariadb'].includes(engine)?'`':'"');expression.setRangeText(q,expression.selectionStart,expression.selectionEnd,'end');insert.value='';expression.focus();};}
  const status=el('p');status.setAttribute('role','alert');body.append(status);
  const close=()=>dialog.close();header.append(button('Close','x',close));footer.append(button('Use selection','check',()=>{try{if(name&&!name.value.trim())throw Error('Enter an object name.');if(kind?.value==='CHECK'){if(!expression.value.trim())throw Error('Enter a check expression.');}else selection.validate(primary);if((foreign||standalone)&&!relation.source)throw Error('Choose an object and wait for its columns to load.');accept({category,action:'add',name:name?.value??'',kind:foreign?'FOREIGN KEY':kind?.value,columns:kind?.value==='CHECK'?[]:selection.value,references:foreign?selection.references:[],schema:relation?.source?.schema,table:relation?.source?.name,source:relation?.source,expression:kind?.value==='CHECK'?expression.value:'',unique:!!unique?.checked});close();}catch(e){status.textContent=e.message;}}),button('Cancel','x',close));
  dialog.addEventListener('close',()=>{scope.close();dialog.remove();},{once:true});dialog.showModal();return dialog;
}
