package io.doindev.codegraph.dba;

import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.*;
import java.security.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

class ConnectionSetupTest {
    @TempDir Path root;
    static ObjectNode input()throws Exception{return new DbaTest().input().put("templateId","h2").put("confirmDriverEffects",true);}
    static JsonNode await(QueryJobs jobs,String owner,JsonNode submitted)throws Exception{long until=System.currentTimeMillis()+20000;JsonNode state;do{state=jobs.status(owner,submitted.path("id").asText());if(state.path("finished").asLong()>0)return state;Thread.sleep(20);}while(System.currentTimeMillis()<until);throw new AssertionError("Job did not finish");}
    @Test void templateOrderCustomBlankAndVendorCapability(){var all=DatabaseCatalog.json();var names=java.util.stream.StreamSupport.stream(all.spliterator(),false).map(n->n.path("name").asText()).toList();assertTrue(names.size()>40);assertEquals("Custom",names.getLast());assertEquals(names.subList(0,names.size()-1).stream().sorted(String.CASE_INSENSITIVE_ORDER).toList(),names.subList(0,names.size()-1));for(String field:List.of("groupId","artifactId","driverClass","url","port"))assertEquals("",all.get(all.size()-1).path(field).asText());for(var t:all)assertEquals(t.path("id").asText().equals("postgresql"),t.path("advancedMcp").asBoolean());assertTrue(DatabaseCatalog.knownPublic("snowflake","private_key_file"));assertFalse(DatabaseCatalog.knownPublic("snowflake","private_key_pwd"));assertFalse(DatabaseCatalog.knownPublic("bigquery","OAuthPvtKey"));assertTrue(DatabaseCatalog.knownPublic("bigquery","OAuthPvtKeyPath"));assertEquals("all",DatabaseCatalog.classifier("bigquery"));assertTrue(DriverBundles.stable("13.2.0.jre11","azure-sql"));assertFalse(DriverBundles.stable("13.2.0.jre8","azure-sql"));}
    @Test void draftTestIsEphemeralReturnsVersionQueryAndReceiptIsOwnerBound()throws Exception{
        var vault=new DbaTest.MemoryVault();try(var profiles=new Profiles(root,vault);var connections=new Connections(profiles);var jobs=new QueryJobs(connections,new DbaConfig(root,64L<<20,2,100,100,10),o->true)){
            var setup=new ConnectionSetup(profiles,jobs);var input=input().put("password","temporary-test-password");String original=Files.readString(root.resolve("profiles.json"));
            JsonNode state=await(jobs,"alice",setup.operation("alice","draft-test",input));assertEquals("complete",state.path("state").asText(),state.toString());JsonNode result=state.path("result");assertTrue(result.path("connected").asBoolean());assertEquals("SELECT H2VERSION()",result.path("versionQuery").asText());assertEquals(1,result.path("versionResult").path("rows").size());
            assertEquals(original,Files.readString(root.resolve("profiles.json")));assertTrue(vault.secrets.isEmpty());assertEquals(0,connections.count());assertFalse(state.toString().contains("temporary-test-password"));
            input.put("receipt",result.path("receipt").asText());assertThrows(IllegalArgumentException.class,()->setup.save("bob",null,input));
            var edited=input.deepCopy().put("name","changed");assertThrows(IllegalArgumentException.class,()->setup.save("alice",null,edited));
            var saved=setup.save("alice",null,input);assertFalse(saved.has("validationStatus"));assertFalse(Files.readString(root.resolve("profiles.json")).contains("receipt"));assertEquals(1,profiles.publicList().size());
        }
    }
    @Test void untestedStillRequiresRealDriverAndRequiredValues()throws Exception{try(var profiles=new Profiles(root,new DbaTest.MemoryVault());var connections=new Connections(profiles);var jobs=new QueryJobs(connections,new DbaConfig(root,64L<<20,2,100,100,10),o->true)){
        var setup=new ConnectionSetup(profiles,jobs);var input=input();assertThrows(IllegalArgumentException.class,()->setup.save("alice",null,input));input.put("saveUntested",true);assertDoesNotThrow(()->setup.save("alice",null,input));assertThrows(Exception.class,()->setup.save("alice",null,input.put("driverClass","not.a.Driver")));
    }}
    @Test void driverMutationInvalidatesTestReceipt()throws Exception{Path jar=root.resolve("copy.jar");Files.copy(Path.of(input().path("jar").asText()),jar);try(var profiles=new Profiles(root.resolve("data"),new DbaTest.MemoryVault());var connections=new Connections(profiles);var jobs=new QueryJobs(connections,new DbaConfig(root,64L<<20,2,100,100,10),o->true)){
        var setup=new ConnectionSetup(profiles,jobs);var in=input().put("jar",jar.toString());var state=await(jobs,"alice",setup.operation("alice","draft-test",in));assertEquals("complete",state.path("state").asText(),state.toString());in.put("receipt",state.path("result").path("receipt").asText());Files.write(jar,new byte[]{0},StandardOpenOption.APPEND);assertThrows(IllegalArgumentException.class,()->setup.save("alice",null,in));
    }}
    @Test void chunkedSecretsKeepReplaceRemoveAndNeverLeak()throws Exception{var vault=new DbaTest.MemoryVault();try(var p=new Profiles(root,vault)){
        var in=input().put("password","original");in.putObject("properties").put("unknownSecret","s".repeat(12000)).put("MODE","PostgreSQL");var saved=p.put(null,in);String id=saved.path("id").asText();assertTrue(vault.secrets.size()>4);assertEquals("PostgreSQL",saved.path("properties").path("MODE").asText());assertFalse(saved.toString().contains("ssss"));
        var edit=input().put("password","replacement");p.put(id,edit);var props=p.credentials(p.get(id));assertEquals("s".repeat(12000),props.getProperty("unknownSecret"));assertEquals("replacement",props.getProperty("password"));
        edit.remove("password");edit.put("removePassword",true).putObject("secretProperties").putNull("unknownSecret");p.put(id,edit);assertTrue(vault.secrets.isEmpty());
    }}
    @Test void duplicatePropertiesRejectedAndOracleAtIsAllowed()throws Exception{var in=input();in.put("url","jdbc:h2:mem:test;MODE=PostgreSQL").putObject("properties").put("MODE","MySQL");assertThrows(IllegalArgumentException.class,()->ConnectionDraft.create(in,Profiles.JSON.createObjectNode()));in.put("url","jdbc:oracle:thin:@//localhost:1521/service");assertDoesNotThrow(()->ConnectionDraft.create(in,Profiles.JSON.createObjectNode()));}
    @Test void descriptorsAndClassDiscoveryDoNotConnect()throws Exception{try(var profiles=new Profiles(root,new DbaTest.MemoryVault());var connections=new Connections(profiles);var jobs=new QueryJobs(connections,new DbaConfig(root,64L<<20,2,100,100,10),o->true)){
        var setup=new ConnectionSetup(profiles,jobs);var in=input();in.putArray("jars").add(in.path("jar").asText());var inspected=ConnectionSetup.inspect(in);assertTrue(inspected.path("classes").toString().contains("org.h2.Driver"));var result=await(jobs,"alice",setup.operation("alice","properties",in));assertEquals("complete",result.path("state").asText(),result.toString());assertFalse(result.path("result").path("properties").isEmpty());assertEquals(0,connections.count());
    }}
    @Test void driverExceptionsExposeCodesNotSecrets(){var e=new java.sql.SQLException("password=NEVER-RETURN jdbc:whatever","28000",123);var result=QueryJobs.exceptionInfo(e);assertFalse(result.toString().contains("NEVER-RETURN"));assertEquals("28000",result.path("causes").get(0).path("sqlState").asText());assertEquals(123,result.path("causes").get(0).path("vendorCode").asInt());}
    static String pem(byte[] key){return "-----BEGIN PRIVATE KEY-----\n"+Base64.getMimeEncoder(64,new byte[]{10}).encodeToString(key)+"\n-----END PRIVATE KEY-----\n";}
    static KeyPair key(int bits)throws Exception{var generator=KeyPairGenerator.getInstance("RSA");generator.initialize(bits);return generator.generateKeyPair();}
    @Test void rsaKeyValidationFingerprintRotationAndWeakRejection()throws Exception{Path file=root.resolve("user-key.p8");String original=pem(key(2048).getPrivate().getEncoded());Files.writeString(file,original);var validated=SnowflakeKeys.validate(file.toString(),new char[0]);assertEquals(2048,validated.path("bits").asInt());assertFalse(validated.path("encrypted").asBoolean());assertEquals(original,Files.readString(file));Files.writeString(file,pem(key(2048).getPrivate().getEncoded()));assertNotEquals(validated.path("fingerprint"),SnowflakeKeys.validate(file.toString(),new char[0]).path("fingerprint"));Files.writeString(file,pem(key(1024).getPrivate().getEncoded()));assertThrows(IllegalArgumentException.class,()->SnowflakeKeys.validate(file.toString(),new char[0]));assertThrows(IllegalArgumentException.class,()->SnowflakeKeys.validate(root.resolve("missing").toString(),new char[0]));}
    @Test void encryptedPkcs8CorrectWrongAndMissingPassphrase()throws Exception{
        var encryptor=new org.bouncycastle.openssl.jcajce.JceOpenSSLPKCS8EncryptorBuilder(org.bouncycastle.openssl.PKCS8Generator.AES_256_CBC).setProvider(new org.bouncycastle.jce.provider.BouncyCastleProvider()).setPassword("unit-test-passphrase".toCharArray()).build();
        var generator=new org.bouncycastle.openssl.jcajce.JcaPKCS8Generator(key(2048).getPrivate(),encryptor);var text=new java.io.StringWriter();try(var writer=new org.bouncycastle.util.io.pem.PemWriter(text)){writer.writeObject(generator.generate());}Path file=root.resolve("encrypted.p8");Files.writeString(file,text.toString());char[] pass="unit-test-passphrase".toCharArray();assertTrue(SnowflakeKeys.validate(file.toString(),pass).path("encrypted").asBoolean());assertEquals(0,pass[0]);assertThrows(IllegalArgumentException.class,()->SnowflakeKeys.validate(file.toString(),"wrong".toCharArray()));assertThrows(IllegalArgumentException.class,()->SnowflakeKeys.validate(file.toString(),new char[0]));
    }
    @Test void unsupportedKeyFormatsAreRejected()throws Exception{Path file=root.resolve("key");for(String content:List.of("invalid","-----BEGIN OPENSSH PRIVATE KEY-----\naGVsbG8=\n-----END OPENSSH PRIVATE KEY-----","-----BEGIN PUBLIC KEY-----\n"+Base64.getEncoder().encodeToString(key(2048).getPublic().getEncoded())+"\n-----END PUBLIC KEY-----")){Files.writeString(file,content);assertThrows(IllegalArgumentException.class,()->SnowflakeKeys.validate(file.toString(),new char[0]));}var ec=KeyPairGenerator.getInstance("EC");ec.initialize(256);Files.writeString(file,pem(ec.generateKeyPair().getPrivate().getEncoded()));assertThrows(IllegalArgumentException.class,()->SnowflakeKeys.validate(file.toString(),new char[0]));}
    @Test void stableVersionFilter(){assertTrue(DriverBundles.stable("4.0.0","snowflake"));assertFalse(DriverBundles.stable("4.1.0-beta1","snowflake"));assertFalse(DriverBundles.stable("13.2.0.jre8","sqlserver"));assertTrue(DriverBundles.stable("13.2.0.jre11","sqlserver"));}
}
