package io.doindev.codegraph.dba;
import com.fasterxml.jackson.databind.node.*;
import java.io.StringReader;
import java.lang.reflect.*;
import java.sql.*;
import java.nio.file.Path;
import java.util.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
class ExplainPlansTest {
 @TempDir Path root;
 @Test void everyTemplateHasAnExplicitOutcome(){assertEquals(new TreeSet<>(DatabaseCatalog.ALL.stream().map(DatabaseCatalog.Template::id).toList()),new TreeSet<>(ExplainPlans.REGISTRY.keySet()));for(var a:ExplainPlans.REGISTRY.values()){assertFalse(a.protocol().isBlank());if(a.protocol().contains("unsupported")||a.protocol().equals("missing_driver_facility"))assertFalse(a.reason().isBlank());}}
 static class Fake implements InvocationHandler {
  final List<String> commands=new ArrayList<>();final Map<Integer,Object> bindings=new HashMap<>();final String product;String version="16.0",fail="";boolean rollback;String current;
  Fake(String product){this.product=product;}
  Connection connection(){return proxy(Connection.class,this);}
  public Object invoke(Object proxy,Method method,Object[] args)throws Throwable{String name=method.getName();if(name.equals("getMetaData"))return proxy(DatabaseMetaData.class,(p,m,a)->switch(m.getName()){case "getDatabaseProductName"->product;case "getDatabaseProductVersion"->version;case "getDatabaseMajorVersion"->16;case "getDatabaseMinorVersion"->0;case "getDriverName"->"Contract JDBC";default->zero(m.getReturnType());});if(name.equals("prepareStatement")||name.equals("createStatement")){String sql=args==null?null:(String)args[0];return proxy(PreparedStatement.class,(p,m,a)->{String command=sql==null&&a!=null&&a.length>0?a[0].toString():sql;switch(m.getName()){case "setString","setBoolean","setBigDecimal","setNull"->{bindings.put((Integer)a[0],a[1]);return null;}case "execute","executeQuery"->{commands.add(command);current=command;if(!fail.isEmpty()&&command.equals(fail))throw new SQLException("denied","42501");if(m.getName().equals("execute"))return false;return rows(command.startsWith("SELECT QUERYNO")?null:command.equals("SELECT version()")?product+" "+version:"estimated plan");}default->{return zero(m.getReturnType());}}});}if(name.equals("setSavepoint"))return new Savepoint(){public int getSavepointId(){return 1;}public String getSavepointName(){return "job";}};if(name.equals("rollback")){rollback=true;return null;}return zero(method.getReturnType());}
 }
 static Object zero(Class<?> type){if(type==boolean.class)return false;if(type==int.class)return 0;if(type==long.class)return 0L;return null;}
 @SuppressWarnings("unchecked") static <T>T proxy(Class<T> type,InvocationHandler handler){return (T)Proxy.newProxyInstance(type.getClassLoader(),new Class[]{type},handler);}
 static ResultSet rows(String text){int[] cursor={0};return proxy(ResultSet.class,(p,m,a)->switch(m.getName()){case "next"->text!=null&&cursor[0]++==0;case "getCharacterStream"->new StringReader(text);case "getString"->text;case "getMetaData"->proxy(ResultSetMetaData.class,(p2,m2,a2)->switch(m2.getName()){case "getColumnCount"->1;case "getColumnLabel"->"Plan";case "getColumnType"->Types.VARCHAR;default->zero(m2.getReturnType());});default->zero(m.getReturnType());});}
 @Test void nativeCommandsBindWithoutExecutingDataQueries()throws Exception{try(var profiles=new Profiles(root,new DbaTest.MemoryVault());var connections=new Connections(profiles);var jobs=new QueryJobs(connections,new DbaConfig(root,64L<<20,2,100,100,10),s->true)){for(var a:ExplainPlans.REGISTRY.values())if(a.protocol().equals("native")&&!Set.of("csv","json","redis").contains(a.id())){String product=switch(a.id()){case "hsqldb"->"HSQL Database Engine";case "hana"->"HANA";default->a.id();};Fake f=new Fake(product);QueryJobs.Job job=jobs.new Job("human","test");var result=ExplainPlans.collect(job,f.connection(),"SELECT ID FROM ITEM WHERE ID = ?",Profiles.JSON.createArrayNode().add(7));assertTrue(result.path("estimated").asBoolean(),a.id());assertFalse(result.path("executed").asBoolean());assertTrue(f.commands.contains(a.command()+"SELECT ID FROM ITEM WHERE ID = "+(a.id().equals("hsqldb")?"7":"?")),a.id()+f.commands);if(!a.id().equals("hsqldb"))assertEquals(new java.math.BigDecimal("7"),f.bindings.get(1));assertTrue(f.commands.stream().noneMatch(s->s.contains("ANALYZE TRUE")||s.contains("PROFILE")||s.equals("SELECT ID FROM ITEM WHERE ID = ?")));}}}
 @Test void sessionModesAndPlanTablesAreCleanedAfterFailure()throws Exception{try(var profiles=new Profiles(root,new DbaTest.MemoryVault());var connections=new Connections(profiles);var jobs=new QueryJobs(connections,new DbaConfig(root,64L<<20,2,100,100,10),s->true)){Fake sqlServer=new Fake("Microsoft SQL Server");sqlServer.fail="SELECT ID FROM ITEM";var error=assertThrows(IllegalArgumentException.class,()->ExplainPlans.collect(jobs.new Job("human","test"),sqlServer.connection(),sqlServer.fail,Profiles.JSON.createArrayNode()));assertTrue(error.getMessage().startsWith("missing_privileges:"));assertEquals(List.of("SET SHOWPLAN_XML ON","SELECT ID FROM ITEM","SET SHOWPLAN_XML OFF"),sqlServer.commands);assertTrue(ExplainPlans.capability(sqlServer.connection()).path("supported").asBoolean(),"A permission failure is not cached as unsupported");for(String product:List.of("Oracle","HANA","DB2/LINUXX8664","DSN")){Fake f=new Fake(product);var result=ExplainPlans.collect(jobs.new Job("human","test"),f.connection(),"SELECT ID FROM ITEM",Profiles.JSON.createArrayNode());assertTrue(f.rollback,product);assertTrue(result.path("estimated").asBoolean());assertTrue(f.commands.stream().anyMatch(s->s.startsWith("EXPLAIN PLAN")));assertTrue(f.commands.stream().noneMatch(s->s.startsWith("DELETE")||s.equals("SELECT ID FROM ITEM")));}}}
 @Test void actualProductVersionsAndUnsupportedFacilitiesAreDistinct()throws Exception{Fake db2=new Fake("DB2");db2.version="DSN13015";assertEquals("db2-zos",ExplainPlans.capability(db2.connection()).path("engine").asText());assertEquals("missing_driver_facility",ExplainPlans.capability(new Fake("AS/400").connection()).path("status").asText());assertEquals("unsupported_estimated_plan",ExplainPlans.capability(new Fake("BigQuery").connection()).path("status").asText());assertEquals("calcite",ExplainPlans.capability(new Fake("Apache Calcite").connection()).path("engine").asText());}
 @Test void openSearchUsesOnlyItsExplainEndpointAndClosesBoundedResponses()throws Exception{try(var profiles=new Profiles(root,new DbaTest.MemoryVault());var connections=new Connections(profiles);var jobs=new QueryJobs(connections,new DbaConfig(root,64L<<20,2,100,100,10),s->true)){
  boolean[] closed={false};var job=jobs.new Job("human","test");var result=OpenSearchExplain.request(job,"/_plugins/_sql/_explain","SELECT NAME FROM ITEM WHERE NAME = ?",Profiles.JSON.createArrayNode().add("O'Reilly"),(path,body,timeout)->{assertEquals("/_plugins/_sql/_explain",path);assertTrue(timeout>0);assertTrue(Profiles.JSON.readTree(body).path("query").asText().contains("'O''Reilly'"));return new OpenSearchExplain.Response(200,new StringReader("{\"root\":{\"name\":\"Project\"}}"),()->closed[0]=true);});assertTrue(closed[0]);assertEquals("json",ExplainPlans.normalize("opensearch","SELECT NAME FROM ITEM",result).path("format").asText());
  var denied=assertThrows(SQLException.class,()->OpenSearchExplain.request(job,"/_plugins/_sql/_explain","SELECT ID FROM ITEM",Profiles.JSON.createArrayNode(),(path,body,timeout)->new OpenSearchExplain.Response(403,new StringReader("denied"),()->{})));assertEquals("42501",denied.getSQLState());
 }}
 @Test void formatsRemainUsableAndXmlCannotResolveEntities(){var raw=ExplainPlans.textRaw("[{\"Plan\":{\"Node Type\":\"Hash Join\",\"Total Cost\":7.5,\"Plans\":[{\"Node Type\":\"Seq Scan\",\"Relation Name\":\"item\",\"Plan Rows\":4}]}}]",100000);var json=ExplainPlans.normalize("postgresql","SELECT * FROM item",raw);assertEquals("json",json.path("format").asText());assertEquals("Hash Join",json.path("nodes").get(0).path("operator").asText());assertEquals(1,json.path("nodes").get(0).path("children").size());var xml=ExplainPlans.normalize("sqlserver","SELECT 1",ExplainPlans.textRaw("<ShowPlanXML><RelOp PhysicalOp='Index Scan' EstimateRows='3'/></ShowPlanXML>",100000));assertEquals("xml",xml.path("format").asText());assertFalse(xml.path("nodes").isEmpty());var malicious=ExplainPlans.normalize("sqlserver","SELECT 1",ExplainPlans.textRaw("<!DOCTYPE a [<!ENTITY x SYSTEM 'file:///not-readable'>]><a>&x;</a>",100000));assertTrue(malicious.path("nodes").isEmpty());assertTrue(malicious.path("rawText").asText().contains("DOCTYPE"));var truncated=ExplainPlans.normalize("h2","SELECT 1",ExplainPlans.textRaw("abcdef".repeat(50),20));assertTrue(truncated.path("truncated").asBoolean());assertTrue(truncated.path("observations").toString().contains("truncated"));}
}
