package io.doindev.codegraph.dba;

import com.fasterxml.jackson.databind.node.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.Path;
import static org.junit.jupiter.api.Assertions.*;

@EnabledIfEnvironmentVariable(named="DBA_COMPARE_DISPOSABLE",matches="cgraph-compare-qa-[a-f0-9]+")
class MysqlWorkflowVendorTest {
    @TempDir Path directory;
    @Test @Timeout(120) void nativeSqlModeAndEventTimeZoneSurviveGeneration()throws Exception {
        String engine=System.getenv("DBA_COMPARE_VENDOR");Assumptions.assumeTrue(MysqlDialect.supports(engine));
        try(var profiles=new Profiles(directory,new DbaTest.MemoryVault());var connections=new Connections(profiles);var jobs=new QueryJobs(connections,new DbaConfig(directory,384L<<20,2,100,100,60),s->true);var compare=new DatabaseCompare(profiles,connections,jobs,directory,s->true)) {
            String source=profiles.put(null,CompareVendorIntegrationTest.profile(engine,"Mode source",System.getenv("DBA_COMPARE_SOURCE"))).path("id").asText(),dest=profiles.put(null,CompareVendorIntegrationTest.profile(engine,"Mode destination",System.getenv("DBA_COMPARE_DESTINATION"))).path("id").asText();
            try(var a=connections.open(source);var b=connections.open(dest);var left=a.createStatement();var right=b.createStatement()) {
                a.setAutoCommit(true);b.setAutoCommit(true);left.execute("SET SESSION sql_mode='ANSI_QUOTES,NO_BACKSLASH_ESCAPES'");left.execute("SET SESSION time_zone='+05:30'");left.execute("CREATE TABLE compare_test.mode_log(note varchar(80))");left.execute("CREATE PROCEDURE compare_test.mode_program() BEGIN SELECT 'slash\\' AS \"value\"; END");left.execute("CREATE EVENT compare_test.mode_event ON SCHEDULE EVERY 1 DAY STARTS '2028-01-01 12:00:00' DISABLE DO INSERT INTO compare_test.mode_log VALUES ('event')");
                var input=Profiles.JSON.createObjectNode().put("sourceReceipt",DatabaseCompareTest.receipt(compare,jobs,source,"compare_test")).put("destinationReceipt",DatabaseCompareTest.receipt(compare,jobs,dest,"compare_test")).put("dataMode","none");input.putArray("objectTypes").add("procedures").add("events");var ids=input.putArray("objectIds");for(String[] object:new String[][]{{"procedures","mode_program"},{"events","mode_event"}})ids.add(TableDesigner.hash(Profiles.JSON.getNodeFactory().textNode(CompareCatalog.key("compare_test",object[0],object[1]))).substring(0,32));
                String id=DatabaseCompareTest.finish(jobs,compare.start("human",input)).path("comparisonId").asText();var selected=DatabaseCompareTest.select(compare,id).put("dataMode","none");var artifact=DatabaseCompareTest.finish(jobs,compare.generate("human",id,selected));String sql=compare.artifacts.preview("human",artifact.path("artifactId").asText()).path("sql").asText();assertTrue(sql.contains("NO_BACKSLASH_ESCAPES"));assertTrue(sql.contains("time_zone='+05:30'"));for(var unit:MysqlScript.extract(sql,65536,MysqlScript.Mode.parse("")))right.execute(unit.sql());compare.remove("human",id);
                try(var rows=right.executeQuery("CALL compare_test.mode_program()")){assertTrue(rows.next());assertEquals("slash\\",rows.getString(1));}
                try(var rows=right.executeQuery("SELECT TIME_ZONE,STATUS FROM information_schema.EVENTS WHERE EVENT_SCHEMA='compare_test' AND EVENT_NAME='mode_event'")){assertTrue(rows.next());assertEquals("+05:30",rows.getString(1));assertEquals("DISABLED",rows.getString(2));}
                id=DatabaseCompareTest.finish(jobs,compare.start("human",input)).path("comparisonId").asText();for(var object:compare.results("human",id,0,200,"","").path("objects"))if(object.path("supported").asBoolean())assertEquals("identical",object.path("status").asText(),object.toString());compare.remove("human",id);System.out.println("MYSQL_SQL_MODE_EVENT_VERIFIED "+engine);
            }
        }
    }
    @Test @Timeout(120) void autoIncrementAdvancementIsIndependentAndNeverLowersCapturedState()throws Exception {
        String engine=System.getenv("DBA_COMPARE_VENDOR");Assumptions.assumeTrue(MysqlDialect.supports(engine));
        try(var profiles=new Profiles(directory,new DbaTest.MemoryVault());var connections=new Connections(profiles);var jobs=new QueryJobs(connections,new DbaConfig(directory,384L<<20,2,100,100,60),s->true);var compare=new DatabaseCompare(profiles,connections,jobs,directory,s->true)) {
            String source=profiles.put(null,CompareVendorIntegrationTest.profile(engine,"Counter source",System.getenv("DBA_COMPARE_SOURCE"))).path("id").asText(),dest=profiles.put(null,CompareVendorIntegrationTest.profile(engine,"Counter destination",System.getenv("DBA_COMPARE_DESTINATION"))).path("id").asText();
            try(var a=connections.open(source);var b=connections.open(dest);var left=a.createStatement();var right=b.createStatement()) {
                a.setAutoCommit(true);b.setAutoCommit(true);for(var st:java.util.List.of(left,right))st.execute("CREATE TABLE compare_test.auto_state(id bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY, note varchar(80) DEFAULT ' AUTO_INCREMENT=123')");left.execute("ALTER TABLE compare_test.auto_state AUTO_INCREMENT=10");right.execute("ALTER TABLE compare_test.auto_state AUTO_INCREMENT=100");
                var input=Profiles.JSON.createObjectNode().put("sourceReceipt",DatabaseCompareTest.receipt(compare,jobs,source,"compare_test")).put("destinationReceipt",DatabaseCompareTest.receipt(compare,jobs,dest,"compare_test")).put("dataMode","none");input.putArray("objectTypes").add("tables");input.putArray("objectIds").add(TableDesigner.hash(Profiles.JSON.getNodeFactory().textNode(CompareCatalog.key("compare_test","tables","auto_state"))).substring(0,32));
                for(int expected:new int[]{100,1001}) {
                    if(expected==1001)left.execute("ALTER TABLE compare_test.auto_state AUTO_INCREMENT=1000");String id=DatabaseCompareTest.finish(jobs,compare.start("human",input)).path("comparisonId").asText();var counterReview=compare.results("human",id,0,200,"","");assertEquals("identical",counterReview.path("objects").path(0).path("status").asText(),counterReview.toPrettyString());var choice=DatabaseCompareTest.select(compare,id).put("dataMode","none");
                    var artifact=DatabaseCompareTest.finish(jobs,compare.generate("human",id,choice));assertFalse(compare.artifacts.preview("human",artifact.path("artifactId").asText()).path("sql").asText().contains("AUTO_INCREMENT ="));if(expected==1001)left.execute("ALTER TABLE compare_test.auto_state AUTO_INCREMENT=1001");choice.put("syncAutoIncrement",true);artifact=DatabaseCompareTest.finish(jobs,compare.generate("human",id,choice));String sql=compare.artifacts.preview("human",artifact.path("artifactId").asText()).path("sql").asText();assertTrue(sql.contains("AUTO_INCREMENT = "+expected));for(var unit:MysqlScript.extract(sql,65536,MysqlScript.Mode.parse("")))right.execute(unit.sql());compare.remove("human",id);
                    right.execute("INSERT INTO compare_test.auto_state(note) VALUES('destination verification')");try(var rows=right.executeQuery("SELECT MAX(id) FROM compare_test.auto_state")){assertTrue(rows.next());assertEquals(expected,rows.getInt(1));}
                }
                System.out.println("MYSQL_AUTO_INCREMENT_VERIFIED "+engine);
            }
        }
    }
    @Test @Timeout(120) void storedProgramsAndDefinersGenerateCompleteExecutableUnits()throws Exception{
        String engine=System.getenv("DBA_COMPARE_VENDOR");Assumptions.assumeTrue(MysqlDialect.supports(engine));
        try(var profiles=new Profiles(directory,new DbaTest.MemoryVault());var connections=new Connections(profiles);var jobs=new QueryJobs(connections,new DbaConfig(directory,384L<<20,2,100,100,60),s->true);var compare=new DatabaseCompare(profiles,connections,jobs,directory,s->true)){
            String source=profiles.put(null,CompareVendorIntegrationTest.profile(engine,"Programs source",System.getenv("DBA_COMPARE_SOURCE"))).path("id").asText(),dest=profiles.put(null,CompareVendorIntegrationTest.profile(engine,"Programs destination",System.getenv("DBA_COMPARE_DESTINATION"))).path("id").asText();
            try(var a=connections.open(source);var b=connections.open(dest);var left=a.createStatement();var right=b.createStatement()){
                a.setAutoCommit(true);b.setAutoCommit(true);left.execute("CREATE TABLE compare_test.program_table(id int PRIMARY KEY, amount decimal(30,8))");left.execute("CREATE PROCEDURE compare_test.program_copy(INOUT amount DECIMAL(30,8)) SQL SECURITY INVOKER BEGIN SET amount=amount+0.00000001; SELECT amount; SELECT 'literal;?'; END");left.execute("CREATE TRIGGER compare_test.program_trigger BEFORE INSERT ON compare_test.program_table FOR EACH ROW SET NEW.amount=COALESCE(NEW.amount,1)");
                left.execute("CREATE USER 'program_reader'@'%' IDENTIFIED BY 'Fixture-only-123'");right.execute("CREATE USER 'program_reader'@'%' IDENTIFIED BY 'Fixture-only-123'");left.execute("GRANT SELECT(id) ON compare_test.program_table TO 'program_reader'@'%' WITH GRANT OPTION");
                var input=Profiles.JSON.createObjectNode().put("sourceReceipt",DatabaseCompareTest.receipt(compare,jobs,source,"compare_test")).put("destinationReceipt",DatabaseCompareTest.receipt(compare,jobs,dest,"compare_test")).put("dataMode","none");input.putArray("objectTypes").add("procedures").add("triggers");input.putArray("objectIds").add(TableDesigner.hash(Profiles.JSON.getNodeFactory().textNode(CompareCatalog.key("compare_test","procedures","program_copy"))).substring(0,32)).add(TableDesigner.hash(Profiles.JSON.getNodeFactory().textNode(CompareCatalog.key("compare_test","triggers","program_trigger"))).substring(0,32));
                String id=DatabaseCompareTest.finish(jobs,compare.start("human",input)).path("comparisonId").asText();var result=compare.results("human",id,0,200,"","");for(var o:result.path("objects"))if(!o.path("kind").asText().equals("indexes"))assertTrue(o.path("supported").asBoolean(),o.toPrettyString());var selected=DatabaseCompareTest.select(compare,id).put("dataMode","none").put("definerPolicy","preserve");var artifact=DatabaseCompareTest.finish(jobs,compare.generate("human",id,selected));String sql=compare.artifacts.preview("human",artifact.path("artifactId").asText()).path("sql").asText();assertTrue(sql.contains("DELIMITER"));for(var unit:MysqlScript.extract(sql,65536,MysqlScript.Mode.parse("")))right.execute(unit.sql());compare.remove("human",id);
                var parameters=Profiles.JSON.createArrayNode();parameters.addObject().put("mode","inout").put("type","DECIMAL").put("value","12345678901234567890.12345678");var called=HumanSqlTest.finish(jobs,"human",jobs.humanQuery("human",dest,"{call compare_test.program_copy(?)}",parameters,true));assertEquals("complete",called.path("state").asText(),called.toString());assertEquals("12345678901234567890.12345679",called.path("result").path("outputParameters").path(0).path("value").asText(),called.toString());assertTrue(called.path("result").path("results").size()>=2);
                right.execute("INSERT INTO compare_test.program_table(id) VALUES(1)");try(var rows=right.executeQuery("SELECT amount FROM compare_test.program_table")){assertTrue(rows.next());assertEquals("1.00000000",rows.getBigDecimal(1).toPlainString());}
                id=DatabaseCompareTest.finish(jobs,compare.start("human",input)).path("comparisonId").asText();result=compare.results("human",id,0,200,"","");for(var o:result.path("objects"))if(o.path("supported").asBoolean())assertEquals("identical",o.path("status").asText(),o.toPrettyString());compare.remove("human",id);System.out.println("MYSQL_PROGRAM_GENERATION_VERIFIED "+engine);
            }
        }
    }
    @Test @Timeout(120) void nativeAlterScriptExecutesAndRepeatComparisonIsIdentical()throws Exception{
        String engine=System.getenv("DBA_COMPARE_VENDOR");Assumptions.assumeTrue(MysqlDialect.supports(engine));
        try(var profiles=new Profiles(directory,new DbaTest.MemoryVault());var connections=new Connections(profiles);var jobs=new QueryJobs(connections,new DbaConfig(directory,384L<<20,2,100,100,60),s->true);var compare=new DatabaseCompare(profiles,connections,jobs,directory,s->true)){
            String source=profiles.put(null,CompareVendorIntegrationTest.profile(engine,"ALTER source",System.getenv("DBA_COMPARE_SOURCE"))).path("id").asText(),dest=profiles.put(null,CompareVendorIntegrationTest.profile(engine,"ALTER destination",System.getenv("DBA_COMPARE_DESTINATION"))).path("id").asText();
            try(var a=connections.open(source);var b=connections.open(dest);var left=a.createStatement();var right=b.createStatement()){
                a.setAutoCommit(true);b.setAutoCommit(true);left.execute("CREATE DATABASE native_alter_db");right.execute("CREATE DATABASE native_alter_db");
                left.execute("CREATE TABLE native_alter_db.native_alter(id bigint unsigned PRIMARY KEY, title varchar(90) COLLATE utf8mb4_bin DEFAULT 'changed' INVISIBLE, touched timestamp(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), doubled bigint unsigned AS (id*2) VIRTUAL, added int NULL, KEY title_idx(title(8)), CONSTRAINT nonnegative CHECK (id>0)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                right.execute("CREATE TABLE native_alter_db.native_alter(id bigint unsigned PRIMARY KEY, title varchar(30) COLLATE utf8mb4_bin DEFAULT 'before' INVISIBLE, touched timestamp(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), doubled bigint unsigned AS (id*2) VIRTUAL, KEY title_idx(title(4))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
                var input=Profiles.JSON.createObjectNode().put("sourceReceipt",DatabaseCompareTest.finish(jobs,compare.test("human",Profiles.JSON.createObjectNode().put("connectionId",source).put("database","native_alter_db").put("schema","native_alter_db"))).path("receipt").asText()).put("destinationReceipt",DatabaseCompareTest.finish(jobs,compare.test("human",Profiles.JSON.createObjectNode().put("connectionId",dest).put("database","native_alter_db").put("schema","native_alter_db"))).path("receipt").asText()).put("dataMode","none");input.putArray("objectTypes").add("tables");input.putArray("objectIds").add(TableDesigner.hash(Profiles.JSON.getNodeFactory().textNode(CompareCatalog.key("native_alter_db","tables","native_alter"))).substring(0,32));
                String id=DatabaseCompareTest.finish(jobs,compare.start("human",input)).path("comparisonId").asText();var selected=DatabaseCompareTest.select(compare,id).put("destructiveSchema",true).put("dataMode","none");var artifact=DatabaseCompareTest.finish(jobs,compare.generate("human",id,selected));String sql=compare.artifacts.preview("human",artifact.path("artifactId").asText()).path("sql").asText();assertTrue(sql.contains("ALTER TABLE"));for(var unit:MysqlScript.extract(sql,65536,MysqlScript.Mode.parse("")))right.execute(unit.sql());compare.remove("human",id);
                id=DatabaseCompareTest.finish(jobs,compare.start("human",input)).path("comparisonId").asText();var result=compare.results("human",id,0,200,"","");assertEquals("identical",result.path("objects").get(0).path("status").asText(),result.toPrettyString());compare.remove("human",id);
                System.out.println("MYSQL_NATIVE_ALTER_VERIFIED "+engine);
            }
        }
    }
    @Test @Timeout(120) void nativeCreateEditReopenPreservesAttributesAndStoredProgram()throws Exception{
        String engine=System.getenv("DBA_COMPARE_VENDOR");Assumptions.assumeTrue(MysqlDialect.supports(engine));
        try(var profiles=new Profiles(directory,new DbaTest.MemoryVault());var connections=new Connections(profiles);var jobs=new QueryJobs(connections,new DbaConfig(directory,384L<<20,2,100,100,60),s->true)){
            String id=profiles.put(null,CompareVendorIntegrationTest.profile(engine,"Native workflow",System.getenv("DBA_COMPARE_DESTINATION"))).path("id").asText();
            try(var connection=connections.open(id);var statement=connection.createStatement()){
                connection.setAutoCommit(true);var request=TableCreationTest.input("compare_test");((ObjectNode)request.path("target")).put("database","compare_test");
                var loaded=HumanSqlTest.finish(jobs,"human",jobs.tableProperties("human",id,request,false));assertEquals("complete",loaded.path("state").asText(),loaded.toString());var baseline=(ObjectNode)loaded.path("result");var draft=TableDesignerTest.draft(baseline);((ObjectNode)draft.path("fields")).put("name","native_designer");
                ((ArrayNode)draft.path("columns")).addObject().put("id","new:id").put("name","id").put("type","bigint unsigned").put("pk",1).put("nullable",false).put("identity","d");
                ((ArrayNode)draft.path("columns")).addObject().put("id","new:label").put("name","label").put("type","varchar(30)").put("pk",0).put("nullable",true).put("default","'start'");
                request.put("fingerprint",baseline.path("fingerprint").asText());request.set("draft",draft);var plan=TableDesignerTest.waitRetained(jobs,"human",jobs.tableProperties("human",id,request,true));assertEquals("complete",plan.path("state").asText(),plan.toString());
                var applied=HumanSqlTest.finish(jobs,"human",jobs.applyTableProperties("human",Profiles.JSON.createObjectNode().put("planId",plan.path("id").asText()).put("confirmed",true)));assertEquals("success",applied.path("result").path("status").asText(),applied.toString());jobs.remove("human",plan.path("id").asText());
                statement.execute("ALTER TABLE compare_test.native_designer MODIFY label varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT 'start' INVISIBLE, ADD touched timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), ADD generated_id bigint unsigned AS (length(label) + 1) VIRTUAL");
                var parent=Profiles.JSON.createObjectNode().put("kind","tables").put("database","compare_test").put("schema","compare_test");var browse=HumanSqlTest.finish(jobs,"human",jobs.metadataTree("human",id,parent));
                String key="";for(var node:browse.path("result").path("nodes"))if(node.path("name").asText().equals("native_designer"))key=node.path("key").asText();assertFalse(key.isBlank(),browse.toString());
                var edit=Profiles.JSON.createObjectNode().put("key",key);edit.set("parent",parent);loaded=HumanSqlTest.finish(jobs,"human",jobs.tableProperties("human",id,edit,false));assertEquals("complete",loaded.path("state").asText(),loaded.toString());baseline=(ObjectNode)loaded.path("result");draft=TableDesignerTest.draft(baseline);
                for(var column:draft.path("columns"))if(column.path("name").asText().equals("label"))((ObjectNode)column).put("type","varchar(90)").put("comment","kept");edit.put("fingerprint",baseline.path("fingerprint").asText());edit.set("draft",draft);
                plan=TableDesignerTest.waitRetained(jobs,"human",jobs.tableProperties("human",id,edit,true));assertEquals("complete",plan.path("state").asText(),plan.toString());applied=HumanSqlTest.finish(jobs,"human",jobs.applyTableProperties("human",Profiles.JSON.createObjectNode().put("planId",plan.path("id").asText()).put("confirmed",true)));assertEquals("success",applied.path("result").path("status").asText(),applied.toString());jobs.remove("human",plan.path("id").asText());
                try(var rows=statement.executeQuery("SHOW CREATE TABLE compare_test.native_designer")){assertTrue(rows.next());String ddl=rows.getString(2);assertTrue(ddl.contains("varchar(90)"));assertTrue(ddl.contains("utf8mb4_bin"));assertTrue(ddl.toUpperCase().contains("INVISIBLE"));assertTrue(ddl.toUpperCase().contains("ON UPDATE"));assertTrue(ddl.contains("generated_id"));}
                for(var unit:MysqlScript.extract("DELIMITER $$\nCREATE PROCEDURE compare_test.native_program(IN p INT) BEGIN SELECT p; SELECT 'a;?b'; END$$\nDELIMITER ;\n",16384,MysqlScript.Mode.parse("")))statement.execute(unit.sql());
                assertTrue(statement.execute("CALL compare_test.native_program(7)"));try(var rows=statement.getResultSet()){assertTrue(rows.next());assertEquals(7,rows.getInt(1));}assertTrue(statement.getMoreResults());try(var rows=statement.getResultSet()){assertTrue(rows.next());assertEquals("a;?b",rows.getString(1));}
                System.out.println("MYSQL_NATIVE_WORKFLOW_VERIFIED "+engine+" "+connection.getMetaData().getDatabaseProductVersion());
            }
        }
    }
}
