package io.doindev.codegraph.dba;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.Path;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
class VisualQueryTest {
 @TempDir Path root;
 static ObjectNode model(int count){ObjectNode m=VisualQuery.empty();for(int i=1;i<=count;i++){ObjectNode s=m.withArray("sources").addObject().put("id","s"+i).put("reference","PUBLIC.ITEM").put("name","ITEM").put("alias","t"+i);s.putArray("columns").addObject().put("name","ID").put("jdbcType",4).put("type","INTEGER");m.withArray("roots").add(VisualQuery.expression("source").put("source","s"+i));}m.withObject("detail").withArray("outputs").addObject().put("id","o1").put("alias","").set("expression",col("s1"));return m;}
 static ObjectNode col(String source){return VisualQuery.expression("column").put("source",source).put("name","ID");}
 static ObjectNode join(JsonNode left,JsonNode right,String type){ObjectNode j=VisualQuery.expression("join").put("id",UUID.randomUUID().toString()).put("type",type);j.set("left",left);j.set("right",right);ArrayNode pairs=j.putArray("pairs");if(!type.equals("CROSS")){ObjectNode p=pairs.addObject().put("op","=");p.set("left",col(VisualQuery.leafIds(left).iterator().next()));p.set("right",col(VisualQuery.leafIds(right).iterator().next()));}return j;}
 static ObjectNode compile(JsonNode model){ObjectNode request=Profiles.JSON.createObjectNode().put("quote","\"").put("engine","h2");request.set("model",model);return VisualQuery.compile(request);}
 @Test void disconnectedSourcesAndNestedOuterJoins(){var m=model(3);assertFalse(compile(m).path("valid").asBoolean());JsonNode a=m.path("roots").get(0),b=m.path("roots").get(1),c=m.path("roots").get(2);m.withArray("roots").removeAll().add(join(a,join(b,c,"INNER"),"LEFT"));var result=compile(m);assertTrue(result.path("valid").asBoolean(),result.toString());assertTrue(result.path("sql").asText().contains("LEFT JOIN (PUBLIC.ITEM AS \"t2\""));ObjectNode j=(ObjectNode)m.path("roots").get(0);j.withArray("pairs").addObject().put("op",">=").set("left",col("s1"));((ObjectNode)j.path("pairs").get(1)).set("right",col("s3"));assertTrue(compile(m).path("sql").asText().contains(" AND "));
 }
 @Test void exceedsSixteenSourcesWithinSqlAndExpressionLimits(){var m=model(20);JsonNode tree=m.path("roots").get(0);for(int i=1;i<20;i++)tree=join(tree,m.path("roots").get(i),"CROSS");m.withArray("roots").removeAll().add(tree);assertTrue(compile(m).path("valid").asBoolean(),compile(m).toString());}
 @Test void expressionsGroupingBindingsAndMissingDependencies(){var m=model(1);m.put("mode","summary");var summary=m.withObject("summary");var count=VisualQuery.expression("function").put("name","COUNT");count.putArray("args").add(VisualQuery.expression("star"));summary.withArray("outputs").addObject().put("id","count").put("alias","Total").set("expression",count);m.withArray("parameters").addObject().put("id","minimum").put("name","minimum").put("type","integer");var condition=VisualQuery.expression("binary").put("op",">");condition.set("left",col("s1"));condition.set("right",VisualQuery.expression("parameter").put("parameter","minimum"));m.set("where",condition);var having=condition.deepCopy();having.set("left",VisualQuery.expression("output").put("output","count"));summary.set("having",having);summary.withArray("order").addObject().put("direction","DESC").set("expression",VisualQuery.expression("output").put("output","count"));var result=compile(m);assertTrue(result.path("valid").asBoolean(),result.toString());assertEquals(2,result.path("bindings").size());assertTrue(result.path("sql").asText().contains("HAVING (COUNT(*) > ?)"));summary.withArray("outputs").removeAll();assertFalse(compile(m).path("valid").asBoolean());}
 @Test void validatesTypesCyclesAndDraftPrivacy(){var m=model(1);m.withArray("parameters").addObject().put("id","p").put("name","p").put("type","text").put("value","secret");m.put("parameterValues","secret");var saved=VisualQuery.validateDraft(m);assertFalse(saved.toString().contains("secret"));((ObjectNode)m.path("detail").path("outputs").get(0)).set("expression",VisualQuery.expression("output").put("output","o1"));assertFalse(compile(m).path("valid").asBoolean());m=model(1);((ObjectNode)m.path("sources").get(0)).put("reference","ITEM; DELETE FROM ITEM");assertFalse(compile(m).path("valid").asBoolean());}
 @Test void rowFiltersSurviveModeSwitchAndFunctionArgumentsAreTyped(){
  var m=model(1);var condition=VisualQuery.expression("binary").put("op",">");condition.set("left",VisualQuery.expression("output").put("output","o1"));condition.set("right",VisualQuery.expression("literal").put("type","integer").put("value",0));m.set("where",condition);
  var count=VisualQuery.expression("function").put("name","COUNT");count.putArray("args").add(VisualQuery.expression("star"));m.withObject("summary").withArray("outputs").addObject().put("id","total").set("expression",count);m.put("mode","summary");assertTrue(compile(m).path("valid").asBoolean(),compile(m).toString());
  m.put("mode","detail");m.putNull("where");var function=VisualQuery.expression("function").put("name","overloaded").put("schema","PUBLIC").put("catalogFunction",true);function.putArray("arguments").addObject().put("type","INTEGER").put("valueType","integer");function.putArray("args").add(VisualQuery.expression("literal").put("type","text").put("value","7"));((ObjectNode)m.path("detail").path("outputs").get(0)).set("expression",function);assertTrue(compile(m).path("sql").asText().contains("CAST('7' AS INTEGER)"),compile(m).toString());((ObjectNode)function.path("arguments").get(0)).put("type","INTEGER); DELETE FROM ITEM");assertFalse(compile(m).path("valid").asBoolean());
 }
 @Test void h2CompileRunExplainAndLosslessImport()throws Exception{
  try(var profiles=new Profiles(root,new DbaTest.MemoryVault());var connections=new Connections(profiles);var jobs=new QueryJobs(connections,new DbaConfig(root,64L<<20,2,100,100,10),s->true)){
   String connection=profiles.put(null,new DbaTest().input()).path("id").asText();try(var c=connections.open(connection);var st=c.createStatement()){c.setAutoCommit(true);st.execute("CREATE TABLE ITEM(ID INT)");st.execute("INSERT INTO ITEM VALUES(1),(2)");}
   var query=compile(model(1));assertTrue(query.path("valid").asBoolean(),query.toString());var plan=HumanSqlTest.finish(jobs,"human",jobs.browserExplain("human",connection,query.path("sql").asText(),Profiles.JSON.createArrayNode(),""));assertEquals("complete",plan.path("state").asText(),plan.toString());assertEquals("h2",plan.path("result").path("engine").asText());assertFalse(plan.path("result").path("executed").asBoolean());assertFalse(plan.path("result").path("raw").path("rows").isEmpty());
   var nested=model(3);nested.withArray("roots").removeAll().add(join(VisualQueryImport.source("s1"),join(VisualQueryImport.source("s2"),VisualQueryImport.source("s3"),"INNER"),"LEFT"));String nestedSql=compile(nested).path("sql").asText();var roundTrip=HumanSqlTest.finish(jobs,"human",jobs.queryBuilder("human",connection,Profiles.JSON.createObjectNode().put("sql",nestedSql),false));assertTrue(roundTrip.path("result").path("editable").asBoolean(),roundTrip.toString());var recovered=roundTrip.path("result").path("visualModel");assertEquals("LEFT",recovered.path("roots").get(0).path("type").asText());assertEquals("INNER",recovered.path("roots").get(0).path("right").path("type").asText());
   var imported=HumanSqlTest.finish(jobs,"human",jobs.queryBuilder("human",connection,Profiles.JSON.createObjectNode().put("sql","SELECT ID FROM ITEM WHERE ID > ? ORDER BY ID"),false));assertTrue(imported.path("result").path("editable").asBoolean(),imported.toString());assertEquals(2,imported.path("result").path("visualModel").path("version").asInt());assertEquals(1,imported.path("result").path("visualModel").path("parameters").size());assertThrows(SecurityException.class,()->jobs.browserExplain("agent:a",connection,"SELECT ID FROM ITEM",Profiles.JSON.createArrayNode(),""));
  }
 }
}
