// Requires Playwright and an isolated BrowserFixture; no user browser profile is used.
const { chromium }=require('playwright');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const [base,jar,schema='']=process.argv.slice(2);
(async()=>{
  const browser=await chromium.launch({channel:'msedge',headless:true});
  // Closing an isolated test context should end its server session as well. Otherwise
  // the full suite legitimately exhausts the application's eight-session allowance.
  const newContext=browser.newContext.bind(browser);
  browser.newContext=async(...args)=>{const context=await newContext(...args),close=context.close.bind(context);let closing=false;
  context.close=async(...options)=>{
    if(closing)return;closing=true; // browser.newPage owns its context and closes it recursively.
    try{
      // Block new renewals, then verify logout against an exact cookie snapshot.
      // Page closure can drop requestfinished events and late responses can change the jar.
      await context.route(base+'/api/dba/bootstrap',route=>route.abort());
      await Promise.all(context.pages().map(page=>page.close()));
      for(let attempt=0;attempt<3;attempt++){
      const cookie=(await context.cookies(base)).map(c=>c.name+'='+c.value).join('; '),headers={Cookie:cookie};
      const r=await context.request.get(base+'/api/dba/session',{headers});
      if(r.ok()){
        const s=await r.json(),logout=await context.request.post(base+'/api/dba/logout',{headers:{...headers,Origin:base,'X-Dba-CSRF':s.csrf}});
        assert.equal(logout.status(),200,'Fixture logout must release its browser session');
        assert.equal((await context.request.get(base+'/api/dba/session',{headers})).status(),403,'The exact revoked fixture session must remain unauthorized');
      }
      if((await context.cookies(base)).map(c=>c.name+'='+c.value).join('; ')===cookie)break;
      assert.ok(attempt<2,'Fixture cookie kept changing after page closure');
      }
    }finally{await close(...options);}
  };return context;};
  try {
    if(process.env.DBA_BROWSER_SUITE==='driver-downloads'){await require('./browser-driver-downloads.cjs')(browser,base);return;}
    if(process.env.DBA_BROWSER_SUITE==='grid-cell'){await require('./browser-grid-cell.cjs')(browser,base);return;}
    if(process.env.DBA_BROWSER_SUITE==='grid-search'){await require('./browser-grid-search.cjs')(browser,base,jar);return;}
    if(process.env.DBA_BROWSER_SUITE==='editable-grid'){await require('./browser-editable-grid.cjs')(browser,base,jar);return;}
    if(process.env.DBA_BROWSER_SUITE==='grid-scroll'){await require('./browser-grid-scroll.cjs')(browser,base,jar);return;}
    if(process.env.DBA_BROWSER_SUITE==='native'){await require('./browser-native.cjs')(browser,base);return;}
    if(process.env.DBA_BROWSER_SUITE==='yolo'){await require('./browser-yolo.cjs')(browser,base,jar);return;}
    if(process.env.DBA_BROWSER_SUITE==='tree-context'){await require('./browser-tree-context.cjs')(browser,base);return;}
    if(process.env.DBA_BROWSER_SUITE==='approval-review'){await require('./browser-approval-review.cjs')(browser,base,jar);return;}
    if(process.env.DBA_BROWSER_SUITE==='approvals'){await require('./browser-approvals.cjs')(browser,base,jar);return;}
    if(process.env.DBA_BROWSER_SUITE==='catalog'){await require('./browser-catalog.cjs')(browser,base);return;}
    if(process.env.DBA_BROWSER_SUITE==='project-context'){await require('./browser-project-context.cjs')(browser,base,jar);return;}
    if(process.env.DBA_BROWSER_SUITE==='editor-pairing'){await require('./browser-editor-pairing.cjs')(browser,base);return;}
    if(process.env.DBA_BROWSER_SUITE==='view-query'){await require('./browser-view-query.cjs')(browser,base,jar,schema);return;}
    if(process.env.DBA_BROWSER_SUITE==='script-selection'){await require('./browser-script-selection.cjs')(browser,base,jar);return;}
    if(process.env.DBA_BROWSER_SUITE==='grid'){await require('./browser-grid-column-menu.cjs')(browser,base);await require('./browser-grid-refresh.cjs')(browser,base);await require('./browser-grid-controller.cjs')(browser,base);await require('./browser-table-tabs.cjs')(browser,base,jar);return;}
    if(process.env.DBA_BROWSER_SUITE==='grid-edit'){await require('./browser-grid-edit.cjs')(browser,base,jar);return;}
    if(process.env.DBA_BROWSER_SUITE==='object-designer'){await require('./browser-object-designer.cjs')(browser,base,jar);return;}
    if(process.env.DBA_BROWSER_SUITE==='workspace-toolbar'){await require('./browser-workspace-toolbar.cjs')(browser,base);return;}
    if(process.env.DBA_BROWSER_SUITE==='object-creation'){await require('./browser-object-creation.cjs')(browser,base,jar);return;}
    if(process.env.DBA_BROWSER_SUITE==='query-builder'){await require('./browser-query-geometry.cjs')(browser,base);await require('./browser-query-builder.cjs')(browser,base,jar);await require('./browser-query-lifecycle.cjs')(browser,base);return;}
    if(process.env.DBA_BROWSER_SUITE==='table-designer'){await require('./browser-table-designer.cjs')(browser,base,jar);return;}
    if(process.env.DBA_BROWSER_SUITE!=='core'){
    await require('./browser-tree-context.cjs')(browser,base);
    await require('./browser-workspace-toolbar.cjs')(browser,base);
    await require('./browser-script-selection.cjs')(browser,base,jar);
    await require('./browser-grid-column-menu.cjs')(browser,base);
    await require('./browser-grid-refresh.cjs')(browser,base);
    await require('./browser-grid-controller.cjs')(browser,base);
    await require('./browser-table-tabs.cjs')(browser,base,jar);
    await require('./browser-table-designer.cjs')(browser,base,jar);
    await require('./browser-view-query.cjs')(browser,base,jar,schema);
    await require('./browser-query-geometry.cjs')(browser,base);
    await require('./browser-query-builder.cjs')(browser,base,jar);
    await require('./browser-object-creation.cjs')(browser,base,jar);
    await require('./browser-object-designer.cjs')(browser,base,jar);
    await require('./browser-grid-edit.cjs')(browser,base,jar);
    }
    const page=await browser.newPage({viewport:{width:1440,height:960}}),errors=[];
    await page.addInitScript(()=>{window.showOpenFilePicker=undefined;window.showSaveFilePicker=undefined;});
    page.on('pageerror',e=>errors.push(e.message));
    await page.goto(base+'/dba');
    // Schema entries use table; objects below schema-level groups use sheet, not their columns.
    const treeIcons=await page.evaluate(async()=>{
      const {MetadataTreeView}=await import('/dba/metadata-tree.js');const tree=new MetadataTreeView({});
      return ['schemas','tables','views','indexes','functions','procedures','sequences','types','schema','relation','databases'].map(kind=>{
        const parent={key:kind,descriptor:{kind},parent:{descriptor:{kind:['tables','views','indexes','functions','procedures','sequences','types'].includes(kind)?'schema':'other'}},profile:{id:'icon-test'},children:[],container:document.createElement('div')};
        tree.append(parent,{key:'child',kind:'item',name:'Child',branch:true});
        const icon=parent.container.querySelector('.metadata-icon');return {name:icon.dataset.lucide??null,rect:icon.querySelector('rect')?.getAttribute('width'),path:icon.querySelector('path').getAttribute('d'),hidden:icon.getAttribute('aria-hidden')};
      });
    });
    assert.deepEqual(treeIcons.map(i=>i.name),['table','sheet','sheet','sheet','sheet','sheet','sheet','sheet',null,null,'database']);
    assert.equal(treeIcons[0].path,'M12 3v18M3 9h18M3 15h18');assert.equal(treeIcons[1].path,'M3 9h18M3 15h18M9 9v12M15 9v12');
    for(const icon of treeIcons.slice(0,2)){assert.equal(icon.rect,'18');assert.equal(icon.hidden,'true');}
    assert.equal(await page.locator(' #toolbar-brand #appname').getAttribute('href'),'/', 'The DBA brand returns to the graph page');
    const counterpartLink=page.locator('#toolbar-brand #counterpart-new-tab');assert.equal(await counterpartLink.getAttribute('href'),'/');assert.equal(await counterpartLink.getAttribute('target'),'_blank');assert.equal(await counterpartLink.getAttribute('rel'),'noopener');assert.equal(await counterpartLink.getAttribute('aria-label'),'Open code graph visualization in a new tab');assert.equal(await counterpartLink.locator('svg').count(),1);
    page.on('dialog',d=>d.accept(d.type()==='prompt'?d.defaultValue():undefined));
    await page.waitForFunction(()=>document.querySelector('#connection-count').textContent.includes('connection'));
    assert.equal(await page.locator('#login-dialog').count(),0);
    assert.equal(await page.locator('.notice').count(),0,'Full-width notice is removed');
    assert.equal(await page.locator('#toolbar, #ddl, #ddl-dialog, #execution-target').count(),0,'Script toolbar and DDL UI are removed');
    assert.equal(await page.locator('#file-save').isDisabled(),true);assert.equal(await page.locator('#file-save-as').isDisabled(),true);
    const fullToolbar=await page.locator('#workspace-toolbar').boundingBox(),layout=await page.locator('#layout').boundingBox();
    assert.equal(fullToolbar.x,layout.x);assert.equal(fullToolbar.width,layout.width);assert.ok(fullToolbar.y+fullToolbar.height<=layout.y);
    assert.equal(fullToolbar.height,36,'The workspace toolbar is approximately 30% shorter');const agentAccessBox=await page.locator('#workspace-settings').boundingBox();assert.equal(agentAccessBox.height,30);assert.ok(agentAccessBox.x>fullToolbar.x+fullToolbar.width/2);assert.ok(Math.abs(agentAccessBox.x+agentAccessBox.width-(fullToolbar.x+fullToolbar.width-8))<2,'Settings is right-aligned in toolbar');assert.ok(Math.abs((agentAccessBox.y+agentAccessBox.height/2)-(fullToolbar.y+fullToolbar.height/2))<1,'Settings is vertically centered');assert.equal(await page.locator('#workspace-toolbar-actions').evaluate(e=>getComputedStyle(e).overflowX),'auto');
    assert.equal(await page.locator('#file-tools button').count(),4);
    for(const id of ['new-tab','file-open','file-save','file-save-as','run','explain','stop','script-settings','toggle-server-output','toggle-execution-log','toggle-sql-variables']){
      const b=page.locator('#'+id);assert.equal(await b.textContent(),'');assert.equal(await b.locator('svg').count(),1);assert.ok(await b.getAttribute('title'));assert.ok(await b.getAttribute('aria-label'));
    }
    for(const id of ['new-tab','file-open','file-save','file-save-as']){const b=await page.locator('#'+id).boundingBox(),svg=await page.locator('#'+id+' svg').boundingBox();assert.deepEqual([b.width,b.height],[30,30]);assert.deepEqual([svg.width,svg.height],[16,16]);}
    await page.locator('#new-tab').click();assert.equal(await page.locator('#file-save').isDisabled(),false);
    await page.waitForFunction(()=>document.querySelector('#sql-line-numbers').textContent==='1');
    assert.equal(await page.locator('#variables, #output-bar').count(),0,'Obsolete execution settings and output header are removed');
    assert.equal(await page.locator('#output').evaluate(e=>e.firstElementChild.id),'result-tabs','Output tabs are always the first output element');
    const workspaceDivider=page.locator('#editor-output-divider');assert.equal(await workspaceDivider.getAttribute('role'),'separator');assert.equal(await workspaceDivider.getAttribute('aria-orientation'),'horizontal');
    const dividerBox=await workspaceDivider.boundingBox(),editorBeforeDrag=await page.locator('#script-editor').boundingBox(),outputBeforeDrag=await page.locator('#output').boundingBox();await page.mouse.move(dividerBox.x+dividerBox.width/2,dividerBox.y+dividerBox.height/2);await page.mouse.down();await page.mouse.move(dividerBox.x+dividerBox.width/2,dividerBox.y+dividerBox.height/2+60);await page.mouse.up();const editorAfterDrag=await page.locator('#script-editor').boundingBox(),outputAfterDrag=await page.locator('#output').boundingBox();assert.ok(editorAfterDrag.height>editorBeforeDrag.height+45,'Dragging the divider grows the editor');assert.ok(outputAfterDrag.height<outputBeforeDrag.height-45,'Dragging the divider shrinks the output');await workspaceDivider.focus();const editorBeforeKey=await page.locator('#script-editor').boundingBox();await workspaceDivider.press('ArrowUp');assert.ok((await page.locator('#script-editor').boundingBox()).height<editorBeforeKey.height,'The divider supports keyboard resizing');assert.ok(Number(await workspaceDivider.getAttribute('aria-valuenow'))>10);
    const gutter=page.locator('#sql-gutter');
    assert.equal(await page.locator('#sql').getAttribute('wrap'),'off');assert.equal(await gutter.getAttribute('aria-hidden'),'true');
    const gutterBox=await gutter.boundingBox(),initialRail=await page.locator('#execution-rail').boundingBox(),initialEditor=await page.locator('#sql').boundingBox();
    assert.equal(initialRail.width,38,'The execution rail is approximately 30% narrower');assert.equal(initialRail.x+initialRail.width,gutterBox.x);assert.equal(gutterBox.x+gutterBox.width,initialEditor.x);
    const railIds=['run','explain','stop','script-settings','toggle-server-output','toggle-execution-log','toggle-sql-variables'];for(const id of railIds){const b=await page.locator('#'+id).boundingBox(),svg=await page.locator('#'+id+' svg').boundingBox();assert.deepEqual([b.width,b.height],[30,30]);assert.deepEqual([svg.width,svg.height],[16,16]);}
    assert.deepEqual(await page.locator('#execution-rail .rail-bottom').evaluate(e=>[...e.children].map(child=>child.id||child.className)),['script-settings','rail-divider','toggle-server-output','toggle-execution-log','toggle-sql-variables']);assert.equal(await page.locator('.rail-divider').getAttribute('role'),'separator');assert.equal(await page.locator('.rail-divider').innerText(),'…');assert.equal(await page.locator('.rail-divider button').count(),0);
    const initialRun=await page.locator('#run').boundingBox(),initialStop=await page.locator('#stop').boundingBox(),scriptSettingsBox=await page.locator('#script-settings').boundingBox(),variablesToggleBox=await page.locator('#toggle-sql-variables').boundingBox();assert.ok(initialRun.y<initialStop.y&&initialStop.y< scriptSettingsBox.y);assert.ok(Math.abs(variablesToggleBox.y+variablesToggleBox.height-(initialRail.y+initialRail.height-6))<2,'Additional controls are aligned to the bottom');
    for(const id of ['toggle-server-output','toggle-execution-log','toggle-sql-variables'])assert.equal(await page.locator('#'+id).getAttribute('aria-pressed'),'false');
    const serverOutput=page.locator('#toggle-server-output');await serverOutput.hover();const hoverStyle=await serverOutput.evaluate(e=>{const s=getComputedStyle(e);return[s.backgroundColor,s.borderTopColor]});await page.locator('#sql').hover();await serverOutput.click();await page.locator('#sql').hover();assert.equal(await serverOutput.getAttribute('aria-pressed'),'true');assert.deepEqual(await serverOutput.evaluate(e=>{const s=getComputedStyle(e);return[s.backgroundColor,s.borderTopColor]}),hoverStyle,'A pressed placeholder has the same styling as hover');assert.deepEqual(await page.locator('#result-tabs .result-select').allTextContents(),['Server output']);await page.locator('#toggle-execution-log').focus();await page.locator('#toggle-execution-log').press('Space');assert.equal(await page.locator('#toggle-execution-log').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#toggle-execution-log').evaluate(e=>getComputedStyle(e).outlineStyle),'solid','Keyboard focus remains visible');await page.locator('#toggle-sql-variables').click();assert.equal(await page.locator('#toggle-sql-variables').getAttribute('aria-pressed'),'true');assert.deepEqual(await page.locator('#result-tabs .result-select').allTextContents(),['Server output','Execution log','SQL variables'],'Enabled auxiliary tabs follow Data Grid tabs in rail order');assert.equal(await page.locator('#result-tabs .result-close').count(),3);await page.locator('#result-tabs .result-close').nth(2).click();assert.equal(await page.locator('#toggle-sql-variables').getAttribute('aria-pressed'),'false','Closing an auxiliary output tab turns off its rail toggle');assert.deepEqual(await page.locator('#result-tabs .result-select').allTextContents(),['Server output','Execution log']);await page.locator('#toggle-sql-variables').click();await page.locator('#script-settings').click();assert.match(await page.locator('#toast').innerText(),/reserved for a future update/);
    await page.locator('#sql').fill('SELECT restored_first');await page.locator('#new-tab').click();for(const id of ['toggle-server-output','toggle-execution-log','toggle-sql-variables'])assert.equal(await page.locator('#'+id).getAttribute('aria-pressed'),'false','A new Script tab starts with independent off state');assert.equal(await page.locator('#result-tabs').isHidden(),true);await page.locator('#sql').fill('SELECT restored_active');await page.locator('#toggle-sql-variables').click();await workspaceDivider.focus();await workspaceDivider.press('ArrowDown');const restoredDivider=await workspaceDivider.getAttribute('aria-valuenow');await page.waitForFunction(async()=>{const response=await fetch('/api/dba/workspace');if(!response.ok)return false;const state=await response.json();return state.tabs?.length===2&&state.tabs[1]?.sql==='SELECT restored_active'&&state.active===state.tabs[1].id;});await page.reload();await page.waitForFunction(()=>document.querySelector('#connection-count').textContent.includes('connection')&&document.querySelectorAll('#tabs .tab').length===2);assert.equal(await page.locator('#sql').inputValue(),'SELECT restored_active','The active Script and unsaved text survive refresh');assert.equal(await page.locator('#tabs .tab.active').evaluate(e=>e===document.querySelectorAll('#tabs .tab')[1]),true,'The same ordered Script tab remains active');assert.equal(await page.evaluate(()=>document.activeElement.id),'sql');assert.equal(await workspaceDivider.getAttribute('aria-valuenow'),restoredDivider,'The active Script divider position survives refresh');assert.equal(await page.locator('#toggle-sql-variables').getAttribute('aria-pressed'),'true');await page.locator('#tabs .tab').first().locator('button').first().click();assert.equal(await page.locator('#sql').inputValue(),'SELECT restored_first','Script tab order and each unsaved buffer survive refresh');for(const id of ['toggle-server-output','toggle-execution-log','toggle-sql-variables'])assert.equal(await page.locator('#'+id).getAttribute('aria-pressed'),'true','Restored Script output state remains independent');await page.locator('#tabs .tab[data-type=script]').nth(1).locator('.close').click();assert.deepEqual(await page.locator('#result-tabs .result-select').allTextContents(),['Server output','Execution log','SQL variables']);
    const scriptEditor=page.locator('#script-editor');await scriptEditor.evaluate(e=>{e.style.height='170px';e.style.flexBasis='170px';});const compactOverflow=await page.locator('#execution-rail').evaluate(e=>({vertical:e.scrollHeight>e.clientHeight,horizontal:getComputedStyle(e).overflowX}));assert.deepEqual(compactOverflow,{vertical:true,horizontal:'hidden'});await page.locator('#execution-rail').evaluate(e=>e.scrollTop=e.scrollHeight);const shortRail=await page.locator('#execution-rail').boundingBox(),shortLast=await page.locator('#toggle-sql-variables').boundingBox();assert.ok(shortLast.y>=shortRail.y&&shortLast.y+shortLast.height<=shortRail.y+shortRail.height+1,'A short rail scrolls to its bottom controls without overlap');await scriptEditor.evaluate(e=>{e.style.height='';e.style.flexBasis='';});await page.locator('#execution-rail').evaluate(e=>e.scrollTop=0);
    await page.locator('#sql').fill('SELECT 1;\r\n\r\n');await page.waitForFunction(()=>document.querySelector('#sql-line-numbers').textContent==='1\n2\n3');
    await page.locator('#sql').fill('SELECT '+ 'long_column_name, '.repeat(250)+'last_column;');
    await page.waitForFunction(()=>document.querySelector('#sql-line-numbers').textContent==='1');
    const noWrap=await page.locator('#sql').evaluate(e=>({wide:e.scrollWidth>e.clientWidth,tall:e.scrollHeight>e.clientHeight}));assert.deepEqual(noWrap,{wide:true,tall:false});
    await page.locator('#sql').fill(Array.from({length:120},(_,i)=>'SELECT '+i+'; -- '+'long SQL line '.repeat(20)).join('\n'));
    await page.locator('#sql').evaluate(e=>{e.scrollTop=850;e.scrollLeft=350;e.dispatchEvent(new Event('scroll'));});
    await page.waitForFunction(()=>{const input=document.querySelector('#sql'),numbers=document.querySelector('#sql-line-numbers'),style=getComputedStyle(input),first=Number(numbers.textContent.split('\n')[0]);return first>20&&Math.abs(numbers.getBoundingClientRect().top-(input.getBoundingClientRect().top+parseFloat(style.paddingTop)+(first-1)*parseFloat(style.lineHeight)-input.scrollTop))<1;});
    async function assertGutterAlignment(){const alignment=await page.evaluate(()=>{const sql=document.querySelector('#sql'),numbers=document.querySelector('#sql-line-numbers'),style=getComputedStyle(sql),first=Number(numbers.textContent.split('\n')[0]);return {actual:numbers.getBoundingClientRect().top,expected:sql.getBoundingClientRect().top+parseFloat(style.paddingTop)+(first-1)*parseFloat(style.lineHeight)-sql.scrollTop,count:document.querySelector('#sql-gutter').dataset.lineCount,rendered:numbers.textContent.split('\n').length};});assert.ok(Math.abs(alignment.actual-alignment.expected)<1,JSON.stringify(alignment));assert.equal(alignment.count,'120');assert.ok(alignment.rendered<40,'Gutter rendering stays bounded');}
    await assertGutterAlignment();await page.setViewportSize({width:720,height:800});await page.waitForTimeout(100);await assertGutterAlignment();
    await page.setViewportSize({width:1440,height:960});await page.waitForTimeout(100);await page.screenshot({path:'code-graph-dba/target/script-line-numbers.png'});
    await page.locator('#new-tab').click();await page.waitForFunction(()=>document.querySelector('#sql-line-numbers').textContent==='1');
    await page.locator('.tab.active .close').click();await page.waitForFunction(()=>document.querySelector('#sql-gutter').dataset.lineCount==='120');
    await page.locator('#script-file-input').setInputFiles({name:'many-lines.sql',mimeType:'text/plain',buffer:Buffer.from('\n'.repeat(9999))});
    await page.waitForFunction(()=>document.querySelector('#sql-gutter').dataset.lineCount==='10000');await page.locator('#sql').evaluate(e=>{e.scrollTop=e.scrollHeight;e.dispatchEvent(new Event('scroll'));});
    await page.waitForFunction(()=>document.querySelector('#sql-line-numbers').textContent.endsWith('10000'));assert.ok((await page.locator('#sql-line-numbers').textContent()).split('\n').length<40);
    await page.locator('#sql').fill('');await page.waitForFunction(()=>document.querySelector('#sql-line-numbers').textContent==='1');
    await page.locator('#sql').press('Enter');await page.waitForFunction(()=>document.querySelector('#sql-gutter').dataset.lineCount==='2');await page.locator('#sql').press('Backspace');await page.waitForFunction(()=>document.querySelector('#sql-line-numbers').textContent==='1');
    await page.locator('#sql').fill('SELECT value');await page.locator('#sql').evaluate(e=>e.setSelectionRange(7,7));await page.locator('#sql').press('Tab');assert.equal(await page.locator('#sql').inputValue(),'SELECT \tvalue');assert.equal(await page.evaluate(()=>document.activeElement.id),'sql');
    await page.locator('#sql').fill('one\n  two\n\tthree\nfour');await page.locator('#sql').evaluate(e=>e.setSelectionRange(0,17));await page.locator('#sql').press('Tab');assert.equal(await page.locator('#sql').inputValue(),'\tone\n\t  two\n\t\tthree\nfour','Tab indents every selected line without deleting text');let selected=await page.locator('#sql').evaluate(e=>[e.selectionStart,e.selectionEnd]);assert.ok(selected[1]>selected[0],'multi-line selection remains selected after indent');await page.locator('#sql').press('Shift+Tab');assert.equal(await page.locator('#sql').inputValue(),'one\n  two\n\tthree\nfour','Shift+Tab outdents every selected line');selected=await page.locator('#sql').evaluate(e=>[e.selectionStart,e.selectionEnd]);assert.ok(selected[1]>selected[0],'multi-line selection remains selected after outdent');assert.equal(await page.evaluate(()=>document.activeElement.id),'sql');
    await page.locator('.tab.active .close').click();await page.waitForFunction(()=>document.querySelector('#sql-gutter').dataset.lineCount==='120');
    if(!schema)assert.equal(await page.locator('#run').isDisabled(),true,'A script can exist without any connection');
    await page.locator('.tab.active .close').click();assert.equal(await page.locator('#file-save').isDisabled(),true);
    if(!schema){const initialConnectionCount=await page.locator('.connection-row').count();await page.locator('#add').click();await page.locator('#connection-editor').waitFor({state:'visible'});
    const databaseNames=await page.locator('.database-tile strong').allTextContents();assert.ok(databaseNames.length>40);assert.equal(databaseNames.pop(),'Custom');assert.deepEqual(databaseNames,[...databaseNames].sort((a,b)=>a.toLowerCase()<b.toLowerCase()?-1:a.toLowerCase()>b.toLowerCase()?1:0));
    await page.screenshot({path:'code-graph-dba/target/connection-picker.png'});
    await page.locator('#ce-search').fill('custom');assert.equal(await page.locator('.database-tile').count(),1);
    await page.locator('[data-database=custom]').click();
    for(const id of ['name','url','username'])assert.equal(await page.locator('#ce-'+id).inputValue(),'');
    await page.locator('#ce-name').fill('Browser fixture');await page.locator('#ce-url').fill('jdbc:h2:mem:browser_fixture');await page.locator('#ce-username').fill('sa');
    await page.getByRole('tab',{name:'Driver',exact:true}).click();
    for(const id of ['groupId','artifactId','version','driverClass','jars'])assert.equal(await page.locator('#ce-'+id).inputValue(),'');
    await page.locator('#ce-driverClass').fill('org.h2.Driver');await page.locator('#ce-jars').fill(jar);
    await page.getByRole('button',{name:'Inspect / discover classes',exact:true}).click();
    await page.waitForFunction(()=>!document.querySelector('#ce-test').disabled);
    await page.locator('#ce-test').click();await page.locator('#connection-test-result').waitFor({state:'visible'});
    const testResultBody=await page.locator('#test-result-body').innerText();assert.equal(await page.locator('#test-result-title').innerText(),'Connection successful',testResultBody);assert.match(testResultBody,/SELECT H2VERSION\(\)/);assert.equal(await page.locator('#test-result-body td').count(),1);
    assert.equal(await page.locator('.connection-row').count(),initialConnectionCount,'Test must not save a connection');
    await page.screenshot({path:'code-graph-dba/target/connection-test-success.png'});
    await page.locator('#test-result-close').click();await page.locator('#ce-save').click();
    await page.locator('#connection-editor').waitFor({state:'hidden'});
    const treeRoot=page.locator('.connection-row').first();assert.equal(await treeRoot.locator('.connection-address').innerText(),'In-memory');assert.equal(await treeRoot.locator('.connection-icon').count(),1);
    assert.equal(await treeRoot.getAttribute('data-color'),'transparent');
    await treeRoot.locator(':scope > .connection-title > .connection-more').click();await page.getByRole('menuitem',{name:'Edit Connection',exact:true}).click();assert.equal(await page.locator('#ce-color-preview').getAttribute('data-color'),'transparent');
    let colorTests=0;const countColorTests=request=>{if(request.url().endsWith('/setup/draft-test'))colorTests++;};page.on('request',countColorTests);
    await page.getByRole('button',{name:'Red connection shade',exact:true}).click();assert.equal(await page.locator('#ce-save').isEnabled(),true,'Color-only edits do not require testing database connectivity');await page.locator('#ce-save').click();await page.locator('#connection-editor').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('.connection-row')?.dataset.color==='#ed6363');assert.equal(colorTests,0);page.off('request',countColorTests);
    await treeRoot.locator(':scope > .connection-title > .connection-more').click();await page.getByRole('menuitem',{name:'Edit Connection',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Red connection shade',exact:true}).getAttribute('aria-pressed'),'true');await page.locator('#ce-color').fill('#2468ac');await page.locator('#ce-save').click();await page.locator('#connection-editor').waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelector('.connection-row')?.dataset.color==='#2468ac');
    await treeRoot.locator(':scope > .connection-title > .connection-more').click();assert.equal(await page.getByRole('menuitem',{name:'Connect',exact:true}).isEnabled(),true);assert.equal(await page.getByRole('menuitem',{name:'Disconnect',exact:true}).isDisabled(),true);await page.getByRole('menuitem',{name:'Connect',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.connection-row')?.dataset.connected==='true');
    await treeRoot.locator(':scope > .connection-title > .connection-more').click();assert.equal(await page.getByRole('menuitem',{name:'Connect',exact:true}).isDisabled(),true);assert.equal(await page.getByRole('menuitem',{name:'Invalidate/Reconnect',exact:true}).isEnabled(),true);await page.getByRole('menuitem',{name:'Invalidate/Reconnect',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('Connected'));
    await treeRoot.locator('.connection-toggle').click();await page.waitForFunction(()=>document.querySelector('.connection-row > .children .node'));assert.equal(await treeRoot.getAttribute('aria-expanded'),'true');await treeRoot.locator('.connection-toggle').click();assert.equal(await treeRoot.getAttribute('aria-expanded'),'false');
    await treeRoot.locator(':scope > .connection-title > .connection-more').click();await page.getByRole('menuitem',{name:'Disconnect',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.connection-row')?.dataset.connected==='false');assert.equal(await treeRoot.getAttribute('aria-expanded'),'false');
    await page.locator('.connection-more').first().click();await page.getByRole('menuitem',{name:'Edit Connection',exact:true}).click();await page.getByRole('tab',{name:'Driver',exact:true}).click();await page.locator('#ce-driverClass').fill('missing.Driver');await page.locator('#ce-test').click();await page.locator('#connection-test-result').waitFor({state:'visible'});assert.equal(await page.locator('#test-result-title').innerText(),'Connection test failed');assert.match(await page.locator('#test-result-body').innerText(),/ClassNotFoundException/);await page.locator('#test-result-close').click();await page.locator('#ce-close').click();}
    // Lazy vendor hierarchy: refresh rebuilds descendants without losing expanded paths.
    const metadataRoot=page.locator('.connection-row').first();
    const assertNameKeepsExpansion=async(row,label,expanded)=>{await label.click();assert.equal(await row.getAttribute('aria-expanded'),String(expanded),'Name click does not toggle expansion');await label.dblclick();assert.equal(await row.getAttribute('aria-expanded'),String(expanded),'Name double-click does not toggle expansion');};
    const rootName=metadataRoot.locator(':scope > .connection-title .connection-select');
    await assertNameKeepsExpansion(metadataRoot,rootName,false);
    await metadataRoot.locator(':scope > .connection-title .connection-toggle').click();
    await assertNameKeepsExpansion(metadataRoot,rootName,true);
    const branch=(kind,name)=>metadataRoot.locator('.metadata-node[data-kind="'+kind+'"]').filter({has:page.locator(':scope > .metadata-title > .metadata-name').filter({hasText:new RegExp('^'+name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$')})}).first();
    const expand=async(kind,name)=>{
      const row=branch(kind,name),label=row.locator(':scope > .metadata-title > .metadata-name'),chevron=row.locator(':scope > .metadata-title > .metadata-toggle');
      await assertNameKeepsExpansion(row,label,false);
      await chevron.click();
      await page.waitForFunction(({kind,name})=>{const row=[...document.querySelectorAll('.metadata-node')].find(n=>n.dataset.kind===kind&&n.dataset.name===name);return row?.getAttribute('aria-expanded')==='true'&&!row.hasAttribute('aria-busy');},{kind,name});
      await assertNameKeepsExpansion(row,label,true);
      await chevron.click();assert.equal(await row.getAttribute('aria-expanded'),'false','Chevron collapses branch');
      await chevron.click();assert.equal(await row.getAttribute('aria-expanded'),'true','Chevron expands branch');
      await label.focus();await label.press('ArrowLeft');assert.equal(await row.getAttribute('aria-expanded'),'false','Keyboard disclosure remains accessible');await label.press('ArrowRight');assert.equal(await row.getAttribute('aria-expanded'),'true');
      return row;
    };
    if(schema){await expand('databases','Databases');await expand('database','postgres');}
    await expand('schemas','Schemas');const schemaBranch=await expand('schema',schema||'PUBLIC');await expand('tables','Tables');
    const groupLabels=await schemaBranch.locator(':scope > .metadata-children > .metadata-node > .metadata-title > .metadata-name').allTextContents();assert.ok(groupLabels.includes('Views')&&groupLabels.includes('Indexes')&&groupLabels.includes('Sequences'));assert.deepEqual(groupLabels,[...groupLabels].sort((a,b)=>a.toLowerCase()<b.toLowerCase()?-1:a.toLowerCase()>b.toLowerCase()?1:0),'Schema branches are alphabetical');
    if(schema){const relation=branch('relation','items');await relation.locator(':scope > .metadata-title > .metadata-toggle').click();const columns=relation.locator('.metadata-node[data-kind="table_columns"]');await columns.locator(':scope > .metadata-title > .metadata-toggle').click();await columns.locator(':scope > .metadata-children > .metadata-node').first().waitFor();assert.ok(await columns.locator(':scope > .metadata-children > .metadata-node').count()>0);assert.equal(await columns.locator(':scope > .metadata-children > .metadata-node > .metadata-title > .metadata-toggle').count(),0,'Only column leaves have no chevron');}
    await schemaBranch.locator(':scope > .metadata-title > .metadata-actions').click();await page.getByRole('menuitem',{name:'Refresh metadata',exact:true}).click();await page.waitForFunction(name=>{const row=[...document.querySelectorAll('.metadata-node')].find(n=>n.dataset.kind==='schema'&&n.dataset.name===name);return row&&!row.hasAttribute('aria-busy');},schema||'PUBLIC');assert.equal(await branch('tables','Tables').getAttribute('aria-expanded'),'true','Expanded Tables survives schema refresh');
    if(schema)assert.equal(await branch('relation','items').getAttribute('aria-expanded'),'true','Expanded descendants survive ancestor refresh');
    if(schema){
      assert.equal(await branch('database','postgres').locator(':scope > .metadata-title > svg[data-lucide=database]').count(),1);
      const menuFor=async row=>{await row.locator(':scope > .metadata-title > .metadata-actions').scrollIntoViewIfNeeded();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await row.locator(':scope > .metadata-title > .metadata-actions').click();await page.waitForFunction(()=>!document.querySelector('[role=menu] [title="Copy object name"]')?.disabled&&!!document.querySelector('[role=menu] [title="Copy object name"]')).catch(async e=>{throw new Error(e.message+' Menu: '+await page.locator('[role=menu]').evaluateAll(nodes=>nodes.map(n=>n.outerHTML).join(''))+' Notice: '+await page.locator('#toast').innerText());});const menu=page.locator('[role=menu]:visible');const labels=await menu.getByRole('menuitem').allTextContents();assert.deepEqual(labels.slice(0,2),['New','Delete']);assert.ok(labels.includes('Open object tab'));assert.deepEqual(labels.slice(-3),['Copy','Rename','Refresh metadata']);assert.equal(await menu.locator(':scope > button > svg[data-lucide]').count(),labels.length);assert.equal(await menu.locator(':scope > [role=separator]').count(),2);};
      await menuFor(branch('database','postgres'));assert.equal(await page.getByRole('menuitem',{name:'Rename',exact:true}).isDisabled(),true,'Catalog databases are not renamed through the tree');await page.keyboard.press('Escape');
      const target=branch('relation','menu_target');await menuFor(target);
      await page.context().grantPermissions(['clipboard-read','clipboard-write'],{origin:base});await page.getByRole('menuitem',{name:'Copy',exact:true}).click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'menu_target');
      let deletes=0;const onDelete=r=>{if(r.url().endsWith('/metadata/object/action')&&r.postDataJSON()?.action==='delete')deletes++;};page.on('request',onDelete);
      await menuFor(target);await page.getByRole('menuitem',{name:'Delete',exact:true}).click();await page.locator('#tree-object-dialog').waitFor({state:'visible'});assert.equal(deletes,0,'Opening destructive confirmation does not execute');await page.locator('#tree-object-cancel').click();assert.equal(deletes,0);assert.equal(await target.count(),1);
      await menuFor(target);await page.getByRole('menuitem',{name:'Delete',exact:true}).click();await page.locator('#tree-object-dialog').getByRole('checkbox').check();await page.locator('#tree-object-confirm').click();await page.locator('#tree-object-error').waitFor({state:'visible'});assert.match(await page.locator('#tree-object-error').innerText(),/menu_view/);assert.equal(await target.count(),1,'Database rejection preserves the node');await page.locator('#tree-object-close').click();
      await expand('views','Views');const view=branch('relation','menu_view');await menuFor(view);await page.getByRole('menuitem',{name:'Delete',exact:true}).click();await page.locator('#tree-object-dialog').getByRole('checkbox').check();await page.locator('#tree-object-confirm').click();await view.waitFor({state:'detached'});
      await menuFor(target);await page.getByRole('menuitem',{name:'Rename',exact:true}).click();await page.locator('#tree-object-name').fill('menu_renamed');await page.locator('#tree-object-confirm').click();const renamed=branch('relation','menu_renamed');await renamed.waitFor({state:'visible'});assert.equal(await target.count(),0);
      await menuFor(renamed);await page.getByRole('menuitem',{name:'Delete',exact:true}).click();await page.locator('#tree-object-dialog').getByRole('checkbox').check();await page.locator('#tree-object-confirm').click();await renamed.waitFor({state:'detached'});page.off('request',onDelete);assert.equal(deletes,3);
      assert.equal(await branch('relation','items').getAttribute('aria-expanded'),'true','Object operations preserve unrelated expanded siblings');
    }
    await page.screenshot({path:'code-graph-dba/target/metadata-tree-'+(schema?'postgres':'h2')+'.png'});
    await metadataRoot.locator(':scope > .connection-title .connection-toggle').click();
    await page.locator('.connection-more').first().click();await page.getByRole('menuitem',{name:'SQL Editor',exact:true}).click();await page.getByRole('menuitem',{name:'New SQL script',exact:true}).click();
    const activeConnection=page.locator('.tab.active .tab-connection');
    const initialConnectionWidth=(await activeConnection.boundingBox()).width;assert.equal(await activeConnection.evaluate(e=>getComputedStyle(e).appearance),'none','The compact connection selector has no visible caret');assert.ok(initialConnectionWidth<150,'The selected connection name determines the compact selector width');
    const rail=await page.locator('#execution-rail').boundingBox(),sqlBox=await page.locator('#sql').boundingBox();
    assert.ok(rail.x+rail.width<=sqlBox.x);assert.equal(rail.y,sqlBox.y);
    const runBox=await page.locator('#run').boundingBox(),explainBox=await page.locator('#explain').boundingBox(),cancelBox=await page.locator('#stop').boundingBox();
    assert.equal(runBox.x,explainBox.x);assert.equal(runBox.x,cancelBox.x);assert.ok(runBox.y<explainBox.y&&explainBox.y<cancelBox.y);
    await page.route('**/api/dba/query/execute',async route=>{await new Promise(r=>setTimeout(r,700));await route.continue();});
    await page.locator('#sql').fill("SELECT 42 AS ANSWER, 'sample' AS LABEL");
    await page.locator('#toggle-server-output').click();
    await page.locator('#run').click();
    assert.equal(await activeConnection.isDisabled(),true,'The executing tab cannot be retargeted during submission');
    assert.equal(await page.locator('#run').isDisabled(),true);
    await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('1 rows')||!document.querySelector('#error').hidden);
    assert.equal(await page.locator('#error').isVisible(),false,await page.locator('#error').textContent());
    assert.deepEqual(await page.locator('#result-tabs .result-select').allTextContents(),['Result 1','Server output']);assert.equal(await page.locator('#result-tabs .result-select').first().getAttribute('aria-pressed'),'true','A completed script always selects its first Data Grid');assert.equal(await page.locator('#result-tabs .result-select').last().getAttribute('aria-pressed'),'false');await page.locator('#result-tabs .result-close').last().click();
    assert.match(await page.locator('#grid').innerText(),/42/);assert.equal(await page.locator('#grid .grid-row:not(.header) .row-number').first().innerText(),'1','Result rows have a left-side row number');
    let multiCancelled=false;await page.route(/\/api\/dba\/(?:query\/execute|jobs\/multi-results-fixture(?:\/cancel)?)$/,async route=>{const request=route.request(),url=request.url();if(url.includes('/query/execute'))await route.fulfill({json:{id:'multi-results-fixture'}});else if(url.endsWith('/cancel')){multiCancelled=true;await route.fulfill({json:{ok:true}});}else if(request.method()==='DELETE')await route.fulfill({json:{ok:true}});else{const columns=Array.from({length:16},(_,i)=>({id:'c'+(i+1),label:'COLUMN_'+(i+1),type:'VARCHAR'})),rows=Array.from({length:200},(_,row)=>columns.map((_,column)=>(row+1)+'-'+(column+1)));await route.fulfill({json:{state:multiCancelled?'cancelled':'complete',finished:1,result:{rowCount:201,affectedRows:1,statements:[{index:1,sql:'SELECT 11'},{index:2,sql:'SELECT 21'}],results:[{kind:'update',affectedRows:1,statementIndex:1},{kind:'rows',statementIndex:1,columns,rows},{kind:'rows',statementIndex:2,columns:[{id:'c1',label:'SECOND',type:'INTEGER'}],rows:[[21]]}]}}});}});
    await page.locator('#sql').fill('SELECT 11; SELECT 21;');await page.locator('#run').click();await page.waitForFunction(()=>document.querySelectorAll('#result-tabs .result-tab').length===2);
    assert.deepEqual(await page.locator('#result-tabs .result-select').allTextContents(),['Result 1','Result 2'],'Only row-producing results create data-grid tabs');assert.equal(await page.locator('#result-tabs .result-close').count(),2,'Every result tab has a close button');assert.deepEqual((await page.locator('#grid .row-number').allTextContents()).slice(0,3),['','1','2']);
    assert.equal(await page.locator('.grid-source-preview').inputValue(),'SELECT 11');await page.getByRole('button',{name:'Show complete result SQL'}).click();assert.equal(await page.locator('.sql-viewer textarea').inputValue(),'SELECT 11');assert.equal(await page.locator('.sql-resize').count(),8);const viewerBefore=await page.locator('.sql-viewer').boundingBox(),viewerHandle=await page.locator('.sql-resize.se').boundingBox();await page.mouse.move(viewerHandle.x+4,viewerHandle.y+4);await page.mouse.down();await page.mouse.move(viewerHandle.x+34,viewerHandle.y+24);await page.mouse.up();const viewerAfter=await page.locator('.sql-viewer').boundingBox();assert.ok(viewerAfter.width>viewerBefore.width&&viewerAfter.height>viewerBefore.height,'The SQL viewer resizes from a corner');await page.locator('.grid-filter-input').click();assert.equal(await page.locator('.sql-viewer').count(),0,'Clicking elsewhere closes the SQL viewer');await page.getByRole('button',{name:'Show complete result SQL'}).click();await page.keyboard.press('Escape');assert.equal(await page.locator('.sql-viewer').count(),0,'Escape closes the SQL viewer');
    await page.locator('.grid-filter-input').fill('status = 1');assert.equal(await page.locator('.grid-filter-input').getAttribute('rows'),'1');await page.getByRole('button',{name:'Expand SQL filter expression'}).click();assert.equal(await page.locator('.grid-filter-input').getAttribute('rows'),'5');assert.equal(await page.getByRole('button',{name:'Collapse SQL filter expression'}).count(),1);
    await page.getByRole('button',{name:'Choose filtering or ordering to remove'}).click();assert.deepEqual(await page.locator('.grid-action-menu button').allTextContents(),['Remove all filtering','Remove all orderings']);await page.locator('.grid-filter-input').click();assert.equal(await page.locator('.grid-action-menu').isHidden(),true);
    const initialHeaders=await page.locator('.data-column-header').allTextContents();await page.getByRole('button',{name:'Result Set Order/Filter Settings'}).click();const resultSettings=page.locator('.result-settings');assert.equal(await resultSettings.isVisible(),true);assert.deepEqual(await resultSettings.getByRole('tab').allTextContents(),['Columns','Custom']);await resultSettings.getByRole('tab',{name:'Custom'}).click();await page.keyboard.press('Escape');assert.equal(await resultSettings.isVisible(),true,'Escape does not dismiss Result Set settings');await resultSettings.getByRole('tab',{name:'Columns'}).click();await resultSettings.getByRole('button',{name:'Move COLUMN_1 down'}).click();await resultSettings.getByRole('button',{name:'Cancel'}).click();assert.deepEqual(await page.locator('.data-column-header').allTextContents(),initialHeaders,'Cancel discards modal column order');await page.getByRole('button',{name:'Result Set Order/Filter Settings'}).click();await resultSettings.getByRole('button',{name:'Move COLUMN_1 down'}).click();await resultSettings.getByRole('button',{name:'Ok'}).click();assert.deepEqual((await page.locator('.data-column-header').allTextContents()).slice(0,2),['COLUMN_2','COLUMN_1'],'Ok applies modal column order');await page.locator('.data-column-header').first().press('Alt+ArrowRight');assert.deepEqual((await page.locator('.data-column-header').allTextContents()).slice(0,2),['COLUMN_1','COLUMN_2'],'Keyboard column reordering applies immediately');await page.locator('.data-column-header').first().dragTo(page.locator('.data-column-header').nth(2));assert.deepEqual((await page.locator('.data-column-header').allTextContents()).slice(0,3),['COLUMN_2','COLUMN_3','COLUMN_1'],'Header dragging reorders columns directly');await page.getByRole('button',{name:'Result Set Order/Filter Settings'}).click();await resultSettings.locator('.column-order-item').first().dragTo(resultSettings.locator('.column-order-item').nth(2));await resultSettings.getByRole('button',{name:'Ok'}).click();assert.deepEqual((await page.locator('.data-column-header').allTextContents()).slice(0,3),['COLUMN_3','COLUMN_1','COLUMN_2'],'Modal dragging applies its draft order');
    const grid=page.locator('.data-grid-scroll'),overflow=await grid.evaluate(e=>({horizontal:e.scrollWidth>e.clientWidth,vertical:e.scrollHeight>e.clientHeight}));assert.deepEqual(overflow,{horizontal:true,vertical:true},'Large result sets scroll on both axes');const headerTop=(await page.locator('#grid .header').boundingBox()).y,cornerTop=(await page.locator('.row-number-corner').boundingBox()).y;await grid.evaluate(e=>{e.scrollLeft=e.scrollWidth;e.scrollTop=e.scrollHeight;e.onscroll?.();});await page.waitForTimeout(250);const visibleAtEnd=await page.locator('#grid .row-number').allTextContents();assert.equal(visibleAtEnd.at(-1),'200','Vertical scrolling reaches the final virtualized row: '+JSON.stringify(visibleAtEnd));const scrolled=await grid.evaluate(e=>({left:e.scrollLeft,top:e.scrollTop}));assert.ok(scrolled.left>0&&scrolled.top>0);assert.ok(Math.abs((await page.locator('#grid .header').boundingBox()).y-headerTop)<1,'Column headers remain visible while scrolling rows');assert.ok(Math.abs((await page.locator('.row-number-corner').boundingBox()).y-cornerTop)<1,'The blank row-number corner remains visible while scrolling rows');assert.ok(Math.abs((await page.locator('#grid .grid-row:not(.header) .row-number').last().boundingBox()).x-(await grid.boundingBox()).x)<2,'Row numbers remain visible while scrolling columns');await grid.evaluate(e=>{e.scrollLeft=0;e.scrollTop=0;e.onscroll?.();});await page.waitForFunction(()=>document.querySelector('#grid .grid-row:not(.header) .row-number')?.textContent==='1');
    const firstHeader=page.locator('.data-column-header').first(),resizeHandle=firstHeader.locator('.column-resize'),beforeColumn=await firstHeader.boundingBox(),beforeRow=await page.locator('#grid .grid-row:not(.header)').first().boundingBox();await resizeHandle.focus();await resizeHandle.press('ArrowRight');await resizeHandle.press('ArrowRight');const afterColumn=await firstHeader.boundingBox(),afterRow=await page.locator('#grid .grid-row:not(.header)').first().boundingBox();assert.equal(afterColumn.width,beforeColumn.width+20,'Arrow keys resize only the selected result column');assert.equal(afterRow.height,beforeRow.height,'Column resizing does not resize result rows');assert.equal(await resizeHandle.getAttribute('aria-valuenow'),String(beforeColumn.width+20));await page.locator('#result-tabs .result-select').nth(1).click();assert.deepEqual(await page.locator('#grid .row-number').allTextContents(),['','1']);assert.notEqual((await page.locator('.data-column-header').first().boundingBox()).width,afterColumn.width,'Each result keeps independent column widths');assert.equal(await page.locator('.grid-source-preview').inputValue(),'SELECT 21');await page.locator('#result-tabs .result-close').nth(1).click();assert.deepEqual(await page.locator('#result-tabs .result-select').allTextContents(),['Result 1'],'Closing a result removes only that result tab');assert.equal(await page.locator('#result-tabs').isVisible(),true,'A single retained result can still be closed');await page.locator('#result-tabs .result-close').click();assert.equal(await page.locator('#result-tabs').isHidden(),true);assert.match(await page.locator('#grid').innerText(),/Command completed/,'A non-row command shows its status without a data-grid tab');await page.unroute(/\/api\/dba\/(?:query\/execute|jobs\/multi-results-fixture(?:\/cancel)?)$/);
    assert.equal(await activeConnection.isDisabled(),false);await page.unroute('**/api/dba/query/execute');
    await page.locator('#sql').fill(schema?'select version();':'select H2VERSION();');await page.locator('#run').click();
    await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('1 rows')||!document.querySelector('#error').hidden);
    assert.equal(await page.locator('#error').isVisible(),false,await page.locator('#error').textContent());
    assert.match(await page.locator('#grid').innerText(),schema?/PostgreSQL/:/2\./,'Human SQL function returns database version');
    await page.locator('#toggle-server-output').click();assert.deepEqual(await page.locator('#result-tabs .result-select').allTextContents(),['Result 1','Server output'],'Data Grid tabs stay before enabled auxiliary tabs');assert.equal(await page.locator('#grid .output-placeholder strong').innerText(),'Server output');await page.locator('#result-tabs .result-close').last().click();assert.equal(await page.locator('#toggle-server-output').getAttribute('aria-pressed'),'false');assert.match(await page.locator('#grid').innerText(),schema?/PostgreSQL/:/2\./,'Closing the auxiliary tab restores the Data Grid');
    if(!schema){await page.locator('#sql').fill('SELECT 1 AS BEFORE; SELECT * FROM definitely_missing; SELECT 2 AS AFTER;');await page.locator('#run').click();await page.locator('#sql-error-decision').waitFor({state:'visible'});assert.match(await page.locator('#decision-message').textContent(),/DEFINITELY_MISSING/i);assert.match(await page.locator('#decision-context').textContent(),/statement 2/i);await page.locator('#decision-continue').click();await page.waitForFunction(()=>!document.querySelector('#run').disabled);assert.equal(await page.locator('#warning').isVisible(),true,'Continuing a failed unit leaves a partial-results warning');assert.deepEqual(await page.locator('#result-tabs .result-select').allTextContents(),['Result 1','Result 2']);assert.equal(await page.locator('.grid-source-preview').inputValue(),'SELECT 1 AS BEFORE');}
    await page.locator('#sql').fill("SELECT 42 AS ANSWER, 'sample' AS LABEL");
    // Deterministic UI cancellation transport: no additional SQL is sent to the database.
    let cancelled=false,released=false,submittedConnection;
    await page.route('**/api/dba/query/execute',async route=>{submittedConnection=route.request().postDataJSON().connectionId;await route.fulfill({json:{id:'rail-cancel-fixture'}});});
    await page.route(/\/api\/dba\/jobs\/rail-cancel-fixture(?:\/cancel)?$/,async route=>{const request=route.request();if(request.url().endsWith('/cancel')){cancelled=true;await route.fulfill({json:{ok:true}});}else if(request.method()==='DELETE'){released=true;await route.fulfill({json:{ok:true}});}else await route.fulfill({json:{state:cancelled?'cancelled':'running',finished:cancelled?1:0}});});
    await page.locator('#run').click();await page.waitForFunction(()=>!document.querySelector('#stop').disabled);
    assert.equal(await activeConnection.isDisabled(),true);assert.equal(submittedConnection,await activeConnection.inputValue());
    await page.locator('#stop').click();await page.waitForFunction(()=>!document.querySelector('#error').hidden&&document.querySelector('#error').textContent==='cancelled');
    assert.equal(cancelled,true);assert.equal(released,true);assert.equal(await activeConnection.isDisabled(),false);assert.equal(await page.locator('#stop').isDisabled(),true);
    await page.unroute('**/api/dba/query/execute');await page.unroute(/\/api\/dba\/jobs\/rail-cancel-fixture(?:\/cancel)?$/);
    await page.locator('#run').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('1 rows'));
    if(!schema){
      const original=await activeConnection.inputValue();
      const longConnectionName='Secondary fixture with a deliberately long database connection name beyond fifty characters';const second=await page.evaluate(async({jar,name})=>{const call=async(path,body,csrf)=>{const r=await fetch('/api/dba'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Dba-CSRF':csrf||''},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json();};const session=await call('/bootstrap',{});return call('/connections',{name,url:'jdbc:h2:mem:second_fixture',driverClass:'org.h2.Driver',jar,username:'sa',saveUntested:true},session.csrf);},{jar,name:longConnectionName});
      await page.locator('#refresh').click();const longOption=activeConnection.locator(`option[value="${second.id}"]`);await longOption.waitFor({state:'attached'});const refreshedConnectionWidth=await activeConnection.evaluate(e=>e.getBoundingClientRect().width);assert.ok(Math.abs(refreshedConnectionWidth-initialConnectionWidth)<1,'A longer menu option does not widen the hidden selector');const longOptionText=await longOption.textContent();assert.equal(Array.from(longOptionText).length,51);assert.ok(longOptionText.endsWith('…'),'Dropdown names show at most 50 characters before an ellipsis');await page.getByRole('button',{name:longConnectionName,exact:true}).click();assert.equal(await activeConnection.inputValue(),original,'Tree selection must not retarget current script');
      await page.locator('#new-tab').click();assert.equal(await activeConnection.inputValue(),second.id);await page.locator('#sql').fill("SELECT 'second' AS SOURCE");
      const connectionIds=()=>page.locator('.connection-row').evaluateAll(rows=>rows.map(row=>row.dataset.connection));const firstHeader=page.locator(`.connection-row[data-connection="${original}"] > .connection-title`),secondHeader=page.locator(`.connection-row[data-connection="${second.id}"] > .connection-title`);
      await firstHeader.dragTo(secondHeader,{targetPosition:{x:5,y:28}});await page.waitForFunction(([originalId,secondId])=>{const ids=[...document.querySelectorAll('.connection-row')].map(row=>row.dataset.connection);return ids.indexOf(secondId)>=0&&ids.indexOf(secondId)<ids.indexOf(originalId);},[original,second.id]);let orderedIds=await connectionIds();assert.equal(orderedIds.indexOf(second.id),orderedIds.indexOf(original)-1);assert.equal(await activeConnection.inputValue(),second.id,'Reordering connections does not change Script targets');
      const beforeRefresh=await firstHeader.elementHandle();await page.locator('#refresh').click();await page.waitForFunction(element=>!element.isConnected,beforeRefresh);await beforeRefresh.dispose();await page.waitForFunction(([originalId,secondId])=>{const ids=[...document.querySelectorAll('.connection-row')].map(row=>row.dataset.connection);return ids.indexOf(secondId)>=0&&ids.indexOf(secondId)<ids.indexOf(originalId);},[original,second.id]);orderedIds=await connectionIds();assert.equal(orderedIds.indexOf(second.id),orderedIds.indexOf(original)-1,'Connection order survives refresh');
      await firstHeader.locator('.connection-select').focus();await page.keyboard.press('Alt+ArrowUp');await page.waitForFunction(([originalId,secondId])=>{const ids=[...document.querySelectorAll('.connection-row')].map(row=>row.dataset.connection);return ids.indexOf(originalId)>=0&&ids.indexOf(originalId)<ids.indexOf(secondId);},[original,second.id]);orderedIds=await connectionIds();assert.equal(orderedIds.indexOf(original),orderedIds.indexOf(second.id)-1);assert.equal(await page.locator(`.connection-row[data-connection="${original}"]`).getAttribute('data-color'),'#2468ac','Color survives profile refresh and reordering');
      await page.screenshot({path:'code-graph-dba/target/connection-colors-order.png'});
      const fileChooser=page.waitForEvent('filechooser');await page.locator('#file-open').click();await (await fileChooser).setFiles({name:'opened.sql',mimeType:'text/plain',buffer:Buffer.from('SELECT 7 AS VALUE')});await page.waitForFunction(()=>document.querySelector('#sql').value==='SELECT 7 AS VALUE');assert.equal(await activeConnection.inputValue(),second.id);
      await activeConnection.selectOption(original);assert.equal(await activeConnection.inputValue(),original);
      await activeConnection.focus();await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');assert.equal(await activeConnection.inputValue(),second.id,'Tab connection selector is keyboard operable');assert.ok(await activeConnection.evaluate((e,width)=>e.getBoundingClientRect().width>width,initialConnectionWidth),'The closed selector expands only to its newly selected name');await activeConnection.selectOption(original);assert.ok(await activeConnection.evaluate((e,width)=>Math.abs(e.getBoundingClientRect().width-width)<1,initialConnectionWidth),'The closed selector contracts to the selected name');
      const downloaded=page.waitForEvent('download');await page.locator('#file-save-as').click();const download=await downloaded;assert.equal(download.suggestedFilename(),'opened.sql');let content='';for await(const chunk of await download.createReadStream())content+=chunk.toString();assert.equal(content,'SELECT 7 AS VALUE');
      await page.evaluate(()=>{window.__saved=[];window.showSaveFilePicker=async()=>({name:'saved.sql',createWritable:async()=>({write:async text=>window.__saved.push(text),close:async()=>{},abort:async()=>{}})});});
      await page.locator('#file-save-as').click();await page.waitForFunction(()=>window.__saved?.length===1);await page.locator('#sql').fill('SELECT 8 AS VALUE');await page.keyboard.press('Control+s');await page.waitForFunction(()=>window.__saved?.length===2);assert.deepEqual(await page.evaluate(()=>window.__saved),['SELECT 7 AS VALUE','SELECT 8 AS VALUE']);
      await page.locator('#tabs .tab[data-type=script]').nth(1).locator('button').first().click();assert.equal(await activeConnection.inputValue(),second.id);assert.equal(await page.locator('#sql').inputValue(),"SELECT 'second' AS SOURCE");
      await page.locator('#file-save').click();await page.waitForFunction(()=>window.__saved?.length===3);assert.equal((await page.evaluate(()=>window.__saved))[2],"SELECT 'second' AS SOURCE",'Save applies to the active tab, not the previously saved tab');
      await page.locator('#tabs .tab[data-type=script]').nth(0).locator('button').first().click();assert.equal(await activeConnection.inputValue(),original);assert.match(await page.locator('#sql').inputValue(),/ANSWER/);
      await page.locator(`.connection-row[data-connection="${second.id}"] .connection-more`).click();await page.getByRole('menuitem',{name:'SQL Editor',exact:true}).press('ArrowRight');assert.deepEqual(await page.locator('.connection-submenu button').allTextContents(),['Open SQL script','Last edited SQL script','New SQL script']);await page.getByRole('menuitem',{name:'Last edited SQL script',exact:true}).click();assert.equal(await page.locator('#sql').inputValue(),"SELECT 'second' AS SOURCE");assert.equal(await activeConnection.inputValue(),second.id);await page.locator('#tabs .tab[data-type=script]').nth(0).locator('button').first().click();await page.getByRole('button',{name:'Browser fixture',exact:true}).click();
      await page.locator('#new-tab').click();assert.equal(await activeConnection.inputValue(),original,'New uses last selected database, not another tab target');await page.locator('.tab.active .close').click();
      await page.locator('#tabs .tab[data-type=script]').nth(0).locator('button').first().click();
      await page.setViewportSize({width:720,height:800});const narrowToolbar=await page.locator('#workspace-toolbar').boundingBox();assert.equal(narrowToolbar.width,720);assert.equal(await page.locator('#file-open').isVisible(),true);const commandParts=await page.locator('.data-grid-command > *').evaluateAll(elements=>elements.map(e=>({top:e.getBoundingClientRect().top,bottom:e.getBoundingClientRect().bottom})));assert.equal(commandParts.length,3);assert.ok(commandParts.every(part=>Math.abs(part.top-commandParts[0].top)<1),'The Data Grid command strip never wraps at the narrow viewport');await page.screenshot({path:'code-graph-dba/target/script-workspace-narrow.png'});await page.setViewportSize({width:1440,height:960});
      await page.screenshot({path:'code-graph-dba/target/script-workspace.png'});
    }
    if(!schema){
      const removeRow=page.locator('.connection-row').last(),removeId=await removeRow.getAttribute('data-connection'),removeName=await removeRow.locator('.connection-select').innerText(),dialog=page.locator('#remove-connection-dialog');let deletes=0;page.on('request',request=>{if(request.method()==='DELETE'&&request.url().endsWith('/connections/'+removeId))deletes++;});
      const askRemove=async()=>{await removeRow.locator('.connection-more').click();await page.getByRole('menuitem',{name:'Delete',exact:true}).click();await dialog.waitFor({state:'visible'});assert.equal(await page.locator('#remove-connection-name').innerText(),removeName);};
      await askRemove();assert.equal(await page.locator('#remove-connection-cancel').evaluate(e=>e===document.activeElement),true);await page.locator('#remove-connection-cancel').click();assert.equal(await page.locator('.connection-row').count(),2);assert.equal(deletes,0);
      await askRemove();await page.locator('#remove-connection-close').click();assert.equal(deletes,0);await askRemove();await page.keyboard.press('Escape');assert.equal(await dialog.isVisible(),false);assert.equal(deletes,0);
      await page.route('**/api/dba/connections/'+removeId,route=>route.request().method()==='DELETE'?route.fulfill({status:400,json:{error:'Connection has active jobs'}}):route.continue());
      await askRemove();await page.locator('#remove-connection-confirm').click();await page.locator('#remove-connection-error').waitFor({state:'visible'});assert.equal(await dialog.isVisible(),true);assert.match(await page.locator('#remove-connection-error').innerText(),/active jobs/);assert.equal(await page.locator('.connection-row').count(),2);await page.unroute('**/api/dba/connections/'+removeId);
      const tabCount=await page.locator('#tabs .tab').count();await page.locator('#remove-connection-confirm').click();await dialog.waitFor({state:'hidden'});await page.waitForFunction(()=>document.querySelectorAll('.connection-row').length===1);assert.equal(await page.locator('#tabs .tab').count(),tabCount,'Removing a connection preserves Script tabs');assert.equal(deletes,2);
    }
    if(schema){
      async function browserSql(sql,expected='complete'){await page.locator('#sql').fill(sql);await page.locator('#run').click();if(expected==='failed'){await page.locator('#sql-error-decision').waitFor({state:'visible'});const error=await page.locator('#decision-message').textContent();await page.locator('#decision-cancel').click();await page.waitForFunction(()=>!document.querySelector('#run').disabled);assert.equal(await page.locator('#warning').isVisible(),true);return error;}await page.waitForFunction(()=>!document.querySelector('#run').disabled);const error=await page.locator('#error').textContent();assert.equal(await page.locator('#error').isVisible(),false,error);return error;}
      assert.match(await browserSql('CREATE TABLE '+schema+'.bad_users (id SERIAL PRIMARY KEY, name varchar(50), signup_date data default current_date)','failed'),/type "data" does not exist/);
      await browserSql('CREATE TABLE '+schema+'.myusers (id SERIAL PRIMARY KEY, name varchar(50), signup_date date default current_date)');assert.match(await page.locator('#grid').innerText(),/Command completed/);assert.match(await page.locator('#status').innerText(),/commit acknowledged/);
      await browserSql("INSERT INTO "+schema+".myusers(name) VALUES ('Browser user')");assert.match(await page.locator('#status').textContent(),/1 affected/);
      await browserSql('SELECT name FROM '+schema+'.myusers; SELECT version();');assert.equal(await page.locator('#result-tabs .result-tab').count(),2);assert.match(await page.locator('#grid').innerText(),/Browser user/);await page.locator('#result-tabs .result-select').nth(1).click();assert.match(await page.locator('#grid').innerText(),/PostgreSQL/);
      await browserSql('DROP TABLE '+schema+'.myusers');await page.locator('#sql').fill('SELECT id FROM '+schema+'.items WHERE id = 1');
      await page.locator('#explain').click();
      await page.waitForFunction(()=>document.querySelector('#grid').textContent.includes('Plan')||!document.querySelector('#error').hidden);
      assert.equal(await page.locator('#error').isVisible(),false,await page.locator('#error').textContent());
      await page.locator('#sql').fill('SELECT * FROM '+schema+'.items');await page.locator('#run').click();
      await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('truncated'));assert.match(await page.locator('#status').innerText(),/10 rows/);
    }
    const renameRoot=page.locator('.connection-row').first(),originalRootName=await renameRoot.locator(':scope > .connection-title .connection-select').innerText(),rootId=await renameRoot.getAttribute('data-connection');
    const renameConnection=async name=>{await renameRoot.locator(':scope > .connection-title .connection-more').click();await page.getByRole('menuitem',{name:'Copy',exact:true}).waitFor({state:'visible'});const labels=await page.getByRole('menuitem').allTextContents(),copyIndex=labels.indexOf('Copy');assert.deepEqual(labels.slice(copyIndex,copyIndex+4),['Copy','Delete','Rename','Refresh']);assert.equal(await page.getByRole('menuitem').evaluateAll(items=>items.every(item=>item.querySelector('svg[data-lucide]'))),true,'Every popup action uses a Lucide icon');await page.getByRole('menuitem',{name:'Rename',exact:true}).click();await page.locator('#tree-object-name').fill(name);await page.locator('#tree-object-confirm').click();await page.waitForFunction(name=>document.querySelector('.connection-row .connection-select').textContent===name,name);};
    await renameConnection('Renamed fixture');assert.equal(await renameRoot.getAttribute('data-connection'),rootId);await renameConnection(originalRootName);
    await page.locator('#workspace-settings').click();await page.locator('#agents').click();await page.locator('#agent-form [name=name]').fill('Browser read agent');await page.locator('#agent-form [name=schema]').fill(schema||'PUBLIC');await page.locator('#agent-form [name=objects]').fill('items');await page.locator('#grant-agent').click();
    await page.waitForFunction(()=>document.querySelector('#agent-token').value.length===43);assert.match(await page.locator('#agent-list').innerText(),/Browser read agent/);
    await page.locator('[data-close=agents-dialog]').click();assert.ok((await page.locator('#agent-token').inputValue()).length===0,'Agent token must be cleared on close');
    await page.locator('#workspace-settings').click();await page.locator('#agents').click();await page.getByRole('button',{name:'Revoke',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#agent-list').children.length===0);await page.locator('[data-close=agents-dialog]').click();
    await page.locator('#divider').focus();const before=await page.locator('#divider').boundingBox();await page.keyboard.press('ArrowRight');const after=await page.locator('#divider').boundingBox();assert.ok(after.x>before.x);
    await page.locator('#workspace-settings').click();await page.locator('#settings').click();
    await page.locator('[name=memory]').fill('32m');
    await page.locator('[name=agentRows]').fill('7');
    await page.locator('#settings-form button[type=submit]').click();
    await page.locator('#settings-dialog').waitFor({state:'hidden'});
    await page.screenshot({path:'code-graph-dba/target/browser-smoke.png'});
    assert.deepEqual(errors,[]);
    await page.locator('#workspace-settings').click();await page.locator('#settings').click();assert.equal(await page.locator('[name=agentRows]').inputValue(),'7');await page.locator('[data-close=settings-dialog]').click();
    assert.equal(await page.locator('#logout').count(),0);await page.evaluate(async()=>{const session=await(await fetch('/api/dba/bootstrap',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).json();await fetch('/api/dba/logout',{method:'POST',headers:{'X-Dba-CSRF':session.csrf}});});await page.reload();await page.locator('#welcome').waitFor({state:'visible'});assert.equal(await page.locator('#tabs .tab').count(),0,'Ending a session clears its recoverable Script workspace');
    console.log('Browser checks passed: session-scoped Script recovery, compact toolbars, reusable statement-aware Data Grid, SQL viewer resizing/dismissal, filter command strip, direct and modal column reordering, stable widths, sticky headers/row numbers, virtualization, tab connection selectors, file actions, direct access, connection tests, query, grants, keyboard operation, responsive layout, settings menu, session expiry/logout API'+(schema?', PostgreSQL plans/truncation':'')+'; no page errors.');
    const navHandle=await page.locator('#divider').boundingBox();await page.mouse.move(navHandle.x+2,navHandle.y+30);await page.mouse.down();await page.mouse.move(340,navHandle.y+30);await page.mouse.up();assert.equal(await page.evaluate(()=>sessionStorage.getItem('codegraph.dba.sidebar-width')),'340');
    await page.reload();await page.waitForFunction(()=>document.querySelector('#connection-count').textContent.includes('connection'));assert.equal((await page.locator('#divider').boundingBox()).x,340,'Sidebar width survives refresh in this browser tab');
    await page.locator('#divider').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.evaluate(()=>sessionStorage.getItem('codegraph.dba.sidebar-width')),'360');
    await page.reload();await page.waitForFunction(()=>document.querySelector('#connection-count').textContent.includes('connection'));assert.equal((await page.locator('#divider').boundingBox()).x,360,'Keyboard resize is persisted too');
    await page.evaluate(()=>sessionStorage.setItem('codegraph.dba.sidebar-width','99999'));await page.reload();await page.waitForFunction(()=>document.querySelector('#connection-count').textContent.includes('connection'));assert.equal((await page.locator('#divider').boundingBox()).x,500,'Stored widths are clamped');
    await page.evaluate(()=>sessionStorage.setItem('codegraph.dba.sidebar-width','invalid'));await page.reload();await page.waitForFunction(()=>document.querySelector('#connection-count').textContent.includes('connection'));assert.ok(Number.isFinite((await page.locator('#divider').boundingBox()).x),'Invalid stored width does not break startup');
    assert.deepEqual(errors,[]);console.log('Sidebar browser storage checks passed: drag, keyboard, reload, bounds and malformed data.');

  } finally {await browser.close();await fetch(base+'/__test/stop');}
})().catch(e=>{console.error(e);process.exitCode=1;});
