const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
module.exports=async(browser,base)=>{
 const context=await browser.newContext({viewport:{width:1440,height:960},acceptDownloads:true});
 const page=await context.newPage(),errors=[],requests=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/dba/'))requests.push([r.method(),r.url()]);});
 try{
  await page.goto(base+'/dba');await page.waitForFunction(()=>document.querySelector('#connection-count')?.textContent.includes('connection'));
  await page.locator('#workspace-settings').click();await page.locator('#settings').click();await page.locator('#settings-dialog').waitFor({state:'visible'});
  const metadataLimit=page.locator('#settings-form [name="compareMetadataMiB"]');
  assert.equal(await metadataLimit.inputValue(),'');await metadataLimit.fill('32');
  await page.locator('#settings-form button[type="submit"]').click();await page.locator('#settings-dialog').waitFor({state:'hidden'});
  await page.reload();await page.locator('#workspace-settings').click();await page.locator('#settings').click();await page.locator('#settings-dialog').waitFor({state:'visible'});
  assert.equal(await metadataLimit.inputValue(),'32');await metadataLimit.fill('');
  await page.locator('#settings-form button[type="submit"]').click();await page.locator('#settings-dialog').waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Compare',exact:true}).click();
  const wizard=page.getByRole('region',{name:'Database Compare'});
  const source=wizard.getByLabel('source connection',{exact:true});await source.selectOption({label:'Context H2'});
  await page.waitForFunction(()=>[...document.querySelector('[aria-label="source schema"]').options].some(o=>o.value==='SRC'));
  await wizard.getByLabel('source schema',{exact:true}).selectOption('SRC');
  await wizard.getByLabel('destination connection',{exact:true}).selectOption({label:'Context H2'});
  await page.waitForFunction(()=>[...document.querySelector('[aria-label="destination schema"]').options].some(o=>o.value==='DST'));
  await wizard.getByLabel('destination schema',{exact:true}).selectOption('DST');
  assert.equal(await wizard.getByRole('button',{name:'Test connection',exact:true}).count(),0);
  await page.route('**/api/dba/compare/test',async route=>{
    if(route.request().postDataJSON().schema==='DST')await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'Destination connection fixture unavailable'})});else await route.continue();
  });
  await wizard.getByRole('button',{name:'Choose object types',exact:true}).click();
  await wizard.locator('.compare-error').filter({hasText:'Destination connection fixture unavailable'}).waitFor();
  assert.equal(await wizard.locator('[aria-current="step"]').innerText(),'1. Databases');
  await page.unroute('**/api/dba/compare/test');
  const testedBefore=requests.filter(([method,url])=>method==='POST'&&url.endsWith('/compare/test')).length;
  await wizard.getByRole('button',{name:'Choose object types',exact:true}).click();
  await wizard.getByRole('heading',{name:'Object types',exact:true}).waitFor();
  assert.equal(requests.filter(([method,url])=>method==='POST'&&url.endsWith('/compare/test')).length,testedBefore+2);
  await wizard.getByRole('button',{name:'Clear all',exact:true}).click();
  for(const kind of ['Tables','Views','Sequences'])await wizard.getByRole('checkbox',{name:kind,exact:true}).check();
  assert.equal(await wizard.getByLabel('Default table data mode',{exact:true}).inputValue(),'none');
  assert.equal(await wizard.getByRole('button',{name:'Load objects and choose table data'}).isDisabled(),true);
  await wizard.getByLabel('Default table data mode',{exact:true}).selectOption('upsert');
  await wizard.getByRole('checkbox',{name:'Sync sequence values',exact:true}).check();
  await wizard.getByRole('button',{name:'Load objects and choose table data'}).click();
  const parent=wizard.locator('.compare-object-option').filter({hasText:'SRC.PARENT'});await parent.getByRole('checkbox',{name:'Include data',exact:true}).check();
  await wizard.getByLabel('Default table data mode',{exact:true}).selectOption('none');
  assert.equal(await parent.getByRole('checkbox',{name:'Include data',exact:true}).isDisabled(),true);
  await wizard.getByLabel('Default table data mode',{exact:true}).selectOption('upsert');
  assert.equal(await parent.getByRole('checkbox',{name:'Include data',exact:true}).isChecked(),true);
  await wizard.getByRole('button',{name:'Compare',exact:true}).click();
  await wizard.getByRole('button',{name:'SRC.CHILD',exact:true}).waitFor({timeout:30000});
  await wizard.locator('.compare-tree details').filter({has:page.locator(':scope > summary',{hasText:/^Identical/})}).evaluateAll(nodes=>nodes.forEach(n=>n.open=true));
  await wizard.getByRole('button',{name:'SRC.PARENT',exact:true}).click();
  await wizard.getByRole('tab',{name:'Data differences',exact:true}).click();
  await wizard.locator('.compare-data-scroll').waitFor();
  assert.match(await wizard.locator('.compare-detail-content').innerText(),/Different: 1/);
  assert.match(await wizard.locator('.compare-detail-content').innerText(),/Only in source: 1/);
  assert.match(await wizard.locator('.compare-detail-content').innerText(),/Only in destination: 1/);
  await wizard.getByRole('tab',{name:'Source / Destination',exact:true}).click();await wizard.locator('.compare-code-pair').waitFor();
  await wizard.getByRole('button',{name:'Expand',exact:true}).click();
  const verifyLayout=async()=>{const boxes=await wizard.evaluate(e=>({root:e.getBoundingClientRect().toJSON(),footer:e.querySelector('footer').getBoundingClientRect().toJSON(),width:innerWidth,height:innerHeight}));assert.ok(boxes.root.x>=0&&boxes.root.right<=boxes.width+1);assert.ok(boxes.footer.bottom<=boxes.height+1);};
  await verifyLayout();await fs.mkdir('target/compare-browser-evidence',{recursive:true});await page.screenshot({path:'target/compare-browser-evidence/review.png'});
  await page.setViewportSize({width:600,height:800});await verifyLayout();await page.screenshot({path:'target/compare-browser-evidence/review-narrow.png'});await page.setViewportSize({width:1440,height:960});
  await wizard.getByRole('button',{name:'Generate script',exact:true}).click();
  const sql=wizard.getByRole('textbox',{name:'Generated destination SQL',exact:true});await sql.waitFor({timeout:30000});
  const script=await sql.inputValue();assert.match(script,/CREATE TABLE "DST"\."CHILD"/);assert.match(script,/RESTART WITH 20/);assert.match(script,/UPDATE "DST"\."PARENT"/);
  assert.equal(await wizard.getByRole('button',{name:/^(Execute|Apply)$/}).count(),0);
  const downloadPromise=page.waitForEvent('download');await wizard.getByRole('button',{name:'Save',exact:true}).click();const download=await downloadPromise;
  assert.equal(await fs.readFile(await download.path(),'utf8'),script);
  await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:base});await wizard.getByRole('button',{name:'Copy',exact:true}).click();await page.waitForFunction(expected=>navigator.clipboard.readText().then(text=>text===expected),script);
  await page.screenshot({path:'target/compare-browser-evidence/script.png'});
  const downloadRequest=requests.filter(([method,url])=>method==='GET'&&url.includes('/compare/artifacts/')&&url.endsWith('/download')).at(-1)[1];
  assert.equal((await context.request.post(base+'/api/dba/compare/test',{data:{}})).status(),403,'Compare mutations require CSRF');
  const other=await browser.newContext();await other.request.post(base+'/api/dba/bootstrap',{headers:{Origin:base},data:{}});assert.equal((await other.request.get(downloadRequest)).status(),403,'Artifacts are owner-bound');await other.close();
  await wizard.getByRole('button',{name:'2. Objects & options',exact:true}).click();
  await wizard.getByLabel('Default table data mode',{exact:true}).selectOption('none');
  const structureRequest=page.waitForRequest(r=>r.method()==='POST'&&r.url().endsWith('/compare/start'));
  await wizard.getByRole('button',{name:'Compare',exact:true}).click();
  const structureInput=(await structureRequest).postDataJSON();assert.equal(structureInput.dataMode,'none');assert.deepEqual(structureInput.tableData,[]);
  await wizard.getByRole('button',{name:'SRC.CHILD',exact:true}).waitFor({timeout:30000});
  await wizard.getByRole('button',{name:'Generate script',exact:true}).click();await sql.waitFor({timeout:30000});
  const structureSql=await sql.inputValue();assert.match(structureSql,/CREATE TABLE/);assert.doesNotMatch(structureSql,/^(?:INSERT INTO|UPDATE |DELETE FROM|MERGE INTO|TRUNCATE )/m);assert.match(structureSql,/RESTART WITH 20/);
  await wizard.getByRole('button',{name:'Cancel',exact:true}).click();await wizard.waitFor({state:'detached'});
  assert.equal((await context.request.get(downloadRequest)).status(),403,'Cancelled script must no longer be downloadable');
  assert.equal(requests.filter(([method,url])=>method==='POST'&&/\/api\/dba\/(queries|query\/execute|execute|mutations)(\/|$)/.test(url)).length,0);
  await verifyTypeSelection(page);assert.deepEqual(errors,[]);console.log('COMPARE_BROWSER_VERIFIED review, rows, SQL, save, copy, viewport, disposal, per-type selection across pages, filters and destructive guards');
 }catch(error){await fs.mkdir('target/compare-browser-evidence',{recursive:true});await page.screenshot({path:'target/compare-browser-evidence/failure.png'});console.error(await page.locator('body').innerText());throw error;}
 finally{await context.close();}
};

async function verifyTypeSelection(page){
 await page.evaluate(async()=>{
  const {DatabaseCompare}=await import('/dba/compare.js');window.bulkCalls=[];
  const fixture=new DatabaseCompare({api:async(path,method='GET',body)=>{bulkCalls.push({path,method,body});if(path.includes('/objects/'))return fixture.objects.find(o=>o.id===path.split('/').at(-1));return{};},profiles:()=>[],close:()=>{},notify:()=>{},csrf:()=>''});
  const object=(id,kind,status,changes,supported=true)=>({id,name:id,schema:'SRC',kind,status,changes,supported});
  const change=(id,destructive=false)=>({id,action:'Add',section:'definition',name:id,destructive});
  fixture.objects=[object('MIXED','tables','different',[change('safe_a'),change('safe_b'),change('drop_c',true)]),object('DESTRUCTIVE','tables','different',[change('drop_d',true)]),object('BLOCKED','tables','unsupported',[change('blocked')],false),object('PRESERVED','tables','destination_only',[change('keep')]),...Array.from({length:251},(_,i)=>object('T'+String(i).padStart(3,'0'),'tables','source_only',[change('add_'+i)])),object('V','views','source_only',[change('view')]),object('SEQ','sequences','identical',[])];
  for(const o of fixture.objects)fixture.selection.set(o.id,new Set(o.status==='source_only'?o.changes.map(c=>c.id):[]));fixture.selection.get('MIXED').add('safe_a');fixture.objects.at(-1).stateModes=['advance'];fixture.settings.syncSequences=true;fixture.settings.dataMode='upsert';fixture.dataOptions.set('T000',{includeData:true});fixture.id='fixture';fixture.step=2;fixture.render();const host=document.createElement('div');document.body.append(host);fixture.mount(host);fixture.root.classList.add('compare-expanded');window.bulkFixture=fixture;
 });
 const review=page.getByRole('region',{name:'Database Compare'}),tables=review.getByRole('checkbox',{name:'Include all tables (Only in source)',exact:true}),different=review.getByRole('checkbox',{name:'Include all tables (Different)',exact:true});
 assert.equal(await tables.isChecked(),true);assert.equal(await different.evaluate(e=>e.indeterminate),true);
 await tables.uncheck();assert.equal(await page.evaluate(()=>bulkFixture.objects.filter(o=>o.kind==='tables'&&o.status==='source_only').every(o=>bulkFixture.selection.get(o.id).size===0)),true);
 assert.equal(await page.evaluate(()=>bulkFixture.selection.get('V').has('view')),true);assert.equal(await page.evaluate(()=>bulkFixture.dataOptions.get('T000').includeData),true);assert.equal(await page.evaluate(()=>bulkFixture.sequenceOption(bulkFixture.objects.at(-1)).syncValues),true);
 await review.getByRole('searchbox',{name:'Search comparison objects',exact:true}).fill('SRC.T00');await tables.check();assert.equal(await page.evaluate(()=>bulkFixture.objects.filter(o=>o.kind==='tables'&&o.status==='source_only'&&bulkFixture.selection.get(o.id).size>0).length),10);
 await review.getByRole('searchbox',{name:'Search comparison objects',exact:true}).fill('');assert.equal(await tables.evaluate(e=>e.indeterminate),true);await tables.check();await review.getByRole('button',{name:'Next objects',exact:true}).click();assert.equal(await review.getByRole('checkbox',{name:'Include SRC.T250',exact:true}).isChecked(),true);await review.getByRole('button',{name:'Previous objects',exact:true}).click();
 // Summary toggles preserve collapse state and keyboard focus while selecting children.
 await tables.locator('..').click({position:{x:150,y:10}});assert.equal(await tables.evaluate(e=>e.closest('details').open),false);await tables.uncheck();assert.equal(await tables.evaluate(e=>e.closest('details').open),false);assert.equal(await tables.evaluate(e=>e===document.activeElement),true);
 await different.check();assert.deepEqual(await page.evaluate(()=>[...bulkFixture.selection.get('MIXED')]),['safe_a','safe_b']);assert.equal(await page.evaluate(()=>bulkFixture.selection.get('DESTRUCTIVE').size),0);assert.equal(await review.getByRole('checkbox',{name:'Include SRC.DESTRUCTIVE',exact:true}).isDisabled(),true);
 assert.equal(await review.getByRole('checkbox',{name:'Include all tables (Unsupported / blocked)',exact:true}).isDisabled(),true);assert.equal(await review.getByRole('checkbox',{name:'Include all tables (Only in destination)',exact:true}).isDisabled(),true);
 await review.getByRole('button',{name:'SRC.MIXED',exact:true}).click();await review.locator('.compare-detail-content').getByRole('checkbox',{name:'Add definition · safe_b',exact:true}).uncheck();assert.equal(await different.evaluate(e=>e.indeterminate),true);assert.equal(await review.locator('.compare-footer > span').innerText(),'2 selected changes');await different.check();assert.equal(await review.locator('.compare-detail-content').getByRole('checkbox',{name:'Add definition · safe_b',exact:true}).isChecked(),true);
 await review.getByRole('checkbox',{name:'Allow destructive schema changes',exact:true}).check();assert.equal(await different.evaluate(e=>e.indeterminate),true);await different.check();assert.deepEqual(await page.evaluate(()=>[...bulkFixture.selection.get('DESTRUCTIVE')]),['drop_d']);await review.getByRole('checkbox',{name:'Allow destructive schema changes',exact:true}).uncheck();assert.deepEqual(await page.evaluate(()=>[...bulkFixture.selection.get('MIXED')]),['safe_a','safe_b']);assert.equal(await page.evaluate(()=>bulkFixture.selection.get('DESTRUCTIVE').size),0);
 await page.evaluate(()=>bulkFixture.artifact={artifactId:'stale-script'});await different.uncheck();assert.equal(await page.evaluate(()=>bulkFixture.artifact),null);assert.equal(await page.evaluate(()=>bulkCalls.some(c=>c.method==='DELETE'&&c.path==='/compare/artifacts/stale-script')),true);assert.equal(await review.locator('.compare-footer > span').innerText(),'1 selected changes');
 await page.evaluate(async()=>{const host=bulkFixture.root.parentElement;await bulkFixture.dispose();host.remove();});
}
