const assert=require('node:assert/strict');
module.exports=async(browser,base)=>{
  const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[];
  page.on('pageerror',error=>errors.push(error.message));let queryCount=0;
  try{
    let releaseBootstrap;const bootstrapGate=new Promise(resolve=>releaseBootstrap=resolve);
    await page.route('**/api/dba/bootstrap',async route=>{await bootstrapGate;await route.continue();});
    await page.goto(base+'/dba');await page.locator('#add').waitFor();
    await page.waitForFunction(()=>document.querySelector('#layout').inert);
    assert.equal(await page.locator('#workspace-toolbar-actions').evaluate(node=>node.inert),true);
    assert.equal(await page.locator('#workspace-settings').evaluate(node=>node.inert),true);
    await page.keyboard.press('Control+Alt+n');assert.equal(await page.locator('#tabs .tab').count(),0);
    releaseBootstrap();await page.waitForFunction(()=>!document.querySelector('#layout').inert);
    await page.unroute('**/api/dba/bootstrap');
    await page.locator('#add').click();await page.getByRole('button',{name:'MongoDB',exact:true}).click();
    await page.locator('#ce-url').waitFor();
    assert.equal(await page.locator('#ce-url').inputValue(),'mongodb://localhost:27017');
    assert.equal(await page.locator('#driver-choice').isVisible(),false);assert.equal(await page.locator('#ce-jars').count(),0);
    await page.getByRole('tab',{name:'Driver',exact:true}).click();
    assert.match(await page.locator('#ce-panel-1').innerText(),/bundled native client/);
    await page.getByRole('tab',{name:'General',exact:true}).click();await page.locator('#ce-name').fill('Native Mongo fixture');
    await page.locator('#ce-database').fill('app');await page.locator('#ce-native-access').selectOption({label:'Allow reviewed writes'});
    await page.getByRole('tab',{name:'Network',exact:true}).click();await page.locator('#ce-topology').selectOption('replica_set');await page.locator('#ce-replicaSet').fill('fixture');
    page.once('dialog',dialog=>dialog.accept());await page.locator('#ce-save-untested').click();
    await page.locator('#connection-editor').waitFor({state:'hidden'});
    const mongo=page.getByRole('treeitem',{name:'Native Mongo fixture',exact:true});await mongo.waitFor();
    await page.route('**/api/dba/native/tree',async route=>{
      const input=route.request().postDataJSON();let nodes=[];
      if(input.kind==='root')nodes=[{key:'database:app',kind:'native_database',name:'app',database:'app',branch:true}];
      if(input.kind==='native_database')nodes=[{key:'collections:Collections',kind:'native_collections',name:'Collections',database:'app',branch:true}];
      if(input.kind==='native_collections')nodes=[{key:'collection:items',kind:'native_collection',name:'items',database:'app',collection:'items',branch:true,nativeObject:true,command:{find:'items',filter:{},limit:100}}];
      await route.fulfill({json:{id:'native-tree-'+input.kind,state:'complete',result:{nodes}}});
      await page.route('**/api/dba/jobs/native-tree-'+input.kind,job=>job.fulfill({json:job.request().method()==='DELETE'?{}:{id:'native-tree-'+input.kind,state:'complete',finished:Date.now(),result:{nodes}}}));
    });
    await mongo.getByRole('button',{name:'Expand Native Mongo fixture',exact:true}).click();
    await mongo.getByRole('button',{name:'Expand app',exact:true}).click();
    await mongo.getByRole('button',{name:'Expand Collections',exact:true}).click();
    const items=mongo.getByRole('treeitem',{name:'items',exact:true});
    await items.getByRole('button',{name:'items',exact:true}).dblclick();await page.locator('.native-workspace').waitFor();
    assert.equal(await page.locator('.native-workspace input[aria-label=Collection]').inputValue(),'items');
    assert.match(await page.locator('.native-command').inputValue(),/"find": "items"/);
    await mongo.getByRole('button',{name:'Actions for Native Mongo fixture',exact:true}).click();
    await page.getByRole('menuitem',{name:'Native workspace',exact:true}).click();await page.locator('.native-workspace').waitFor();
    assert.equal(await page.locator('#document').isHidden(),true);assert.equal(await page.locator('#file-save').isDisabled(),true);
    await page.locator('.native-workspace input[aria-label=Collection]').fill('items');
    const command='{"find":"items","filter":{"date":{"$gte":{"$date":"2026-09-01T00:00:00Z"}}},"limit":3}';
    await page.locator('.native-command').fill(command);
    await page.route('**/api/dba/native/execute',async route=>{
      const body=route.request().postDataJSON();assert.equal(body.database,'app');assert.equal(body.collection,'items');assert.equal(body.command.find,'items');queryCount++;
      await route.fulfill({json:{id:'native-browser-job'}});
    });
    await page.route('**/api/dba/jobs/native-browser-job',route=>route.fulfill({json:route.request().method()==='DELETE'?{}:{id:'native-browser-job',state:'complete',finished:Date.now(),result:{kind:'documents',entries:[{name:'<script>never execute</script>',id:{$numberLong:'9007199254740993'}}],truncated:false}}}));
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await page.getByRole('status').filter({hasText:'Complete'}).waitFor();
    assert.equal(queryCount,1);assert.match(await page.locator('.native-result').innerText(),/9007199254740993/);assert.equal(await page.locator('.native-result script').count(),0);
    const gridTab=page.locator('.native-workspace').getByRole('tab',{name:'Grid',exact:true});
    const jsonTab=page.locator('.native-workspace').getByRole('tab',{name:'JSON',exact:true});
    await gridTab.click();await page.locator('.native-workspace .data-grid-scroll').waitFor();
    assert.equal(await page.locator('.native-workspace .grid-source-preview').isVisible(),false);
    assert.equal(await page.locator('.native-workspace .grid-column-toggle').count(),0);
    assert.match(await page.locator('.native-workspace [role=grid]').innerText(),/9007199254740993/);
    assert.equal(await page.locator('.native-workspace [role=grid] script').count(),0);
    const header=page.locator('.native-workspace .data-column-header').first();await header.focus();await page.keyboard.press('Alt+ArrowRight');
    assert.equal(await page.locator('.native-workspace .grid-column-label').first().innerText(),'id');
    const resize=page.locator('.native-workspace .column-resize').first(),width=Number(await resize.getAttribute('aria-valuenow'));
    await resize.focus();await page.keyboard.press('ArrowRight');assert.equal(Number(await resize.getAttribute('aria-valuenow')),width+10);
    await jsonTab.click();await gridTab.click();assert.equal(await page.locator('.native-workspace .grid-column-label').first().innerText(),'id');
    assert.equal(queryCount,1,'Changing result display must not execute anything');
    await page.screenshot({path:'code-graph-dba/target/native-grid.png'});
    const projection=await page.evaluate(async()=>{
      const {nativeGridModel}=await import('/dba/native-workspace.js');
      const model=nativeGridModel([{nullable:null,large:{$numberLong:'9007199254740993'}},{}]);
      const wide=nativeGridModel([Object.fromEntries(Array.from({length:300},(_,i)=>['field'+i,i]))]);
      return{rows:model.rows,columns:wide.columns.length,omitted:wide.omittedColumns};
    });
    assert.deepEqual(projection.rows,[['null','{"$numberLong":"9007199254740993"}'],['[missing]','[missing]']]);
    assert.equal(projection.columns,256);assert.equal(projection.omitted,true);
    await jsonTab.click();
    await page.waitForFunction(async()=>{const r=await fetch('/api/dba/workspace');return(await r.json()).tabs.some(t=>t.type==='native'&&t.commandText.includes('"items"'));});
    await page.reload();await page.locator('.native-workspace').waitFor();assert.equal(await page.locator('.native-command').inputValue(),command);assert.equal(queryCount,1);
    assert.match(await page.locator('.native-result').innerText(),/Run a command/);
    const mutation='{"insert":"items","documents":[{"name":"review-only"}]}';let applied=0;
    await page.locator('.native-command').fill(mutation);
    await page.route('**/api/dba/native/apply',async route=>{
      assert.ok(route.request().postDataJSON().planId);applied++;
      await route.fulfill({json:{id:'native-browser-job'}});
    });
    await page.getByRole('button',{name:'Run native command',exact:true}).click();
    const review=page.getByRole('dialog',{name:'Review native database change'});await review.waitFor();
    assert.match(await review.innerText(),/Native Mongo fixture/);assert.match(await review.innerText(),/review-only/);
    assert.equal(applied,0);await review.getByRole('button',{name:'Cancel',exact:true}).click();
    await review.waitFor({state:'hidden'});assert.equal(applied,0);
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();
    await review.getByRole('button',{name:'Apply once',exact:true}).click();
    await page.locator('.native-status').filter({hasText:'Complete'}).waitFor();assert.equal(applied,1);
    const rename='{"renameCollection":"app.items","to":"app.items.renamed","dropTarget":false}';
    await page.locator('.native-command').fill(rename);
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();
    assert.match(await review.innerText(),/Review destructive database change/);
    assert.match(await review.innerText(),/app.items.renamed/);assert.match(await review.innerText(),/cursors/);
    await review.getByRole('button',{name:'Cancel',exact:true}).click();await review.waitFor({state:'hidden'});assert.equal(applied,1);
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();
    await review.getByRole('button',{name:'Apply once',exact:true}).click();await page.locator('.native-status').filter({hasText:'Complete'}).waitFor();assert.equal(applied,2);
    assert.equal(await page.locator('.native-workspace input[aria-label=Collection]').inputValue(),'items','Rename must not silently retarget an existing workspace');
    await page.locator('.native-command').fill('{"renameCollection":"other.items","to":"app.next"}');
    await page.getByRole('button',{name:'Run native command',exact:true}).click();
    await page.locator('.native-status').filter({hasText:'exactly match'}).waitFor();assert.equal(applied,2);
    assert.equal(await review.count(),0);await page.locator('.native-command').fill(mutation);
    for(const setting of [{collMod:'items',index:{name:'expiry',expireAfterSeconds:60}},{collMod:'items',expireAfterSeconds:'off'},{collMod:'items',cappedMax:200}]){
      await page.locator('.native-command').fill(JSON.stringify(setting));
      await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();
      assert.match(await review.innerText(),/Review destructive database change/);assert.match(await review.innerText(),/delete/);
      assert.match(await review.innerText(),/items/);assert.equal(applied,2);
      await review.getByRole('button',{name:'Cancel',exact:true}).click();await review.waitFor({state:'hidden'});
    }
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();
    await review.getByRole('button',{name:'Apply once',exact:true}).click();await page.locator('.native-status').filter({hasText:'Complete'}).waitFor();assert.equal(applied,3);
    await page.locator('.native-command').fill('{"collMod":"items","expireAfterSeconds":60,"cappedMax":10}');
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await page.locator('.native-status').filter({hasText:'mixed collection setting'}).waitFor();
    assert.equal(await review.count(),0);assert.equal(applied,3);await page.locator('.native-command').fill(mutation);
    const mongoTransaction={transaction:[{insert:'items',documents:[{_id:'reviewed',value:1}]},{delete:'items',deletes:[{q:{_id:'reviewed'},limit:1}]}]};
    await page.locator('.native-command').fill(JSON.stringify(mongoTransaction));
    assert.match(await page.locator('.native-command').getAttribute('title'),/replica-set/);
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();
    assert.match(await review.innerText(),/atomic MongoDB/);assert.match(await review.innerText(),/Review destructive database change/);
    await page.screenshot({path:'code-graph-dba/target/mongo-transaction-review.png'});
    await review.getByRole('button',{name:'Cancel',exact:true}).click();await review.waitFor({state:'hidden'});assert.equal(applied,3);
    await page.route('**/api/dba/jobs/native-browser-job',route=>route.fulfill({json:route.request().method()==='DELETE'?{}:{id:'native-browser-job',state:'failed',finished:Date.now(),error:'MongoDB transaction conflict',result:{kind:'transaction',outcome:'rollback_acknowledged',atomic:true,entries:[{index:0,state:'rolled_back'}],notice:'Transaction aborted; no transaction writes committed.'}}}));
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();await review.getByRole('button',{name:'Apply once',exact:true}).click();
    await page.locator('.native-status').filter({hasText:'transaction conflict'}).waitFor();assert.equal(applied,4);
    assert.match(await page.locator('.native-result').innerText(),/rollback_acknowledged/);assert.equal(await page.locator('.native-command').inputValue(),JSON.stringify(mongoTransaction));
    let watchRequests=0;const watchCommand='{"watch":"items","waitMillis":0,"limit":2}';
    const nextBatch=page.getByRole('button',{name:'Read next change batch',exact:true});assert.equal(await nextBatch.isDisabled(),true);
    const streamIcon=await nextBatch.locator('svg').evaluate(node=>({fill:getComputedStyle(node).fill,stroke:getComputedStyle(node).stroke,color:getComputedStyle(node.parentElement).color}));assert.equal(streamIcon.fill,'none');assert.equal(streamIcon.stroke,streamIcon.color);
    await page.route('**/api/dba/native/execute',async route=>{const input=route.request().postDataJSON();assert.equal(input.command.watch,'items');watchRequests++;if(watchRequests===2)assert.equal(input.command.cursor,'mcs1.browser-one');else assert.equal(input.command.cursor,undefined);await route.fulfill({json:{id:'native-stream-browser'}});});
    await page.route('**/api/dba/jobs/native-stream-browser',route=>route.fulfill({json:route.request().method()==='DELETE'?{}:{id:'native-stream-browser',state:'complete',finished:Date.now(),result:{kind:'change_stream',entries:[{operationType:'insert',documentKey:{_id:watchRequests}}],stopReason:'event_limit',nextCursor:watchRequests===1?'mcs1.browser-one':'mcs1.browser-two',snapshot:false,retainedSubscription:false}}}));
    await page.locator('.native-command').fill(watchCommand);await page.getByRole('button',{name:'Run native command',exact:true}).click();await page.locator('.native-status').filter({hasText:'Read next batch explicitly'}).waitFor();
    assert.equal(watchRequests,1);assert.equal(await review.count(),0);assert.equal(await nextBatch.isEnabled(),true);
    await nextBatch.click();await page.locator('.native-result').filter({hasText:'browser-two'}).waitFor();assert.equal(watchRequests,2);assert.equal(await page.locator('.native-command').inputValue(),watchCommand);
    await page.screenshot({path:'code-graph-dba/target/native-change-stream.png'});
    await page.locator('.native-command').fill(watchCommand+' ');assert.equal(await nextBatch.isDisabled(),true,'Editing the input invalidates its retained continuation');
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await page.locator('.native-status').filter({hasText:'Read next batch explicitly'}).waitFor();assert.equal(watchRequests,3);
    await page.waitForFunction(async expected=>{const response=await fetch('/api/dba/workspace');return(await response.json()).tabs.some(tab=>tab.type==='native'&&tab.commandText===expected);},watchCommand+' ');
    await page.reload();await page.locator('.native-workspace').waitFor();assert.equal(await nextBatch.isDisabled(),true);assert.equal(watchRequests,3,'Reload must not resume a change subscription');
    assert.equal((await page.locator('.native-command').inputValue()).includes('mcs1.'),false,'Managed continuation is not persisted in the command draft');
    await page.locator('.native-command').fill(mutation);
    await mongo.getByRole('button',{name:'Actions for Native Mongo fixture',exact:true}).click();
    await page.getByRole('menuitem',{name:'Delete',exact:true}).click();await page.locator('#remove-connection-dialog').waitFor();
    await page.locator('#remove-connection-confirm').click();await page.locator('#remove-connection-dialog').waitFor({state:'hidden'});
    await page.locator('.native-status').filter({hasText:'Connection removed'}).waitFor();
    assert.equal(await page.getByRole('button',{name:'Run native command',exact:true}).isDisabled(),true);
    assert.equal(await page.locator('.native-command').inputValue(),mutation);
    await page.reload();await page.getByRole('status').filter({hasText:'Connection removed'}).waitFor();
    assert.match(await page.locator('#table-document').innerText(),/review-only/);
    await page.unroute('**/api/dba/native/execute');await page.unroute('**/api/dba/native/apply');
    await page.locator('#add').click();await page.getByRole('button',{name:'Redis',exact:true}).click();
    await page.locator('#ce-name').fill('Native Redis binary fixture');await page.locator('#ce-database').fill('0');
    await page.locator('#ce-native-access').selectOption({label:'Allow reviewed writes'});
    await page.getByRole('tab',{name:'Network',exact:true}).click();
    assert.deepEqual(await page.locator('#ce-topology option').allTextContents(),['standalone','sentinel','cluster']);
    await page.locator('#ce-topology').selectOption('sentinel');await page.locator('#ce-sentinelMaster').fill('cgraph');
    await page.locator('#ce-seeds').fill('redis://localhost:26380, redis://localhost:26381');
    const nativeDraft=await page.evaluate(async()=>{
      const {nativeConnectionDraft}=await import('/dba/native-connection-editor.js');
      return nativeConnectionDraft({template:{id:'redis-native',transport:'redis'},get:key=>document.getElementById('ce-'+key)?.value??'',shade:''});
    });
    assert.equal(nativeDraft.nativeOptions.sentinelMaster,'cgraph');
    assert.deepEqual(nativeDraft.nativeOptions.seeds,['redis://localhost:26380','redis://localhost:26381']);
    await page.getByRole('tab',{name:'Authentication & TLS',exact:true}).click();
    assert.equal(await page.locator('#ce-sentinelPassword').getAttribute('type'),'password');
    await page.locator('#ce-sentinelUsername').fill('sentinel-worker');
    await page.locator('#ce-sentinelPassword').fill('sentinel-browser-secret');
    const sentinelDraft=await page.evaluate(async()=>{
      const {nativeConnectionDraft}=await import('/dba/native-connection-editor.js');
      return nativeConnectionDraft({template:{id:'redis-native',transport:'redis'},get:key=>document.getElementById('ce-'+key)?.value??'',shade:'transparent'});
    });
    assert.equal(sentinelDraft.nativeOptions.sentinelUsername,'sentinel-worker');
    assert.equal(sentinelDraft.secretProperties.sentinelPassword,'sentinel-browser-secret');
    assert.equal(sentinelDraft.password,undefined,'Sentinel password must not replace the data password');
    await page.screenshot({path:'code-graph-dba/target/sentinel-auth-editor.png'});
    page.once('dialog',dialog=>dialog.accept());await page.locator('#ce-save-untested').click();
    await page.locator('#connection-editor').waitFor({state:'hidden'});
    const savedSentinel=page.getByRole('treeitem',{name:'Native Redis binary fixture',exact:true});
    await savedSentinel.getByRole('button',{name:'Actions for Native Redis binary fixture',exact:true}).click();
    await page.getByRole('menuitem',{name:'Edit Connection',exact:true}).click();
    await page.getByRole('tab',{name:'Authentication & TLS',exact:true}).click();
    assert.equal(await page.locator('#ce-sentinelPassword').inputValue(),'');
    assert.equal(await page.locator('#ce-sentinel-password-action').inputValue(),'Keep');
    assert.equal(await page.locator('#ce-sentinelUsername').inputValue(),'sentinel-worker');
    const visibleProfiles=await page.evaluate(async()=>JSON.stringify(await(await fetch('/api/dba/connections')).json()));
    assert.equal(visibleProfiles.includes('sentinel-browser-secret'),false);
    await page.locator('#ce-sentinelUsername').fill('');
    await page.locator('#ce-sentinel-password-action').selectOption('Remove');
    await page.getByRole('tab',{name:'Network',exact:true}).click();
    await page.locator('#ce-topology').selectOption('standalone');await page.locator('#ce-sentinelMaster').fill('');await page.locator('#ce-seeds').fill('');
    await page.getByRole('tab',{name:'General',exact:true}).click();
    page.once('dialog',dialog=>dialog.accept());await page.locator('#ce-save-untested').click();
    await page.locator('#connection-editor').waitFor({state:'hidden'});
    const redis=page.getByRole('treeitem',{name:'Native Redis binary fixture',exact:true});
    await redis.getByRole('button',{name:'Actions for Native Redis binary fixture',exact:true}).click();
    await page.getByRole('menuitem',{name:'Native workspace',exact:true}).click();
    assert.match(await page.locator('.native-command').getAttribute('title'),/base64/);
    const binaryCommand='["SET",{"base64":"/wA="},{"base64":"AP8B"}]';
    const beforeRedisApply=applied;
    await page.locator('.native-command').fill(binaryCommand);
    await page.route('**/api/dba/native/apply',async route=>{
      assert.ok(route.request().postDataJSON().planId);applied++;
      await route.fulfill({json:{id:'native-browser-binary'}});
    });
    await page.route('**/api/dba/jobs/native-browser-binary',route=>route.fulfill({json:route.request().method()==='DELETE'?{}:{id:'native-browser-binary',state:'complete',finished:Date.now(),result:{kind:'values',entries:[{encoding:'binary',base64:'AP8B',previewBytes:3,truncated:false}],truncated:false}}}));
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();
    assert.match(await review.innerText(),/Native Redis binary fixture/);
    assert.match(await review.innerText(),/AP8B/);assert.match(await review.innerText(),/\/wA=/);
    assert.equal(applied,beforeRedisApply,'Binary commands must still wait for exact review');
    await review.getByRole('button',{name:'Apply once',exact:true}).click();
    await page.locator('.native-status').filter({hasText:'Complete'}).waitFor();assert.equal(applied,beforeRedisApply+1);
    assert.match(await page.locator('.native-result').innerText(),/AP8B/);
    await page.waitForFunction(async()=>{const r=await fetch('/api/dba/workspace');return(await r.json()).tabs.some(t=>t.type==='native'&&t.commandText.includes('AP8B'));});
    await page.reload();await page.locator('.native-workspace').waitFor();
    assert.equal(await page.locator('.native-command').inputValue(),binaryCommand);assert.equal(applied,beforeRedisApply+1);
    const transaction={transaction:[['SET','{review}:one','value'],['DEL','{review}:one']],watch:[{key:'{review}:one',expected:null}]};
    await page.locator('.native-command').fill(JSON.stringify(transaction));
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();
    assert.match(await review.innerText(),/Review destructive database change/);assert.match(await review.innerText(),/does not roll back/);
    assert.match(await review.innerText(),/expected/);assert.equal(applied,beforeRedisApply+1);
    await review.getByRole('button',{name:'Cancel',exact:true}).click();await review.waitFor({state:'hidden'});assert.equal(applied,beforeRedisApply+1);
    await page.route('**/api/dba/jobs/native-browser-binary',route=>route.fulfill({json:route.request().method()==='DELETE'?{}:{id:'native-browser-binary',state:'failed',finished:Date.now(),error:'Redis transaction partially failed; inspect per-command results',result:{kind:'transaction',outcome:'partial',rollbackSupported:false,entries:[{index:0,state:'acknowledged',value:'OK'},{index:1,state:'failed',error:'Rejected during EXEC'}]}}}));
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();
    await review.getByRole('button',{name:'Apply once',exact:true}).click();
    await page.locator('.native-status').filter({hasText:'partially failed'}).waitFor();assert.equal(applied,beforeRedisApply+2);
    assert.match(await page.locator('.native-result').innerText(),/acknowledged/);assert.match(await page.locator('.native-result').innerText(),/rollbackSupported/);
    assert.equal(await page.locator('.native-command').inputValue(),JSON.stringify(transaction),'Failure retains the exact transaction draft');
    const examples=page.getByRole('combobox',{name:'Redis stream command example'});
    page.once('dialog',dialog=>dialog.dismiss());await examples.selectOption({label:'Read consumer group'});assert.equal(await page.locator('.native-command').inputValue(),JSON.stringify(transaction));
    page.once('dialog',dialog=>dialog.accept());await examples.selectOption({label:'Read consumer group'});
    assert.deepEqual(JSON.parse(await page.locator('.native-command').inputValue()),['XREADGROUP','GROUP','group','consumer','COUNT','100','STREAMS','stream','>']);
    assert.equal(applied,beforeRedisApply+2,'Loading a stream example must not execute it');
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();
    assert.match(await review.innerText(),/pending\/delivery state/);assert.match(await review.innerText(),/NOACK/);assert.equal(await examples.isDisabled(),true);
    await review.getByRole('button',{name:'Cancel',exact:true}).click();await review.waitFor({state:'hidden'});assert.equal(applied,beforeRedisApply+2);
    await page.route('**/api/dba/jobs/native-browser-binary',route=>route.fulfill({json:route.request().method()==='DELETE'?{}:{id:'native-browser-binary',state:'complete',finished:Date.now(),result:{kind:'stream',operation:'XREADGROUP',entries:[{id:'1-0',fields:[{field:{text:'name'},value:{base64:'AP8=',encoding:'binary'}}]}],deliveredIds:['1-0'],acknowledgementRequired:true,automaticAcknowledgement:false}}}));
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();await review.getByRole('button',{name:'Apply once',exact:true}).click();
    await page.locator('.native-status').filter({hasText:'acknowledgement is a separate reviewed command'}).waitFor();assert.equal(applied,beforeRedisApply+3);assert.equal(await examples.isEnabled(),true);
    assert.match(await page.locator('.native-result').innerText(),/deliveredIds/);assert.match(await page.locator('.native-result').innerText(),/1-0/);
    await page.setViewportSize({width:800,height:700});assert.equal(await page.locator('.native-workspace-actions').evaluate(node=>node.scrollWidth<=node.clientWidth),true,'Stream controls wrap without toolbar overflow');await page.setViewportSize({width:1440,height:900});
    await page.screenshot({path:'code-graph-dba/target/redis-stream-workspace.png'});
    const retained=await page.evaluate(async()=>{
      const {NativeWorkspace}=await import('/dba/native-workspace.js');let allocation=0,applies=0;
      const state={database:'0',commandText:JSON.stringify(['XREADGROUP','GROUP','g','c','COUNT','1','STREAMS','s','>'])};
      const api=async(path,method)=>{if(path==='/native/prepare')return{id:'review',mutation:true};if(path==='/native/apply'){applies++;return{id:'job'};}if(path==='/jobs/job'&&method!=='DELETE')return{state:'complete',finished:1,result:{kind:'stream',outcome:'acknowledged',deliveredIds:['1-0'],acknowledgementRequired:true,entries:[{value:'x'.repeat(300000)}]}};return{};};
      const view=new NativeWorkspace({api,profile:{id:'fixture',name:'Fixture',transport:'redis'},state,changed:()=>{},account:bytes=>{if(bytes>700000)throw Error('Browser result allowance full');allocation=bytes;}});
      view.confirmMutation=async()=>true;view.viewName='grid';await view.run();const receipt=JSON.parse(view.result.textContent),kept=allocation,viewName=view.viewName,gridDisabled=view.viewButtons.grid.disabled;view.dispose();
      let rejectedCalls=0;const refused=new NativeWorkspace({api:async()=>{rejectedCalls++;return{};},profile:{transport:'redis'},state,changed:()=>{},account:bytes=>{if(bytes>0)throw Error('Full');}});await refused.run();const refusedStatus=refused.status.textContent;refused.dispose();
      return{receipt,kept,allocation,applies,rejectedCalls,refusedStatus,viewName,gridDisabled};
    });
    assert.equal(retained.applies,1);assert.deepEqual(retained.receipt.deliveredIds,['1-0']);assert.equal(retained.receipt.outcome,'acknowledged');assert.equal(retained.receipt.truncationReason,'browser_memory_limit');assert.equal(retained.receipt.automaticAcknowledgement,false);assert.ok(retained.kept<512*1024);assert.equal(retained.allocation,0);assert.equal(retained.rejectedCalls,0);assert.match(retained.refusedStatus,/Not started/);
    assert.equal(retained.viewName,'json');assert.equal(retained.gridDisabled,true);
    assert.deepEqual(errors,[]);
    await page.screenshot({path:'code-graph-dba/target/native-workspace.png'});
    console.log('Native browser checks passed: picker, setup, exact targets, typed JSON/grid, safe rendering, reusable layout, recovery, review/cancel/apply, finite change-stream continuation, Redis stream examples/explicit ACK notices, binary Redis commands and removed-connection cleanup.');
  }catch(error){console.error('Native browser diagnostics',errors,await page.locator('#toast').textContent().catch(()=>''));await page.screenshot({path:'code-graph-dba/target/native-failure.png'}).catch(()=>{});throw error;}finally{await context.close();}
};
