const assert=require('node:assert/strict');
module.exports=async(browser,base)=>{
  const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),errors=[];
  page.on('pageerror',error=>errors.push(error.message));let queryCount=0;
  try{
    await page.goto(base+'/dba');await page.locator('#add').waitFor();
    await page.locator('#add').click();await page.getByRole('button',{name:'MongoDB',exact:true}).click();
    await page.locator('#ce-url').waitFor();
    assert.equal(await page.locator('#ce-url').inputValue(),'mongodb://localhost:27017');
    assert.equal(await page.locator('#driver-choice').isVisible(),false);assert.equal(await page.locator('#ce-jars').count(),0);
    await page.getByRole('tab',{name:'Driver',exact:true}).click();
    assert.match(await page.locator('#ce-panel-1').innerText(),/bundled native client/);
    await page.getByRole('tab',{name:'General',exact:true}).click();await page.locator('#ce-name').fill('Native Mongo fixture');
    await page.locator('#ce-database').fill('app');await page.locator('#ce-native-access').selectOption({label:'Allow reviewed writes'});page.once('dialog',dialog=>dialog.accept());await page.locator('#ce-save-untested').click();
    await page.locator('#connection-editor').waitFor({state:'hidden'});
    const mongo=page.getByRole('treeitem',{name:'Native Mongo fixture',exact:true});await mongo.waitFor();
    await page.route('**/api/dba/native/tree',async route=>{
      const input=route.request().postDataJSON();let nodes=[];
      if(input.kind==='root')nodes=[{key:'database:app',kind:'native_database',name:'app',database:'app',branch:true}];
      if(input.kind==='native_database')nodes=[{key:'collections:Collections',kind:'native_collections',name:'Collections',database:'app',branch:true}];
      if(input.kind==='native_collections')nodes=[{key:'collection:items',kind:'native_collection',name:'items',database:'app',collection:'items',branch:true,nativeObject:true,command:{find:'items',filter:{},limit:100}}];
      await route.fulfill({json:{id:'native-tree-'+input.kind,state:'complete',result:{nodes}}});
      await page.route('**/api/dba/jobs/native-tree-'+input.kind,job=>job.fulfill({json:job.request().method()==='DELETE'?{}:{id:'native-tree-'+input.kind,state:'complete',finished:Date.now(),result:{nodes}}}));
    });
    await mongo.getByRole('button',{name:'Expand Native Mongo fixture',exact:true}).click();
    await mongo.getByRole('button',{name:'Expand app',exact:true}).click();
    await mongo.getByRole('button',{name:'Expand Collections',exact:true}).click();
    const items=mongo.getByRole('treeitem',{name:'items',exact:true});
    await items.getByRole('button',{name:'items',exact:true}).dblclick();await page.locator('.native-workspace').waitFor();
    assert.equal(await page.locator('.native-workspace input[aria-label=Collection]').inputValue(),'items');
    assert.match(await page.locator('.native-command').inputValue(),/"find": "items"/);
    await mongo.getByRole('button',{name:'Actions for Native Mongo fixture',exact:true}).click();
    await page.getByRole('menuitem',{name:'Native workspace',exact:true}).click();await page.locator('.native-workspace').waitFor();
    assert.equal(await page.locator('#document').isHidden(),true);assert.equal(await page.locator('#file-save').isDisabled(),true);
    await page.locator('.native-workspace input[aria-label=Collection]').fill('items');
    const command='{"find":"items","filter":{"date":{"$gte":{"$date":"2026-09-01T00:00:00Z"}}},"limit":3}';
    await page.locator('.native-command').fill(command);
    await page.route('**/api/dba/native/execute',async route=>{
      const body=route.request().postDataJSON();assert.equal(body.database,'app');assert.equal(body.collection,'items');assert.equal(body.command.find,'items');queryCount++;
      await route.fulfill({json:{id:'native-browser-job'}});
    });
    await page.route('**/api/dba/jobs/native-browser-job',route=>route.fulfill({json:route.request().method()==='DELETE'?{}:{id:'native-browser-job',state:'complete',finished:Date.now(),result:{kind:'documents',entries:[{name:'<script>never execute</script>',id:{$numberLong:'9007199254740993'}}],truncated:false}}}));
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await page.getByRole('status').filter({hasText:'Complete'}).waitFor();
    assert.equal(queryCount,1);assert.match(await page.locator('.native-result').innerText(),/9007199254740993/);assert.equal(await page.locator('.native-result script').count(),0);
    const gridTab=page.locator('.native-workspace').getByRole('tab',{name:'Grid',exact:true});
    const jsonTab=page.locator('.native-workspace').getByRole('tab',{name:'JSON',exact:true});
    await gridTab.click();await page.locator('.native-workspace .data-grid-scroll').waitFor();
    assert.equal(await page.locator('.native-workspace .grid-source-preview').isVisible(),false);
    assert.equal(await page.locator('.native-workspace .grid-column-toggle').count(),0);
    assert.match(await page.locator('.native-workspace [role=grid]').innerText(),/9007199254740993/);
    assert.equal(await page.locator('.native-workspace [role=grid] script').count(),0);
    const header=page.locator('.native-workspace .data-column-header').first();await header.focus();await page.keyboard.press('Alt+ArrowRight');
    assert.equal(await page.locator('.native-workspace .grid-column-label').first().innerText(),'id');
    const resize=page.locator('.native-workspace .column-resize').first(),width=Number(await resize.getAttribute('aria-valuenow'));
    await resize.focus();await page.keyboard.press('ArrowRight');assert.equal(Number(await resize.getAttribute('aria-valuenow')),width+10);
    await jsonTab.click();await gridTab.click();assert.equal(await page.locator('.native-workspace .grid-column-label').first().innerText(),'id');
    assert.equal(queryCount,1,'Changing result display must not execute anything');
    await page.screenshot({path:'code-graph-dba/target/native-grid.png'});
    const projection=await page.evaluate(async()=>{
      const {nativeGridModel}=await import('/dba/native-workspace.js');
      const model=nativeGridModel([{nullable:null,large:{$numberLong:'9007199254740993'}},{}]);
      const wide=nativeGridModel([Object.fromEntries(Array.from({length:300},(_,i)=>['field'+i,i]))]);
      return{rows:model.rows,columns:wide.columns.length,omitted:wide.omittedColumns};
    });
    assert.deepEqual(projection.rows,[['null','{"$numberLong":"9007199254740993"}'],['[missing]','[missing]']]);
    assert.equal(projection.columns,256);assert.equal(projection.omitted,true);
    await jsonTab.click();
    await page.waitForFunction(async()=>{const r=await fetch('/api/dba/workspace');return(await r.json()).tabs.some(t=>t.type==='native'&&t.commandText.includes('"items"'));});
    await page.reload();await page.locator('.native-workspace').waitFor();assert.equal(await page.locator('.native-command').inputValue(),command);assert.equal(queryCount,1);
    assert.match(await page.locator('.native-result').innerText(),/Run a command/);
    const mutation='{"insert":"items","documents":[{"name":"review-only"}]}';let applied=0;
    await page.locator('.native-command').fill(mutation);
    await page.route('**/api/dba/native/apply',async route=>{
      assert.ok(route.request().postDataJSON().planId);applied++;
      await route.fulfill({json:{id:'native-browser-job'}});
    });
    await page.getByRole('button',{name:'Run native command',exact:true}).click();
    const review=page.getByRole('dialog',{name:'Review native database change'});await review.waitFor();
    assert.match(await review.innerText(),/Native Mongo fixture/);assert.match(await review.innerText(),/review-only/);
    assert.equal(applied,0);await review.getByRole('button',{name:'Cancel',exact:true}).click();
    await review.waitFor({state:'hidden'});assert.equal(applied,0);
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();
    await review.getByRole('button',{name:'Apply once',exact:true}).click();
    await page.locator('.native-status').filter({hasText:'Complete'}).waitFor();assert.equal(applied,1);
    await mongo.getByRole('button',{name:'Actions for Native Mongo fixture',exact:true}).click();
    await page.getByRole('menuitem',{name:'Delete',exact:true}).click();await page.locator('#remove-connection-dialog').waitFor();
    await page.locator('#remove-connection-confirm').click();await page.locator('#remove-connection-dialog').waitFor({state:'hidden'});
    await page.locator('.native-status').filter({hasText:'Connection removed'}).waitFor();
    assert.equal(await page.getByRole('button',{name:'Run native command',exact:true}).isDisabled(),true);
    assert.equal(await page.locator('.native-command').inputValue(),mutation);
    await page.reload();await page.getByRole('status').filter({hasText:'Connection removed'}).waitFor();
    assert.match(await page.locator('#table-document').innerText(),/review-only/);
    await page.unroute('**/api/dba/native/execute');await page.unroute('**/api/dba/native/apply');
    await page.locator('#add').click();await page.getByRole('button',{name:'Redis',exact:true}).click();
    await page.locator('#ce-name').fill('Native Redis binary fixture');await page.locator('#ce-database').fill('0');
    await page.locator('#ce-native-access').selectOption({label:'Allow reviewed writes'});
    page.once('dialog',dialog=>dialog.accept());await page.locator('#ce-save-untested').click();
    await page.locator('#connection-editor').waitFor({state:'hidden'});
    const redis=page.getByRole('treeitem',{name:'Native Redis binary fixture',exact:true});
    await redis.getByRole('button',{name:'Actions for Native Redis binary fixture',exact:true}).click();
    await page.getByRole('menuitem',{name:'Native workspace',exact:true}).click();
    assert.match(await page.locator('.native-command').getAttribute('title'),/base64/);
    const binaryCommand='["SET",{"base64":"/wA="},{"base64":"AP8B"}]';
    await page.locator('.native-command').fill(binaryCommand);
    await page.route('**/api/dba/native/apply',async route=>{
      assert.ok(route.request().postDataJSON().planId);applied++;
      await route.fulfill({json:{id:'native-browser-binary'}});
    });
    await page.route('**/api/dba/jobs/native-browser-binary',route=>route.fulfill({json:route.request().method()==='DELETE'?{}:{id:'native-browser-binary',state:'complete',finished:Date.now(),result:{kind:'values',entries:[{encoding:'binary',base64:'AP8B',previewBytes:3,truncated:false}],truncated:false}}}));
    await page.getByRole('button',{name:'Run native command',exact:true}).click();await review.waitFor();
    assert.match(await review.innerText(),/Native Redis binary fixture/);
    assert.match(await review.innerText(),/AP8B/);assert.match(await review.innerText(),/\/wA=/);
    assert.equal(applied,1,'Binary commands must still wait for exact review');
    await review.getByRole('button',{name:'Apply once',exact:true}).click();
    await page.locator('.native-status').filter({hasText:'Complete'}).waitFor();assert.equal(applied,2);
    assert.match(await page.locator('.native-result').innerText(),/AP8B/);
    await page.waitForFunction(async()=>{const r=await fetch('/api/dba/workspace');return(await r.json()).tabs.some(t=>t.type==='native'&&t.commandText.includes('AP8B'));});
    await page.reload();await page.locator('.native-workspace').waitFor();
    assert.equal(await page.locator('.native-command').inputValue(),binaryCommand);assert.equal(applied,2);
    assert.deepEqual(errors,[]);
    await page.screenshot({path:'code-graph-dba/target/native-workspace.png'});
    console.log('Native browser checks passed: picker, setup, exact targets, typed JSON/grid, safe rendering, reusable layout, recovery, review/cancel/apply, binary Redis commands and removed-connection cleanup.');
  }catch(error){console.error('Native browser diagnostics',errors,await page.locator('#toast').textContent().catch(()=>''));await page.screenshot({path:'code-graph-dba/target/native-failure.png'}).catch(()=>{});throw error;}finally{await context.close();}
};
