package io.doindev.codegraph.dba;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.sql.*;
import java.util.*;

/** Exact JDBC scalar parameters for PostgreSQL/MySQL, including OUT/INOUT results. */
final class NativeParameters {
    static final Map<String,Integer> TYPES=Map.ofEntries(Map.entry("VARCHAR",Types.VARCHAR),Map.entry("NVARCHAR",Types.NVARCHAR),Map.entry("NUMBER",Types.DECIMAL),Map.entry("DECIMAL",Types.DECIMAL),Map.entry("BIGINT",Types.BIGINT),Map.entry("INTEGER",Types.INTEGER),Map.entry("BOOLEAN",Types.BOOLEAN),Map.entry("DATE",Types.DATE),Map.entry("TIME",Types.TIME),Map.entry("TIMESTAMP",Types.TIMESTAMP),Map.entry("TIMESTAMP_WITH_TIMEZONE",Types.TIMESTAMP_WITH_TIMEZONE),Map.entry("BINARY",Types.VARBINARY));
    static void shape(JsonNode values){if(values==null||!values.isArray()||values.size()>128)throw new IllegalArgumentException("parameters must be an array of at most 128 values");for(JsonNode value:values){if(!value.isObject()){HumanSql.checkParameters(Profiles.JSON.createArrayNode().add(value));continue;}value.fieldNames().forEachRemaining(key->{if(!Set.of("mode","type","value").contains(key))throw new IllegalArgumentException("Unknown parameter field");});String mode=value.path("mode").asText(),type=value.path("type").asText();if(!Set.of("in","out","inout").contains(mode)||!TYPES.containsKey(type)&&!OracleSql.TYPES.containsKey(type))throw new IllegalArgumentException("Unsupported typed parameter mode/type");if(mode.equals("out")&&value.has("value")||!mode.equals("out")&&!value.has("value"))throw new IllegalArgumentException("IN/INOUT requires a value; OUT cannot contain a value");if(value.has("value"))HumanSql.checkParameters(Profiles.JSON.createArrayNode().add(value.get("value")));}}
    static void check(JsonNode values,String engine){shape(values);for(JsonNode value:values)if(value.isObject()){String type=value.path("type").asText();if(!TYPES.containsKey(type)||MysqlDialect.supports(engine)&&type.equals("TIMESTAMP_WITH_TIMEZONE"))throw new IllegalArgumentException("Unsupported native parameter type for "+engine);if(!value.path("mode").asText().equals("out")&&!value.path("value").isNull())value(type,value.path("value").asText());}}
    private static Object value(String type,String text){try{return switch(type){case "NUMBER","DECIMAL"->{var number=new java.math.BigDecimal(text);if(number.precision()>8192||Math.abs((long)number.scale())>8192)throw new IllegalArgumentException("Numeric parameter exceeds the exact value allowance");yield number;}case "BIGINT"->Long.valueOf(text);case "INTEGER"->Integer.valueOf(text);case "BOOLEAN"->{if(!Set.of("true","false").contains(text))throw new IllegalArgumentException("Boolean parameters require true/false");yield Boolean.valueOf(text);}case "DATE"->java.time.LocalDate.parse(text);case "TIME"->java.time.LocalTime.parse(text);case "TIMESTAMP"->java.time.LocalDateTime.parse(text.replace(' ','T'));case "TIMESTAMP_WITH_TIMEZONE"->java.time.OffsetDateTime.parse(text);case "BINARY"->HexFormat.of().parseHex(text);default->text;};}catch(RuntimeException invalid){throw new IllegalArgumentException("Invalid exact "+type+" parameter value");}}
    static void bind(PreparedStatement statement,int index,JsonNode parameter)throws SQLException{String name=parameter.path("type").asText(),mode=parameter.path("mode").asText();int type=TYPES.get(name);if(!mode.equals("in"))((CallableStatement)statement).registerOutParameter(index,type);if(mode.equals("out"))return;JsonNode input=parameter.path("value");if(input.isNull()){statement.setNull(index,type);return;}Object value=value(name,input.asText());if(value instanceof java.math.BigDecimal number)statement.setBigDecimal(index,number);else if(value instanceof byte[] bytes)statement.setBytes(index,bytes);else if(value instanceof String text)statement.setString(index,text);else statement.setObject(index,value,type);}
    static ObjectNode output(CallableStatement statement,int index,JsonNode parameter)throws Exception{String type=parameter.path("type").asText();ObjectNode out=Profiles.JSON.createObjectNode().put("type",type);String value;if(Set.of("NUMBER","DECIMAL").contains(type)){var number=statement.getBigDecimal(index);if(number!=null&&(number.precision()>8192||Math.abs((long)number.scale())>8192))throw new IllegalArgumentException("Output number exceeds the exact value allowance");value=number==null?null:number.toPlainString();}else if(type.equals("BINARY")){var blob=statement.getBlob(index);if(blob==null)value=null;else try{if(blob.length()>8192)throw new IllegalArgumentException("Output binary parameter exceeds 8 KiB");try(var stream=blob.getBinaryStream()){byte[] bytes=stream.readNBytes(8193);if(bytes.length>8192)throw new IllegalArgumentException("Output binary parameter exceeds 8 KiB");value=HexFormat.of().formatHex(bytes);}}finally{blob.free();}}else if(!Set.of("VARCHAR","NVARCHAR").contains(type)){value=statement.getString(index);if(value!=null&&value.length()>8192)throw new IllegalArgumentException("Output parameter exceeds 8 KiB");}else{try(var reader=statement.getCharacterStream(index)){if(reader==null)value=null;else{StringBuilder text=new StringBuilder();char[] buffer=new char[1024];int n;while((n=reader.read(buffer))!=-1){if(text.length()+n>8192)throw new IllegalArgumentException("Output parameter exceeds 8 KiB");text.append(buffer,0,n);}value=text.toString();}}}return value==null?out.putNull("value"):out.put("value",value);}
    private NativeParameters(){}
}
