package io.doindev.codegraph.dba;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.*;
import java.sql.Connection;
import java.util.*;
import static io.doindev.codegraph.dba.CompareCatalog.*;

/** PostgreSQL dependency rebuilds and native auxiliary definitions. */
final class PostgresCompare {
    static void capture(QueryJobs.Job job,Connection c,ObjectNode object)throws Exception{
        String kind=str(object,"kind"),oid=str(object,"oid");if(!oid.matches("[0-9]+"))return;
        String catalog=Set.of("functions","procedures").contains(kind)?"pg_proc":Set.of("types","domains").contains(kind)?"pg_type":"pg_class";
        var extension=query(job,c,"SELECT e.extname FROM pg_depend d JOIN pg_extension e ON e.oid=d.refobjid WHERE d.classid=?::regclass AND d.objid=?::oid AND d.deptype='e'",catalog,oid);
        if(!extension.isEmpty()){object.put("supported",false).put("reason","Extension-owned object: manage extension "+extension.path(0).path("extname").asText()+" as a unit");return;}
        if(Set.of("tables","views","materialized_views").contains(kind)){
            var row=query(job,c,"SELECT pg_get_userbyid(c.relowner) AS owner,COALESCE(obj_description(c.oid,'pg_class'),'') AS comment,c.relrowsecurity,c.relforcerowsecurity,COALESCE(array_to_string(c.reloptions,','),'') AS options,COALESCE(t.spcname,'') AS tablespace FROM pg_class c LEFT JOIN pg_tablespace t ON t.oid=c.reltablespace WHERE c.oid=?::oid",oid).path(0);object.set("postgresAttributes",row);
            if(kind.equals("tables")){
                var partition=query(job,c,"SELECT COALESCE(pg_get_partkeydef(c.oid),'') AS key,COALESCE(pg_get_expr(c.relpartbound,c.oid),'') AS bound,COALESCE(n.nspname,'') AS schema,COALESCE(parent.relname,'') AS parent FROM pg_class c LEFT JOIN pg_inherits i ON i.inhrelid=c.oid LEFT JOIN pg_class parent ON parent.oid=i.inhparent LEFT JOIN pg_namespace n ON n.oid=parent.relnamespace WHERE c.oid=?::oid",oid).path(0);
                if(!str(partition,"key").isBlank()||!str(partition,"bound").isBlank()) {object.set("postgresPartition",partition);object.put("dataSupported",false).put("dataReason","Partition families require a separate row-routing migration; compare definitions only");if(!object.path("constraints").isEmpty()||!object.path("indexes").isEmpty()||!object.path("triggers").isEmpty())throw new IllegalArgumentException("Partition families with constraints, indexes or triggers need a dedicated propagation plan");}
            }
            if(kind.equals("tables")){object.set("postgresStorage",query(job,c,"SELECT relpersistence::text AS persistence,COALESCE(s.spcname,'') AS tablespace FROM pg_class c LEFT JOIN pg_tablespace s ON s.oid=c.reltablespace WHERE c.oid=?::oid",oid).path(0));object.set("storageOptions",query(job,c,"SELECT split_part(option,'=',1) AS name,substring(option FROM position('=' IN option)+1) AS value FROM pg_class c CROSS JOIN LATERAL unnest(c.reloptions) option WHERE c.oid=?::oid ORDER BY name",oid));}

            object.set("postgresGrants",query(job,c,"SELECT CASE a.grantee WHEN 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END AS grantee,pg_get_userbyid(a.grantor) AS grantor,a.privilege_type,a.is_grantable FROM pg_class c CROSS JOIN LATERAL aclexplode(COALESCE(c.relacl,acldefault('r',c.relowner))) a WHERE c.oid=?::oid ORDER BY grantee,privilege_type,is_grantable",oid));
            object.set("postgresColumnGrants",query(job,c,"SELECT p.attname AS column_name,CASE a.grantee WHEN 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END AS grantee,pg_get_userbyid(a.grantor) AS grantor,a.privilege_type,a.is_grantable FROM pg_attribute p CROSS JOIN LATERAL aclexplode(p.attacl) a WHERE p.attrelid=?::oid AND p.attnum>0 AND NOT p.attisdropped ORDER BY column_name,grantee,privilege_type,is_grantable",oid));
            object.set("postgresColumnComments",query(job,c,"SELECT attname AS name,COALESCE(col_description(attrelid,attnum),'') AS comment FROM pg_attribute WHERE attrelid=?::oid AND attnum>0 AND NOT attisdropped ORDER BY attnum",oid));
            if(kind.equals("materialized_views"))object.set("postgresIndexes",query(job,c,"SELECT c.relname AS name,pg_get_indexdef(i.indexrelid) AS definition FROM pg_index i JOIN pg_class c ON c.oid=i.indexrelid WHERE i.indrelid=?::oid ORDER BY c.relname",oid));
            if(kind.equals("tables")){
                object.set("triggers",query(job,c,"SELECT tgname AS name,pg_get_triggerdef(oid) AS definition,tgenabled::text AS enabled FROM pg_trigger WHERE tgrelid=?::oid AND NOT tgisinternal ORDER BY tgname",oid));
                object.set("rules",query(job,c,"SELECT rulename AS name,pg_get_ruledef(oid) AS definition FROM pg_rewrite WHERE ev_class=?::oid AND rulename<>'_RETURN' ORDER BY rulename",oid));
                object.set("policies",query(job,c,"SELECT p.polname AS name,p.polcmd::text AS command,p.polpermissive,COALESCE(pg_get_expr(p.polqual,p.polrelid),'') AS using,COALESCE(pg_get_expr(p.polwithcheck,p.polrelid),'') AS check,(SELECT string_agg(CASE r WHEN 0 THEN 'PUBLIC' ELSE quote_ident(pg_get_userbyid(r)) END,', ' ORDER BY r) FROM unnest(p.polroles) r) AS roles FROM pg_policy p WHERE p.polrelid=?::oid ORDER BY p.polname",oid));
                if(truth(row.path("relrowsecurity"))||!object.path("triggers").isEmpty()||!object.path("rules").isEmpty())object.put("dataSupported",false).put("dataReason","Data synchronization with row security, triggers or rewrite rules requires explicit behavioral validation");
            }else if(!query(job,c,"SELECT 1 FROM pg_trigger WHERE tgrelid=?::oid AND NOT tgisinternal UNION ALL SELECT 1 FROM pg_rewrite WHERE ev_class=?::oid AND rulename<>'_RETURN'",oid,oid).isEmpty())object.put("supported",false).put("reason","View has custom triggers/rules requiring native rebuild review");
        }
        if(kind.equals("sequences")){
            object.set("postgresAttributes",query(job,c,"SELECT pg_get_userbyid(relowner) AS owner,COALESCE(obj_description(oid,'pg_class'),'') AS comment FROM pg_class WHERE oid=?::oid",oid).path(0));
            object.set("postgresGrants",query(job,c,"SELECT CASE a.grantee WHEN 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END AS grantee,pg_get_userbyid(a.grantor) AS grantor,a.privilege_type,a.is_grantable FROM pg_class s CROSS JOIN LATERAL aclexplode(COALESCE(s.relacl,acldefault('S',s.relowner))) a WHERE s.oid=?::oid ORDER BY grantee,privilege_type,is_grantable",oid));
        }
        if(Set.of("types","domains").contains(kind)){
            object.set("postgresAttributes",query(job,c,"SELECT pg_get_userbyid(typowner) AS owner,COALESCE(obj_description(oid,'pg_type'),'') AS comment FROM pg_type WHERE oid=?::oid",oid).path(0));
            object.set("postgresGrants",query(job,c,"SELECT CASE a.grantee WHEN 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END AS grantee,pg_get_userbyid(a.grantor) AS grantor,a.privilege_type,a.is_grantable FROM pg_type t CROSS JOIN LATERAL aclexplode(COALESCE(t.typacl,acldefault('T',t.typowner))) a WHERE t.oid=?::oid ORDER BY grantee,privilege_type,is_grantable",oid));
        }
        if(Set.of("functions","procedures").contains(kind)){
            object.set("postgresAttributes",query(job,c,"SELECT pg_get_userbyid(proowner) AS owner,COALESCE(obj_description(oid,'pg_proc'),'') AS comment FROM pg_proc WHERE oid=?::oid",oid).path(0));
            object.set("postgresGrants",query(job,c,"SELECT CASE a.grantee WHEN 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END AS grantee,pg_get_userbyid(a.grantor) AS grantor,a.privilege_type,a.is_grantable FROM pg_proc p CROSS JOIN LATERAL aclexplode(COALESCE(p.proacl,acldefault('f',p.proowner))) a WHERE p.oid=?::oid ORDER BY grantee,privilege_type,is_grantable",oid));
        }
        String owner=object.path("postgresAttributes").path("owner").asText();for(String grants:List.of("postgresGrants","postgresColumnGrants"))for(JsonNode grant:object.path(grants))if(!str(grant,"grantor").equals(owner))throw new IllegalArgumentException("Delegated grant chains require a separate privilege migration preserving grantor identity");
        if(Set.of("types","domains").contains(kind)){
            var info=query(job,c,"SELECT typtype::text,format_type(typbasetype,typtypmod) AS base,COALESCE(typdefault,'') AS default,typnotnull FROM pg_type WHERE oid=?::oid",oid).path(0);object.set("postgresType",info);
            if(str(info,"typtype").equals("e")){object.set("enumLabels",query(job,c,"SELECT enumlabel AS label FROM pg_enum WHERE enumtypid=?::oid ORDER BY enumsortorder",oid));List<String> labels=new ArrayList<>();object.path("enumLabels").forEach(label->labels.add(CompareData.literal(str(label,"label"),"postgresql")));object.put("ddl","CREATE TYPE "+CompareSql.qualified("postgresql",str(object,"schema"),str(object,"name"))+" AS ENUM ("+String.join(", ",labels)+")");}
            if(str(info,"typtype").equals("d")){object.set("domainConstraints",query(job,c,"SELECT conname AS name,pg_get_constraintdef(oid) AS definition FROM pg_constraint WHERE contypid=?::oid ORDER BY conname",oid));String ddl="CREATE DOMAIN "+CompareSql.qualified("postgresql",str(object,"schema"),str(object,"name"))+" AS "+str(info,"base")+(str(info,"default").isEmpty()?"":" DEFAULT "+str(info,"default"))+(truth(info.path("typnotnull"))?" NOT NULL":"");for(JsonNode constraint:object.path("domainConstraints"))ddl+=" CONSTRAINT "+TableDesigner.q(str(constraint,"name"))+" "+str(constraint,"definition");object.put("ddl",ddl).put("supported",true).put("reason","");}
        }
    }
    static void validate(QueryJobs.Job job,Connection c,CompareSql.Plan plan)throws Exception {
        Set<String> principals=new TreeSet<>(),spaces=new TreeSet<>();
        for(var choice:plan.selected.values()) {
            var source=choice.source();String owner=source.path("postgresAttributes").path("owner").asText();if(!owner.isEmpty())principals.add(owner);
            source.path("postgresGrants").forEach(g->{if(!str(g,"grantee").equals("PUBLIC"))principals.add(str(g,"grantee"));});source.path("postgresColumnGrants").forEach(g->{if(!str(g,"grantee").equals("PUBLIC"))principals.add(str(g,"grantee"));});
            for(JsonNode policy:source.path("policies"))for(var token:MysqlTableDefinition.tokens(str(policy,"roles"),true))if(!token.text().equals(",")&&!token.word().equals("PUBLIC"))principals.add(MysqlProgram.identifier(token));
            String tablespace=source.path("postgresAttributes").path("tablespace").asText();if(!tablespace.isBlank())spaces.add(tablespace);
            boolean created=choice.destination()==null||plan.rebuilt.contains(key(str(source,"schema"),str(source,"kind"),str(source,"name")));
            if(created&&source.has("postgresGrants")) {
                String kind=str(source,"kind"),aclType=Set.of("functions","procedures").contains(kind)?"f":kind.equals("sequences")?"S":Set.of("types","domains").contains(kind)?"T":"r",type=kind.equals("functions")?"FUNCTION":kind.equals("procedures")?"PROCEDURE":kind.equals("sequences")?"SEQUENCE":Set.of("types","domains").contains(kind)?"TYPE":"TABLE";
                String target=Set.of("FUNCTION","PROCEDURE").contains(type)?routineTarget(plan,source):plan.target(source);Set<String> handled=new HashSet<>();source.path("postgresGrants").forEach(g->handled.add(str(g,"grantee")));
                for(JsonNode grant:query(job,c,"SELECT DISTINCT CASE a.grantee WHEN 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END AS grantee FROM pg_default_acl d CROSS JOIN LATERAL aclexplode(d.defaclacl) a WHERE d.defaclrole=(SELECT oid FROM pg_roles WHERE rolname=current_user) AND d.defaclobjtype::text=? AND (d.defaclnamespace=0 OR d.defaclnamespace=(SELECT oid FROM pg_namespace WHERE nspname=?))",aclType,plan.schema(str(source,"schema")))) {
                    String grantee=str(grant,"grantee");if(handled.add(grantee))plan.after.add("REVOKE ALL PRIVILEGES ON "+type+" "+target+" FROM "+(grantee.equals("PUBLIC")?"PUBLIC":TableDesigner.q(grantee)));
                }
            }
        }
        for(String role:principals)if(query(job,c,"SELECT 1 FROM pg_roles WHERE rolname=?",role).size()!=1)throw new IllegalArgumentException("Destination role is unavailable: "+role+". Review role provisioning before generation.");
        for(String space:spaces)if(query(job,c,"SELECT 1 FROM pg_tablespace WHERE spcname=? AND has_tablespace_privilege(oid,'CREATE')",space).size()!=1)throw new IllegalArgumentException("Destination tablespace or CREATE privilege is unavailable: "+space);
    }
    static boolean rebuild(CompareSql.Plan plan,CompareSql.Choice choice){if(choice.destination()==null)return false;String kind=str(choice.source(),"kind");return kind.equals("materialized_views")&&!CompareSql.same(plan,choice.source(),choice.destination())||kind.equals("views")&&!CompareSql.mappedNode(plan,choice.source().path("columnSignature")).equals(choice.destination().path("columnSignature"))||Set.of("functions","procedures").contains(kind)&&!CompareSql.mappedNode(plan,choice.source().path("signature")).equals(choice.destination().path("signature"));}
    static void prepareRebuilds(CompareSql.Plan plan){
        Set<String> changedRoots=new HashSet<>();for(var entry:plan.selected.entrySet()){var choice=entry.getValue();if(rebuild(plan,choice)){plan.rebuilt.add(entry.getKey());changedRoots.add(entry.getKey());}if(str(choice.source(),"kind").equals("tables")&&choice.destination()!=null&&!CompareSql.columnShape(plan,choice.source(),true).equals(CompareSql.columnShape(plan,choice.destination(),false)))changedRoots.add(entry.getKey());}
        boolean changed=true;while(changed){changed=false;for(var destination:plan.destination.objects.values()){
            if(destination.path("implicit").asBoolean()||str(destination,"kind").equals("indexes"))continue;String sourceKey=plan.sourceKeyForDestination(destination);if(plan.rebuilt.contains(sourceKey))continue;
            boolean incoming=false;for(JsonNode dependency:destination.path("dependencies")){var ref=plan.destination.objects.get(dependency.asText());if(ref!=null&&changedRoots.contains(plan.sourceKeyForDestination(ref)))incoming=true;}
            if(!incoming)continue;if(!Set.of("views","materialized_views").contains(str(destination,"kind")))throw new IllegalArgumentException("Dependent "+str(destination,"name")+" needs a separate transition before changing its dependency");
            var source=plan.source.objects.get(sourceKey);if(source==null||!source.path("supported").asBoolean())throw new IllegalArgumentException("Cannot safely rebuild destination dependent "+str(destination,"name")+" without its supported source definition");
            plan.selected.putIfAbsent(sourceKey,new CompareSql.Choice(source,destination,Profiles.JSON.createObjectNode()));plan.rebuilt.add(sourceKey);changedRoots.add(sourceKey);changed=true;
        }}
        for(var choice:plan.selected.values())for(JsonNode dependency:choice.source().path("dependencies")){var required=plan.selected.get(dependency.asText());if(required==null)continue;String kind=str(choice.source(),"kind"),needed=str(required.source(),"kind");boolean unavailable=required.destination()==null||plan.rebuilt.contains(dependency.asText());if(unavailable&&(Set.of("types","domains").contains(kind)&&!Set.of("types","domains").contains(needed)||Set.of("functions","procedures").contains(kind)&&Set.of("views","materialized_views").contains(needed)))throw new IllegalArgumentException(str(choice.source(),"name")+": dependency "+str(required.source(),"name")+" crosses native creation phases; use a dedicated staged migration");}
        var ordered=CompareSql.order(plan);Collections.reverse(ordered);for(var choice:ordered)if(plan.rebuilt.contains(key(str(choice.source(),"schema"),str(choice.source(),"kind"),str(choice.source(),"name")))){CompareSql.requireDestructive(plan,"Rebuild "+str(choice.source(),"name"));String kind=str(choice.source(),"kind");String type=switch(kind){case "views"->"VIEW";case "materialized_views"->"MATERIALIZED VIEW";case "functions"->"FUNCTION";case "procedures"->"PROCEDURE";default->throw new IllegalArgumentException("Unsupported rebuild");};String target=Set.of("functions","procedures").contains(kind)?routineTarget(plan,choice.source()):plan.target(choice.source());plan.before.add("DROP "+type+" "+target+" RESTRICT");}
    }
    static String routineTarget(CompareSql.Plan plan,JsonNode source){return CompareSql.qualified("postgresql",plan.schema(str(source,"schema")),source.path("fields").path("name").asText(str(source,"name").replaceFirst("\\(.*$","")))+"("+plan.mapped(str(source,"routineIdentity"))+")";}
    static void type(CompareSql.Plan plan,CompareSql.Choice choice){var source=choice.source();var dest=choice.destination();String target=plan.target(source);if(dest==null){plan.before.add(plan.mapped(str(source,"ddl")));return;}String kind=str(source.path("postgresType"),"typtype");
        if(kind.equals("e")&&kind.equals(str(dest.path("postgresType"),"typtype"))){List<String> before=new ArrayList<>(),after=new ArrayList<>();dest.path("enumLabels").forEach(x->before.add(str(x,"label")));source.path("enumLabels").forEach(x->after.add(str(x,"label")));if(after.size()<before.size()||!after.subList(0,before.size()).equals(before))throw new IllegalArgumentException("Removing, renaming or reordering enum labels requires an explicit data conversion");for(String label:after.subList(before.size(),after.size()))plan.prelude.add("ALTER TYPE "+target+" ADD VALUE "+CompareData.literal(label,"postgresql"));return;}
        if(kind.equals("d")&&kind.equals(str(dest.path("postgresType"),"typtype"))){var a=source.path("postgresType");var b=dest.path("postgresType");if(!plan.mapped(str(a,"base")).equals(str(b,"base")))throw new IllegalArgumentException("Domain base-type changes require an explicit data conversion");if(!str(a,"default").equals(str(b,"default")))plan.before.add("ALTER DOMAIN "+target+(str(a,"default").isEmpty()?" DROP DEFAULT":" SET DEFAULT "+plan.mapped(str(a,"default"))));if(truth(a.path("typnotnull"))!=truth(b.path("typnotnull"))){CompareSql.requireDestructive(plan,"Change domain nullability");plan.before.add("ALTER DOMAIN "+target+(truth(a.path("typnotnull"))?" SET NOT NULL":" DROP NOT NULL"));}var old=CompareSql.byName(dest.path("domainConstraints"));var next=CompareSql.byName(source.path("domainConstraints"));for(var entry:old.entrySet())if(!Objects.equals(entry.getValue(),next.get(entry.getKey()))){CompareSql.requireDestructive(plan,"Replace domain constraint "+entry.getKey());plan.before.add("ALTER DOMAIN "+target+" DROP CONSTRAINT "+TableDesigner.q(entry.getKey()));}for(var entry:next.entrySet())if(!Objects.equals(entry.getValue(),old.get(entry.getKey())))plan.before.add("ALTER DOMAIN "+target+" ADD CONSTRAINT "+TableDesigner.q(entry.getKey())+" "+plan.mapped(str(entry.getValue(),"definition")));return;}
        throw new IllegalArgumentException("This type transition requires a native conversion plan");
    }
    static void tableAuxiliary(CompareSql.Plan plan,CompareSql.Choice choice){var source=choice.source();var dest=choice.destination();String target=plan.target(source);
        for(String family:List.of("triggers","rules","policies")){var before=dest==null?Map.<String,JsonNode>of():CompareSql.byName(dest.path(family));var after=CompareSql.byName(source.path(family));for(var entry:before.entrySet())if(!Objects.equals(entry.getValue(),after.get(entry.getKey()))){CompareSql.requireDestructive(plan,"Replace/remove "+family+" "+entry.getKey());plan.before.add("DROP "+(family.equals("triggers")?"TRIGGER":family.equals("rules")?"RULE":"POLICY")+" "+TableDesigner.q(entry.getKey())+" ON "+target);}
            for(var entry:after.entrySet())if(!Objects.equals(entry.getValue(),before.get(entry.getKey()))){var value=entry.getValue();if(family.equals("policies")){String command=Map.of("*","ALL","r","SELECT","a","INSERT","w","UPDATE","d","DELETE").get(str(value,"command"));if(command==null)throw new IllegalArgumentException("Unknown RLS command");plan.after.add("CREATE POLICY "+TableDesigner.q(entry.getKey())+" ON "+target+" AS "+(truth(value.path("polpermissive"))?"PERMISSIVE":"RESTRICTIVE")+" FOR "+command+" TO "+str(value,"roles")+(str(value,"using").isEmpty()?"":" USING ("+plan.mapped(str(value,"using"))+")")+(str(value,"check").isEmpty()?"":" WITH CHECK ("+plan.mapped(str(value,"check"))+")"));}else{plan.after.add(plan.mapped(str(value,"definition")));if(family.equals("triggers")&&!str(value,"enabled").equals("O"))plan.after.add("ALTER TABLE "+target+switch(str(value,"enabled")){case "D"->" DISABLE";case "R"->" ENABLE REPLICA";case "A"->" ENABLE ALWAYS";default->throw new IllegalArgumentException("Unknown trigger state");}+" TRIGGER "+TableDesigner.q(entry.getKey()));}}
        }
        var a=source.path("postgresAttributes");var b=dest==null?Profiles.JSON.createObjectNode():dest.path("postgresAttributes");for(String flag:List.of("relrowsecurity","relforcerowsecurity"))if(truth(a.path(flag))!=truth(b.path(flag)))plan.after.add("ALTER TABLE "+target+(flag.equals("relrowsecurity")?truth(a.path(flag))?" ENABLE":" DISABLE":truth(a.path(flag))?" FORCE":" NO FORCE")+" ROW LEVEL SECURITY");
    }
    static void finish(CompareSql.Plan plan,CompareSql.Choice choice){var source=choice.source();var dest=choice.destination();if(!source.has("postgresAttributes"))return;String kind=str(source,"kind"),type=switch(kind){case "views"->"VIEW";case "materialized_views"->"MATERIALIZED VIEW";case "functions"->"FUNCTION";case "procedures"->"PROCEDURE";case "sequences"->"SEQUENCE";case "types","domains"->str(source.path("postgresType"),"typtype").equals("d")?"DOMAIN":"TYPE";default->"TABLE";},target=Set.of("functions","procedures").contains(kind)?routineTarget(plan,source):plan.target(source),grantType=Set.of("functions","procedures","sequences").contains(kind)?type:Set.of("types","domains").contains(kind)?"TYPE":"TABLE";boolean rebuilt=plan.rebuilt.contains(key(str(source,"schema"),kind,str(source,"name")));var a=source.path("postgresAttributes");var b=dest==null||rebuilt?Profiles.JSON.createObjectNode():dest.path("postgresAttributes");
        if(!str(a,"comment").equals(str(b,"comment")))plan.after.add("COMMENT ON "+type+" "+target+" IS "+CompareData.literal(str(a,"comment"),"postgresql"));
        if(!source.path("identity").asBoolean()&&!source.has("ownership")&&!str(a,"owner").isBlank()&&!str(a,"owner").equals(str(b,"owner")))plan.after.add("ALTER "+type+" "+target+" OWNER TO "+TableDesigner.q(str(a,"owner")));
        if(kind.equals("materialized_views")&&(dest==null||rebuilt))for(JsonNode index:source.path("postgresIndexes"))if(!plan.selected.containsKey(key(str(source,"schema"),"indexes",str(index,"name"))))plan.after.add(plan.mapped(str(index,"definition")));
        if(Set.of("views","materialized_views").contains(kind))for(JsonNode column:source.path("postgresColumnComments"))if(!str(column,"comment").equals(dest==null||rebuilt?"":str(CompareSql.byName(dest.path("postgresColumnComments")).getOrDefault(str(column,"name"),Profiles.JSON.createObjectNode()),"comment")))plan.after.add("COMMENT ON COLUMN "+target+"."+TableDesigner.q(str(column,"name"))+" IS "+CompareData.literal(str(column,"comment"),"postgresql"));
        if(dest==null||rebuilt||!source.path("postgresGrants").equals(dest.path("postgresGrants"))){Set<String> grantees=new TreeSet<>();if(dest==null||rebuilt)grantees.add("PUBLIC");source.path("postgresGrants").forEach(g->grantees.add(str(g,"grantee")));if(dest!=null)dest.path("postgresGrants").forEach(g->grantees.add(str(g,"grantee")));if(dest!=null&&!rebuilt)CompareSql.requireDestructive(plan,"Replace object grants for "+str(source,"name"));for(String grantee:grantees)plan.finish.add("REVOKE ALL PRIVILEGES ON "+grantType+" "+target+" FROM "+(grantee.equals("PUBLIC")?"PUBLIC":TableDesigner.q(grantee)));for(JsonNode grant:source.path("postgresGrants")){String privilege=str(grant,"privilege_type");if(!Set.of("SELECT","INSERT","UPDATE","DELETE","TRUNCATE","REFERENCES","TRIGGER","MAINTAIN","EXECUTE","USAGE").contains(privilege))throw new IllegalArgumentException("Unsupported relation privilege "+privilege);String grantee=str(grant,"grantee");plan.finish.add("GRANT "+privilege+" ON "+grantType+" "+target+" TO "+(grantee.equals("PUBLIC")?"PUBLIC":TableDesigner.q(grantee))+(truth(grant.path("is_grantable"))?" WITH GRANT OPTION":""));}
        }
        if(source.has("postgresColumnGrants")&&(dest==null||rebuilt||!source.path("postgresGrants").equals(dest.path("postgresGrants"))||!source.path("postgresColumnGrants").equals(dest.path("postgresColumnGrants")))){
            if(dest!=null&&!rebuilt&&source.path("postgresGrants").equals(dest.path("postgresGrants")))for(JsonNode grant:dest.path("postgresColumnGrants")){CompareSql.requireDestructive(plan,"Replace column grants for "+str(source,"name"));if(CompareSql.byName(source.path("columns")).containsKey(str(grant,"column_name"))||!kind.equals("tables"))plan.finish.add(columnGrant("REVOKE",target,grant));}
            for(JsonNode grant:source.path("postgresColumnGrants"))plan.finish.add(columnGrant("GRANT",target,grant));
        }
    }
    static String columnGrant(String operation,String target,JsonNode grant){String privilege=str(grant,"privilege_type");if(!Set.of("SELECT","INSERT","UPDATE","REFERENCES").contains(privilege))throw new IllegalArgumentException("Unsupported column privilege "+privilege);String grantee=str(grant,"grantee");return operation+" "+privilege+" ("+TableDesigner.q(str(grant,"column_name"))+") ON TABLE "+target+(operation.equals("GRANT")?" TO ":" FROM ")+(grantee.equals("PUBLIC")?"PUBLIC":TableDesigner.q(grantee))+(operation.equals("GRANT")&&truth(grant.path("is_grantable"))?" WITH GRANT OPTION":"");}
    static boolean partition(CompareSql.Plan plan,CompareSql.Choice choice){
        var source=choice.source();var destination=choice.destination();if(!source.has("postgresPartition")&&(destination==null||!destination.has("postgresPartition")))return false;
        if(destination!=null){if(!CompareSql.same(plan,source,destination))throw new IllegalArgumentException("Existing partition-family changes require a reviewed attach/detach and row-routing migration");return true;}
        var partition=source.path("postgresPartition");String ddl="CREATE TABLE "+plan.target(source);
        if(!str(partition,"parent").isBlank())ddl+=" PARTITION OF "+CompareSql.qualified("postgresql",plan.schema(str(partition,"schema")),str(partition,"parent"))+" "+str(partition,"bound");
        else{List<String> columns=new ArrayList<>();source.path("columns").forEach(column->columns.add(CompareSql.column(plan,column,false)));ddl+=" ("+String.join(", ",columns)+")";}
        if(!str(partition,"key").isBlank())ddl+=" PARTITION BY "+str(partition,"key");ddl+=createStorage(source);plan.before.add(ddl);return true;
    }
    static String storageName(String name){if(!name.matches("[a-z_]+(?:\\.[a-z_]+)?"))throw new IllegalArgumentException("Unsupported PostgreSQL storage option");return name;}
    static String createStorage(JsonNode source){String result="";List<String> options=new ArrayList<>();for(JsonNode option:source.path("storageOptions"))options.add(storageName(str(option,"name"))+"="+CompareData.literal(str(option,"value"),"postgresql"));if(!options.isEmpty())result+=" WITH ("+String.join(", ",options)+")";String tablespace=source.path("postgresStorage").path("tablespace").asText();if(!tablespace.isBlank())result+=" TABLESPACE "+TableDesigner.q(tablespace);return result;}
    static void storage(CompareSql.Plan plan,CompareSql.Choice choice){if(choice.destination()==null)return;var source=choice.source();var destination=choice.destination();String target=plan.target(source);var a=source.path("postgresStorage");var b=destination.path("postgresStorage");if(!a.equals(b)||!source.path("storageOptions").equals(destination.path("storageOptions"))){CompareSql.requireDestructive(plan,"Change table storage "+str(source,"name"));if(!str(a,"persistence").equals(str(b,"persistence")))plan.before.add("ALTER TABLE "+target+(str(a,"persistence").equals("u")?" SET UNLOGGED":" SET LOGGED"));if(!str(a,"tablespace").equals(str(b,"tablespace")))plan.before.add("ALTER TABLE "+target+" SET TABLESPACE "+TableDesigner.q(str(a,"tablespace").isBlank()?"pg_default":str(a,"tablespace")));var before=CompareSql.byName(destination.path("storageOptions"));var after=CompareSql.byName(source.path("storageOptions"));for(String name:before.keySet())if(!after.containsKey(name))plan.before.add("ALTER TABLE "+target+" RESET ("+storageName(name)+")");for(var option:after.entrySet())if(!Objects.equals(option.getValue(),before.get(option.getKey())))plan.before.add("ALTER TABLE "+target+" SET ("+storageName(option.getKey())+"="+CompareData.literal(str(option.getValue(),"value"),"postgresql")+")");}}
    static void identity(CompareSql.Plan plan,String table,JsonNode before,JsonNode after){
        String old=str(before,"identity"),next=str(after,"identity"),column=TableDesigner.q(str(after,"name"));if(old.isEmpty()||next.isEmpty())throw new IllegalArgumentException("Adding/removing identity ownership requires an explicit backfill and sequence migration");
        if(!old.equals(next))plan.before.add("ALTER TABLE "+table+" ALTER COLUMN "+column+" SET GENERATED "+(next.equals("a")?"ALWAYS":"BY DEFAULT"));
        var a=after.path("identityOptions");var b=before.path("identityOptions");String sourceSchema=plan.schema(str(a,"schema"));if(!sourceSchema.equals(str(b,"schema")))throw new IllegalArgumentException("Identity sequence schema changes require a separate ownership migration");String sequence=CompareSql.qualified("postgresql",str(b,"schema"),str(b,"name"));
        for(String key:List.of("start","increment","minimum","maximum","cache","cycle"))if(!a.path(key).equals(b.path(key))){String option=switch(key){case "start"->"START WITH "+CompareSql.integer(str(a,key));case "increment"->"INCREMENT BY "+CompareSql.integer(str(a,key));case "minimum"->"MINVALUE "+CompareSql.integer(str(a,key));case "maximum"->"MAXVALUE "+CompareSql.integer(str(a,key));case "cache"->"CACHE "+CompareSql.integer(str(a,key));default->truth(a.path(key))?"CYCLE":"NO CYCLE";};plan.before.add("ALTER SEQUENCE "+sequence+" "+option);}
        if(!str(a,"name").equals(str(b,"name")))plan.before.add("ALTER SEQUENCE "+sequence+" RENAME TO "+TableDesigner.q(str(a,"name")));
    }
    private PostgresCompare(){}
}
