package io.doindev.codegraph.dba;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.*;
import java.sql.*;
import java.util.*;
import static io.doindev.codegraph.dba.ObjectCatalog.query;

/** Typed native operations; retained reviews contain no client SQL or credentials. */
final class RelationalAdminPlans {
    record Action(String id,String label,String category,List<String> fields){}
    static List<Action> definitions(String engine){boolean pg=engine.equals("postgresql"),maria=engine.equals("mariadb");List<Action> result=new ArrayList<>(List.of(
        new Action("create_user","Create login account","roles",pg?List.of("name"):List.of("name","host")),
        new Action("create_role","Create role","roles",pg||maria?List.of("name"):List.of("name","host")),
        new Action("password","Set account password","roles",pg?List.of("name"):List.of("name","host")),
        new Action("lock","Disable login","roles",pg?List.of("name"):List.of("name","host")),new Action("unlock","Enable login","roles",pg?List.of("name"):List.of("name","host")),
        new Action("grant_role","Grant role membership","membership",pg?List.of("name","role"):maria?List.of("name","host","role"):List.of("name","host","role","roleHost")),new Action("revoke_role","Revoke role membership","membership",pg?List.of("name","role"):maria?List.of("name","host","role"):List.of("name","host","role","roleHost")),
        new Action("grant_table","Grant table privilege","grants",pg?List.of("name","schema","object","privilege"):List.of("name","host","schema","object","privilege")),new Action("revoke_table","Revoke table privilege","grants",pg?List.of("name","schema","object","privilege"):List.of("name","host","schema","object","privilege")),
        new Action("create_schema",pg?"Create schema":"Create database","schemas",List.of("schema")),
        new Action("analyze","Analyze table","statistics",List.of("schema","object"))));
        if(pg){result.add(new Action("grant_default","Grant default table privilege","default_grants",List.of("name","role","schema","privilege")));result.add(new Action("revoke_default","Revoke default table privilege","default_grants",List.of("name","role","schema","privilege")));result.add(new Action("vacuum","Vacuum and analyze table","statistics",List.of("schema","object")));result.add(new Action("reindex","Reindex table (locks writes)","statistics",List.of("schema","object")));result.add(new Action("cancel","Cancel current query","sessions",List.of("pid")));result.add(new Action("terminate","Terminate session","sessions",List.of("pid")));result.add(new Action("create_extension","Install available extension","extensions",List.of("name","schema")));result.add(new Action("update_extension","Update extension to server default","extensions",List.of("name")));}
        else{result.add(new Action("check","Check table","statistics",List.of("schema","object")));result.add(new Action("optimize","Optimize table (may rebuild)","statistics",List.of("schema","object")));result.add(new Action("schema_defaults","Set database charset and collation","schemas",List.of("schema","charset","collation")));result.add(new Action("event_enable","Enable event","scheduler",List.of("schema","object")));result.add(new Action("event_disable","Disable event","scheduler",List.of("schema","object")));}
        return List.copyOf(result);
    }
    static ArrayNode actions(String engine){var out=Profiles.JSON.createArrayNode();for(Action action:definitions(engine)){var a=out.addObject().put("id",action.id()).put("label",action.label()).put("category",action.category());var fields=a.putArray("fields");for(String name:action.fields())fields.addObject().put("key",name).put("label",switch(name){case "name"->"Account / role name";case "host"->"Account host";case "roleHost"->"Role host";case "object"->"Object name";case "pid"->"PostgreSQL process ID";case "privilege"->"Privilege (SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER)";default->Character.toUpperCase(name.charAt(0))+name.substring(1);}).put("value",name.equals("host")||name.equals("roleHost")?"%":name.equals("privilege")?"SELECT":"");}return out;}
    static ObjectNode request(JsonNode input){if(!input.isObject())throw new IllegalArgumentException("Administration request required");Set<String> keys=Set.of("connectionId","database","action","name","host","role","roleHost","schema","object","privilege","pid","charset","collation");input.fieldNames().forEachRemaining(k->{if(!keys.contains(k))throw new IllegalArgumentException("Unexpected administration field: "+k);});for(JsonNode v:input)if(!v.isTextual()||v.asText().length()>256||v.asText().indexOf(0)>=0)throw new IllegalArgumentException("Administration fields must be bounded text");return input.deepCopy();}
    static String password(String value){if(value==null||value.length()<1||value.length()>256||value.indexOf(0)>=0||value.indexOf('\n')>=0||value.indexOf('\r')>=0)throw new IllegalArgumentException("Password must contain 1..256 characters without NUL or line breaks");return value;}
    static String literal(String value,String engine,String mode){return engine.equals("postgresql")?"E'"+value.replace("\\","\\\\").replace("'","''")+"'":MysqlDesigner.literal(value,MysqlScript.Mode.parse(mode).noBackslashEscapes());}
    static String text(JsonNode request,String name){String value=request.path(name).asText();if(value.isBlank()||value.length()>128||value.chars().anyMatch(Character::isISOControl))throw new IllegalArgumentException(name+" must contain 1..128 characters without control characters");return value;}
    static String quote(String engine,String name){return engine.equals("postgresql")?TableDesigner.q(name):MysqlDialect.quote(name);}
    static ObjectNode prepare(QueryJobs.Job job,Connection c,ObjectNode request)throws Exception{
        var target=RelationalAdministration.target(job,c);String engine=target.path("engine").asText(),mode=target.path("identity").path("sql_mode").asText(),action=text(request,"action");boolean pg=engine.equals("postgresql");var spec=definitions(engine).stream().filter(a->a.id().equals(action)).findFirst().orElseThrow(()->new IllegalArgumentException("Unsupported administration action"));for(String field:spec.fields())text(request,field);
        boolean maria=engine.equals("mariadb"),mariaRole=maria&&action.equals("create_role");String name=request.path("name").asText(),schema=request.path("schema").asText(),object=request.path("object").asText(),principal=name.isEmpty()?"":pg||mariaRole?quote(engine,name):literal(name,engine,mode)+"@"+literal(text(request,"host"),engine,mode);ObjectNode evidence=Profiles.JSON.createObjectNode();
        // Privileges are observed again at apply. PostgreSQL owners can maintain their own tables.
        var authority=pg?query(job,c,"SELECT oid,rolsuper,rolcreaterole,rolcreatedb FROM pg_roles WHERE rolname=current_user"):query(job,c,"SHOW GRANTS FOR CURRENT_USER");evidence.set("authority",authority);boolean superuser=pg&&CompareCatalog.truth(authority.path(0).path("rolsuper"));
        if(!name.isEmpty()){
            var rows=pg?query(job,c,"SELECT oid,rolname,rolcanlogin,rolvaliduntil,rolconnlimit,rolsuper,rolcreaterole,rolcreatedb FROM pg_roles WHERE rolname=?",name):query(job,c,engine.equals("mariadb")?"SELECT User,Host,plugin,is_role FROM mysql.user WHERE User=? AND Host=?":"SELECT User,Host,plugin,account_locked,password_expired FROM mysql.user WHERE User=? AND Host=?",name,mariaRole?"":text(request,"host"));
            if(!action.contains("extension")){boolean create=action.equals("create_user")||action.equals("create_role");if(create&&!rows.isEmpty()||!create&&rows.isEmpty())throw new IllegalArgumentException(create?"Account/role already exists":"Account/role is unavailable");}evidence.set("principal",rows);
        }
        if(!schema.isEmpty()){
            var rows=pg?query(job,c,"SELECT oid,nspname,nspowner,nspacl::text FROM pg_namespace WHERE nspname=?",schema):query(job,c,"SELECT SCHEMA_NAME,DEFAULT_CHARACTER_SET_NAME,DEFAULT_COLLATION_NAME FROM information_schema.SCHEMATA WHERE SCHEMA_NAME=?",schema);boolean create=action.equals("create_schema");if(create&&!rows.isEmpty()||!create&&rows.isEmpty())throw new IllegalArgumentException(create?"Schema/database already exists":"Schema/database is unavailable");evidence.set("schema",rows);
        }
        boolean table=!object.isEmpty()&&!action.startsWith("event_");String tableName=object.isEmpty()?"":quote(engine,schema)+"."+quote(engine,object);
        if(table){if(pg){var rows=query(job,c,"SELECT c.oid,c.relkind,c.relowner,c.relacl::text,pg_has_role(c.relowner,'MEMBER') AS owner FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=? AND c.relname=? AND c.relkind IN ('r','p','m')",schema,object);if(rows.size()!=1)throw new IllegalArgumentException("Table is unavailable");evidence.set("table",rows);evidence.set("columns",query(job,c,"SELECT a.attname,format_type(a.atttypid,a.atttypmod) AS type,a.attnotnull,COALESCE(pg_get_expr(d.adbin,d.adrelid),'') AS default FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE a.attrelid=?::oid AND a.attnum>0 AND NOT a.attisdropped ORDER BY a.attnum",rows.path(0).path("oid").asText()));if(!superuser&&!CompareCatalog.truth(rows.path(0).path("owner")))throw new IllegalArgumentException("Administration requires table ownership or superuser privileges");}
            else evidence.set("table",query(job,c,"SHOW CREATE TABLE "+tableName));}
        if(pg&&!table&&!superuser)throw new IllegalArgumentException("Account, schema, extension and session administration requires a PostgreSQL superuser in this workspace");
        if(!pg){String grants=authority.toString().toUpperCase(Locale.ROOT);if(!(grants.contains(" ON *.* TO ")&&(grants.contains("ALL PRIVILEGES")||grants.contains("CREATE USER")&&grants.contains("GRANT OPTION"))))throw new IllegalArgumentException("MySQL administration requires explicit global administrative grants; inherited role privileges are not inferred");}
        String sql;boolean secret=Set.of("create_user","password").contains(action);String prefix="",suffix="";
        switch(action){
            case "create_user"->{prefix=pg?"CREATE ROLE "+principal+" LOGIN PASSWORD ":"CREATE USER "+principal+" IDENTIFIED BY ";sql=prefix+"<password supplied when applying>";}
            case "create_role"->sql="CREATE ROLE "+principal;
            case "password"->{prefix=pg?"ALTER ROLE "+principal+" PASSWORD ":"ALTER USER "+principal+" IDENTIFIED BY ";sql=prefix+"<password supplied when applying>";}
            case "lock","unlock"->sql=(pg?"ALTER ROLE "+principal+(action.equals("lock")?" NOLOGIN":" LOGIN"):"ALTER USER "+principal+(action.equals("lock")?" ACCOUNT LOCK":" ACCOUNT UNLOCK"));
            case "grant_role","revoke_role"->{String role=text(request,"role"),roleHost=maria?"":request.path("roleHost").asText();var rows=pg?query(job,c,"SELECT oid,rolname FROM pg_roles WHERE rolname=?",role):query(job,c,"SELECT User,Host FROM mysql.user WHERE User=? AND Host=?",role,roleHost);if(rows.size()!=1)throw new IllegalArgumentException("Granted role does not exist");evidence.set("role",rows);String roleName=pg||maria?quote(engine,role):literal(role,engine,mode)+"@"+literal(roleHost,engine,mode);sql=(action.equals("grant_role")?"GRANT "+roleName+" TO ":"REVOKE "+roleName+" FROM ")+principal;}
            case "grant_default","revoke_default"->{String role=text(request,"role"),privilege=text(request,"privilege").toUpperCase(Locale.ROOT);if(!Set.of("SELECT","INSERT","UPDATE","DELETE","TRUNCATE","REFERENCES","TRIGGER").contains(privilege))throw new IllegalArgumentException("Unsupported default table privilege");var roles=query(job,c,"SELECT oid,rolname FROM pg_roles WHERE rolname=?",role);if(roles.size()!=1)throw new IllegalArgumentException("Creator role is unavailable");evidence.set("creator",roles);evidence.set("defaultAcl",query(job,c,"SELECT d.oid,d.defaclacl::text FROM pg_default_acl d JOIN pg_roles r ON r.oid=d.defaclrole LEFT JOIN pg_namespace n ON n.oid=d.defaclnamespace WHERE r.rolname=? AND (d.defaclnamespace=0 OR n.nspname=?)",role,schema));sql="ALTER DEFAULT PRIVILEGES FOR ROLE "+quote(engine,role)+" IN SCHEMA "+quote(engine,schema)+(action.equals("grant_default")?" GRANT ":" REVOKE ")+privilege+" ON TABLES"+(action.equals("grant_default")?" TO ":" FROM ")+principal;}
            case "grant_table","revoke_table"->{String privilege=text(request,"privilege").toUpperCase(Locale.ROOT);if(!Set.of("SELECT","INSERT","UPDATE","DELETE","REFERENCES","TRIGGER").contains(privilege))throw new IllegalArgumentException("Unsupported table privilege");sql=(action.equals("grant_table")?"GRANT ":"REVOKE ")+privilege+" ON "+(pg?"TABLE ":"")+tableName+(action.equals("grant_table")?" TO ":" FROM ")+principal;}
            case "create_schema"->sql="CREATE "+(pg?"SCHEMA ":"DATABASE ")+quote(engine,schema);
            case "analyze"->sql=(pg?"ANALYZE ":"ANALYZE TABLE ")+tableName;
            case "vacuum"->sql="VACUUM (ANALYZE) "+tableName;
            case "reindex"->sql="REINDEX TABLE "+tableName;
            case "check"->sql="CHECK TABLE "+tableName;
            case "optimize"->sql="OPTIMIZE TABLE "+tableName;
            case "schema_defaults"->{String charset=text(request,"charset"),collation=text(request,"collation");var rows=query(job,c,"SELECT COLLATION_NAME,CHARACTER_SET_NAME FROM information_schema.COLLATIONS WHERE COLLATION_NAME=? AND CHARACTER_SET_NAME=?",collation,charset);if(rows.size()!=1)throw new IllegalArgumentException("Charset/collation pair is unavailable");evidence.set("collation",rows);sql="ALTER DATABASE "+quote(engine,schema)+" CHARACTER SET "+quote(engine,charset)+" COLLATE "+quote(engine,collation);}
            case "cancel","terminate"->{String pid=text(request,"pid");if(!pid.matches("[1-9][0-9]{0,8}"))throw new IllegalArgumentException("Invalid process ID");var rows=query(job,c,"SELECT pid,backend_start::text,usename,datname,query_start::text,query FROM pg_stat_activity WHERE pid=? AND pid<>pg_backend_pid() AND backend_type='client backend'",Integer.parseInt(pid));if(rows.size()!=1)throw new IllegalArgumentException("Client session is no longer available");evidence.set("session",rows);sql="SELECT "+(action.equals("cancel")?"pg_cancel_backend":"pg_terminate_backend")+"(pid) AS signal_sent FROM pg_stat_activity WHERE pid="+pid+" AND backend_start="+literal(rows.path(0).path("backend_start").asText(),engine,mode)+"::timestamptz AND query_start IS NOT DISTINCT FROM "+(rows.path(0).path("query_start").isNull()?"NULL":literal(rows.path(0).path("query_start").asText(),engine,mode)+"::timestamptz");}
            case "create_extension","update_extension"->{var available=query(job,c,"SELECT name,default_version,installed_version FROM pg_available_extensions WHERE name=?",name);if(available.size()!=1)throw new IllegalArgumentException("Extension is not available on this server");boolean installed=!available.path(0).path("installed_version").isNull();if(action.equals("create_extension")==installed)throw new IllegalArgumentException(installed?"Extension already exists":"Extension is not installed");evidence.set("extension",available);sql=action.equals("create_extension")?"CREATE EXTENSION "+quote(engine,name)+" WITH SCHEMA "+quote(engine,schema)+" VERSION "+literal(available.path(0).path("default_version").asText(),engine,mode):"ALTER EXTENSION "+quote(engine,name)+" UPDATE TO "+literal(available.path(0).path("default_version").asText(),engine,mode);}
            case "event_enable","event_disable"->{var rows=query(job,c,"SHOW CREATE EVENT "+tableName);if(rows.size()!=1)throw new IllegalArgumentException("Event is unavailable");evidence.set("event",rows);sql="ALTER EVENT "+tableName+(action.equals("event_enable")?" ENABLE":" DISABLE");}
            default->throw new IllegalArgumentException("Unsupported action");
        }
        ObjectNode plan=Profiles.JSON.createObjectNode().put("relationalAdminPlan",true).put("action",action).put("label",spec.label()).put("requiresPassword",secret).put("atomic",false);plan.set("request",request.deepCopy());plan.set("target",target);plan.set("preconditions",evidence);var command=plan.putArray("commands").addObject().put("sql",sql);if(secret)command.put("password",true).put("prefix",prefix).put("suffix",suffix);plan.put("sql",sql+";").put("warning","Apply runs the displayed operation on this resolved target. Maintenance can acquire locks or rebuild tables; account and extension changes affect database security. MySQL DDL commits implicitly. A lost connection may leave an unknown outcome.");plan.put("fingerprint",TableDesigner.hash(plan)).put("expiresAt",System.currentTimeMillis()+300000);return plan;
    }
    private RelationalAdminPlans(){}
}
