package io.doindev.codegraph.dba;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.*;
import java.sql.*;
import java.util.*;
import java.util.concurrent.CancellationException;

/** Local-human administration, with expiring target-bound review and one-time apply. */
final class RelationalAdministration {
    record Catalog(String id,String label,String sql,String order){}
    private final Connections connections;private final QueryJobs jobs;
    RelationalAdministration(Connections connections,QueryJobs jobs){this.connections=connections;this.jobs=jobs;}
    static List<Catalog> catalogs(String engine){return engine.equals("postgresql")?List.of(
        new Catalog("roles","Roles and users","SELECT oid,rolname,rolsuper,rolinherit,rolcreaterole,rolcreatedb,rolcanlogin,rolreplication,rolconnlimit,rolvaliduntil FROM pg_roles","rolname"),
        new Catalog("membership","Role membership","SELECT r.rolname AS role,m.rolname AS member,g.rolname AS grantor,a.admin_option FROM pg_auth_members a JOIN pg_roles r ON r.oid=a.roleid JOIN pg_roles m ON m.oid=a.member JOIN pg_roles g ON g.oid=a.grantor","role,member"),
        new Catalog("grants","Object grants","SELECT grantor,grantee,table_schema,table_name,privilege_type,is_grantable FROM information_schema.table_privileges","grantee,table_schema,table_name,privilege_type"),
        new Catalog("default_grants","Default privileges","SELECT pg_get_userbyid(d.defaclrole) AS creator,COALESCE(n.nspname,'all schemas') AS schema,d.defaclobjtype::text AS object_type,CASE a.grantee WHEN 0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END AS grantee,a.privilege_type,a.is_grantable FROM pg_default_acl d LEFT JOIN pg_namespace n ON n.oid=d.defaclnamespace CROSS JOIN LATERAL aclexplode(d.defaclacl) a","creator,schema,object_type,grantee,privilege_type"),
        new Catalog("databases","Databases","SELECT d.oid,d.datname,pg_get_userbyid(d.datdba) AS owner,pg_encoding_to_char(d.encoding) AS encoding,d.datcollate,d.datctype,d.datallowconn,d.datconnlimit FROM pg_database d","datname"),
        new Catalog("schemas","Schemas","SELECT oid,nspname,pg_get_userbyid(nspowner) AS owner,nspacl::text AS grants FROM pg_namespace WHERE nspname NOT LIKE 'pg_%' AND nspname<>'information_schema'","nspname"),
        new Catalog("sessions","Sessions and active SQL","SELECT pid,usename,datname,application_name,client_addr::text,backend_start,state,wait_event_type,wait_event,xact_start,query_start,query FROM pg_stat_activity WHERE backend_type='client backend'","pid"),
        new Catalog("locks","Locks","SELECT pid,locktype,database,relation,mode,granted,waitstart FROM pg_locks","pid,locktype,mode"),
        new Catalog("diagnostics","Database diagnostics","SELECT datname,numbackends,xact_commit,xact_rollback,blks_read,blks_hit,tup_returned,tup_fetched,tup_inserted,tup_updated,tup_deleted,deadlocks,temp_files,temp_bytes,stats_reset FROM pg_stat_database","datname"),
        new Catalog("statistics","Table statistics and maintenance","SELECT schemaname,relname,n_live_tup,n_dead_tup,n_mod_since_analyze,last_vacuum,last_autovacuum,last_analyze,last_autoanalyze,vacuum_count,analyze_count FROM pg_stat_user_tables","schemaname,relname"),
        new Catalog("extensions","Extensions","SELECT e.extname,e.extversion,n.nspname AS schema,pg_get_userbyid(e.extowner) AS owner,e.extrelocatable FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace","extname"),
        new Catalog("replication","Replication","SELECT pid,usename,application_name,client_addr::text,state,sent_lsn::text,write_lsn::text,flush_lsn::text,replay_lsn::text,sync_state FROM pg_stat_replication","pid"),
        new Catalog("slots","Replication slots","SELECT slot_name,plugin,slot_type,database,active,restart_lsn::text,confirmed_flush_lsn::text FROM pg_replication_slots","slot_name"),
        new Catalog("scheduler","pg_cron jobs","SELECT jobid,schedule,command,nodename,nodeport,database,username,active FROM cron.job","jobid")
    ):List.of(
        new Catalog("roles","Accounts (user and host)",engine.equals("mariadb")?"SELECT User AS user,Host AS host,plugin,is_role FROM mysql.user":"SELECT User AS user,Host AS host,plugin,account_locked,password_expired,password_last_changed FROM mysql.user","user,host"),
        new Catalog("membership","Role membership",engine.equals("mariadb")?"SELECT Host AS host,User AS user,Role AS role,Admin_option AS admin_option FROM mysql.roles_mapping":"SELECT FROM_USER AS role,FROM_HOST AS role_host,TO_USER AS user,TO_HOST AS host,WITH_ADMIN_OPTION AS admin_option FROM mysql.role_edges","user,host,role"),
        new Catalog("grants","Global privileges","SELECT GRANTEE,PRIVILEGE_TYPE,IS_GRANTABLE FROM information_schema.USER_PRIVILEGES","GRANTEE,PRIVILEGE_TYPE"),
        new Catalog("object_grants","Object grants","SELECT GRANTEE,TABLE_SCHEMA,TABLE_NAME,PRIVILEGE_TYPE,IS_GRANTABLE FROM information_schema.TABLE_PRIVILEGES","GRANTEE,TABLE_SCHEMA,TABLE_NAME,PRIVILEGE_TYPE"),
        new Catalog("schemas","Databases and defaults","SELECT SCHEMA_NAME,DEFAULT_CHARACTER_SET_NAME,DEFAULT_COLLATION_NAME FROM information_schema.SCHEMATA","SCHEMA_NAME"),
        new Catalog("sessions","Sessions and active SQL","SELECT ID,USER,HOST,DB,COMMAND,TIME,STATE,INFO FROM information_schema.PROCESSLIST","ID"),
        new Catalog("locks","Locks",engine.equals("mariadb")?"SELECT * FROM information_schema.INNODB_LOCKS":"SELECT ENGINE,ENGINE_LOCK_ID,ENGINE_TRANSACTION_ID,THREAD_ID,OBJECT_SCHEMA,OBJECT_NAME,INDEX_NAME,LOCK_TYPE,LOCK_MODE,LOCK_STATUS,LOCK_DATA FROM performance_schema.data_locks",engine.equals("mariadb")?"lock_id":"ENGINE_LOCK_ID"),
        new Catalog("diagnostics","Server diagnostics",engine.equals("mariadb")?"SELECT VARIABLE_NAME,VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS":"SELECT VARIABLE_NAME,VARIABLE_VALUE FROM performance_schema.global_status","VARIABLE_NAME"),
        new Catalog("statistics","Table statistics and maintenance","SELECT TABLE_SCHEMA,TABLE_NAME,ENGINE,TABLE_ROWS,DATA_LENGTH,INDEX_LENGTH,DATA_FREE,AUTO_INCREMENT,TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_TYPE='BASE TABLE' AND TABLE_SCHEMA NOT IN ('mysql','sys','information_schema','performance_schema')","TABLE_SCHEMA,TABLE_NAME"),
        new Catalog("scheduler","Event Scheduler","SELECT EVENT_SCHEMA,EVENT_NAME,DEFINER,TIME_ZONE,EVENT_TYPE,EXECUTE_AT,INTERVAL_VALUE,INTERVAL_FIELD,STATUS,LAST_EXECUTED FROM information_schema.EVENTS","EVENT_SCHEMA,EVENT_NAME"),
        new Catalog("replication","Replication",engine.equals("mariadb")?"SELECT VARIABLE_NAME,VARIABLE_VALUE FROM information_schema.GLOBAL_STATUS WHERE VARIABLE_NAME LIKE 'Slave%'":"SELECT CHANNEL_NAME,SERVICE_STATE,LAST_ERROR_NUMBER,LAST_ERROR_MESSAGE,LAST_ERROR_TIMESTAMP FROM performance_schema.replication_connection_status",engine.equals("mariadb")?"VARIABLE_NAME":"CHANNEL_NAME")
    );}
    static ObjectNode target(QueryJobs.Job job,Connection c)throws Exception{
        String engine=ObjectCreation.engine(c);if(!engine.equals("postgresql")&&!MysqlDialect.supports(engine))throw new IllegalArgumentException("Choose a native PostgreSQL, MySQL or MariaDB connection");if(!CompareCatalog.supported(c,engine))throw new IllegalArgumentException("This server version is not supported by Administration");
        ObjectNode out=Profiles.JSON.createObjectNode().put("engine",engine).put("database",Objects.toString(c.getCatalog(),"")).put("version",c.getMetaData().getDatabaseProductVersion()).put("major",c.getMetaData().getDatabaseMajorVersion()).put("user",c.getMetaData().getUserName());
        var rows=ObjectCatalog.query(job,c,engine.equals("postgresql")?"SELECT current_user AS principal,pg_postmaster_start_time()::text AS instance,inet_server_addr()::text AS address,inet_server_port() AS port":engine.equals("mariadb")?"SELECT CURRENT_USER() AS principal,@@server_id AS instance,@@hostname AS address,@@port AS port,@@SESSION.sql_mode AS sql_mode":"SELECT CURRENT_USER() AS principal,@@server_uuid AS instance,@@hostname AS address,@@port AS port,@@SESSION.sql_mode AS sql_mode");out.set("identity",rows.get(0));return out;
    }
    private String connection(String owner,JsonNode input){if(owner.startsWith("agent:"))throw new SecurityException("Administration is browser-only");String id=Profiles.text(input,"connectionId",36);if(connections.genericOnly(id))throw new IllegalArgumentException("Choose a native database connection");return id;}
    ObjectNode read(String owner,JsonNode input){String id=connection(owner,input);JsonNode request=input.deepCopy();return jobs.local(owner,id,job->{try(var selected=connections.target(id,request.path("database").asText())){var c=selected.connection();var target=target(job,c);String engine=target.path("engine").asText(),category=request.path("category").asText("overview");job.progress="Reading "+engine+" administration / "+category;
        if(category.equals("overview")){ObjectNode result=Profiles.JSON.createObjectNode();result.set("target",target);var categories=result.putArray("categories");catalogs(engine).forEach(cat->categories.addObject().put("id",cat.id()).put("label",cat.label()));result.set("actions",RelationalAdminPlans.actions(engine));return result.put("scopeNotice","Catalog rows reflect this account's privileges. Missing access is reported per category; an empty result does not prove absence.");}
        var cat=catalogs(engine).stream().filter(x->x.id().equals(category)).findFirst().orElseThrow(()->new IllegalArgumentException("Unknown administration category"));int offset=request.path("offset").asInt();if(offset<0||offset>100000)throw new IllegalArgumentException("Invalid catalog offset");int limit=Math.min(100,job.rowLimit);ObjectNode result=Profiles.JSON.createObjectNode().put("category",category).put("label",cat.label()).put("offset",offset).put("pageSize",limit).put("observedAt",System.currentTimeMillis());result.set("target",target);
        try{var rows=ObjectCatalog.query(job,c,"SELECT * FROM ("+cat.sql()+") AS catalog_page ORDER BY "+cat.order()+" LIMIT ? OFFSET ?",limit+1,offset);boolean more=rows.size()>limit;if(more)rows.remove(rows.size()-1);result.set("rows",rows);return result.put("available",true).put("hasMore",more);}catch(SQLException e){if(job.cancelled||CompareCatalog.fatal(e))throw e;return result.put("available",false).put("hasMore",false).put("message","This category is unavailable for the current privileges or server capabilities. SQLSTATE "+Objects.toString(e.getSQLState(),"unknown")+", vendor "+e.getErrorCode()+": "+e.getMessage());}
    }},()->{});}
    ObjectNode backup(String owner,JsonNode input){String id=connection(owner,input);JsonNode request=input.deepCopy();return jobs.local(owner,id,job->{try(var selected=connections.target(id,request.path("database").asText())){job.progress="Generating manual native backup/restore script";return RelationalBackupScripts.generate(job,selected.connection(),request);}},()->{});}
    ObjectNode prepare(String owner,JsonNode input){String id=connection(owner,input);ObjectNode request=RelationalAdminPlans.request(input);return jobs.local(owner,id,job->{try(var selected=connections.target(id,request.path("database").asText())){job.progress="Validating administration target, privileges and preconditions";ObjectNode plan=RelationalAdminPlans.prepare(job,selected.connection(),request);plan.put("profileRevision",ProjectContexts.profileRevision(connections.profile(id)));return plan;}},()->{});}
    ObjectNode apply(String owner,JsonNode input){if(owner.startsWith("agent:"))throw new SecurityException("Administration is browser-only");if(!input.path("confirmed").isBoolean()||!input.path("confirmed").asBoolean())throw new IllegalArgumentException("Review and acknowledge the operation first");var preview=jobs.require(owner,Profiles.text(input,"planId",36));ObjectNode plan;String secret;
        synchronized(preview){if(!preview.state.equals("complete")||preview.result==null||!preview.result.path("relationalAdminPlan").asBoolean()||preview.designerPlanUsed||preview.result.path("expiresAt").asLong()<System.currentTimeMillis())throw new IllegalArgumentException("Review expired or was used; prepare a new review");plan=((ObjectNode)preview.result).deepCopy();secret=plan.path("requiresPassword").asBoolean()?RelationalAdminPlans.password(input.path("password").asText()):"";preview.designerPlanUsed=true;}
        String id=preview.connection;return jobs.local(owner,id,job->{ObjectNode report=Profiles.JSON.createObjectNode().put("status","failed");ArrayNode steps=report.putArray("steps");job.result=report;boolean executing=false,secretDispatched=false;int completed=0;
            try(var selected=connections.target(id,plan.path("request").path("database").asText())){Connection c=selected.connection();if(!c.getAutoCommit())c.rollback();c.setAutoCommit(true);c.setReadOnly(false);if(!plan.path("profileRevision").asText().equals(ProjectContexts.profileRevision(connections.profile(id))))throw new IllegalArgumentException("Connection changed; review again");var observed=RelationalAdminPlans.prepare(job,c,(ObjectNode)plan.path("request"));if(!observed.path("fingerprint").equals(plan.path("fingerprint")))throw new IllegalArgumentException("Target, privileges or affected object changed; review again");
                for(JsonNode command:plan.path("commands")){if(job.cancelled)throw new CancellationException();String sql=command.path("sql").asText();if(command.path("password").asBoolean())sql=command.path("prefix").asText()+RelationalAdminPlans.literal(secret,plan.path("target").path("engine").asText(),plan.path("target").path("identity").path("sql_mode").asText())+command.path("suffix").asText();job.progress="Applying reviewed administration operation "+(completed+1);try(var s=c.createStatement()){job.statement=s;s.setQueryTimeout(job.remainingSeconds());executing=true;secretDispatched=command.path("password").asBoolean();boolean rows=s.execute(sql);if(rows)try(var result=s.getResultSet()){var values=ObjectCatalog.rows(job,result);report.set("results",values);}executing=false;completed++;steps.addObject().put("index",completed).put("status","acknowledged");}finally{job.statement=null;}}
                job.outcome="commit_acknowledged";return report.put("status","success").put("outcome","steps_acknowledged").put("message","The server acknowledged the reviewed operation. Inspect returned status rows for maintenance warnings.");
            }catch(Exception failure){String outcome=executing&&(job.cancelled||failure instanceof SQLTimeoutException||failure instanceof CancellationException||failure instanceof SQLException sql&&Objects.toString(sql.getSQLState(),"").startsWith("08"))?"unknown":completed>0?"partial":"not_applied";job.outcome=outcome;return report.put("status",job.cancelled?"cancelled":"failed").put("outcome",outcome).put("message",!secretDispatched?connections.humanError(id,failure):"Account operation failed; details were withheld to avoid disclosing its password. Inspect the account before retrying.");}
        },()->{});
    }
}
